import type { ActiveSitePage } from "./site-content";

export const manualJourneyPages = [
  {
    id: "P01",
    status: "active",
    name: "Home",
    path: "/",
    canonicalPath: "/",
    seo: {
      title: "Halo Database | One Database, Three Operating Modes",
      description: "Explore how Halo 1.0.16 handles compatibility, migration decisions, conditional role changes, database-aware routing, and partitioned data placement.",
      canonicalPath: "/",
      robots: "index, follow",
    },
    breadcrumb: [],
    localNavigation: [],
    hero: {
      eyebrow: "Compatibility-led database modernization",
      h1: "One database. Three ways in.",
      lead: "Halo 1.0.16 supports Oracle, MySQL, and PostgreSQL operating modes within one cluster. Explore compatibility, migration, continuity, and distributed data one mechanism at a time.",
      actions: [
        { label: "Explore the mechanisms", href: "#technology-story", kind: "primary" },
        { label: "Explore the architecture", href: "/product/architecture/", kind: "secondary" },
        { label: "Prepare a demo brief", href: "/request-demo/?source=home-hero", kind: "text" },
      ],
    },
    blocks: [
      {
        type: "diagram",
        anchor: "technology-story",
        eyebrow: "Five problems · Five distinct mechanisms",
        heading: "See what changes inside Halo.",
        intro: [
          "Each section isolates one customer problem, the Halo mechanism that addresses it, and the result a team can evaluate next.",
        ],
        layout: "flow",
        nodes: [
          {
            label: "COMPATIBILITY",
            heading: "Keep expected application behavior in view.",
            body: [
              "Migration risk is rarely SQL alone: protocol, types, procedural logic, metadata, and optimizer-visible semantics can all matter.",
              "Halo E5 carries a selected Oracle, MySQL, or native PostgreSQL operating-mode request through protocol, parsing and semantics, optimization, and execution.",
              "Teams can trace where behavior is interpreted before validating exact workload coverage.",
            ],
            tone: "accent",
          },
          {
            label: "MIGRATION",
            heading: "Turn hidden dependencies into decisions.",
            body: [
              "Moving rows does not resolve procedural logic, remote access, drivers, tools, or transactional expectations.",
              "The evaluation path inventories each dependency, maps documented candidates, assigns representative tests, and keeps remediation or unresolved gaps visible.",
              "The team leaves with retain, verify, remediate, or stop decisions instead of a generic compatibility percentage.",
            ],
            tone: "default",
          },
          {
            label: "HIGH AVAILABILITY",
            heading: "Move a role only after the control path agrees.",
            body: [
              "A failed primary can become a split-brain risk if traffic moves before control state and fencing are established.",
              "Shield evaluates health plus etcd quorum and leader state, protects the topology through fencing, checks replica eligibility, and coordinates role and VIP movement when conditions pass.",
              "A role change becomes an explicit, conditional sequence—not an unconditional failover promise.",
            ],
            tone: "dark",
          },
          {
            label: "READ / WRITE ROUTING",
            heading: "Let database semantics choose the path.",
            body: [
              "A read-only connection usually cannot accept a write without application or proxy routing logic.",
              "TWR uses statement semantics, transaction state, and object type to keep read work local and forward detected writes to the read/write node, returning the result through the original connection.",
              "Teams can evaluate a database-aware route without treating TWR as an external proxy or a latency guarantee.",
            ],
            tone: "accent",
          },
          {
            label: "SHARDING",
            heading: "Route a partition to the data that owns its range.",
            body: [
              "A distributed query becomes wasteful when every data node receives work that its range cannot answer.",
              "HDS presents one logical database through a worker; partition mappings, shard_fdw, predicate pushdown, and pruning direct relevant ranges to independent Halo data nodes.",
              "Teams can understand the placement model before evaluating worker availability, resharding, and cross-shard transaction requirements.",
            ],
            tone: "muted",
          },
        ],
        caption: ["These are simplified mechanism explainers, not deployment topologies. Results depend on the Halo build, selected mode or component, settings, workload, topology, and operating policy."],
      },
      {
        type: "facts",
        anchor: "product-proof",
        heading: "Migration started the product. Workload evidence decides the fit.",
        intro: ["The Halo 1.0.16 documentation records the history and product counts below. None replaces evaluation against the target workload and topology."],
        items: [
          { value: "2012", label: "manual-traced migration origin", body: "The Halo manual traces the database lineage to an Oracle application migration challenge." },
          { value: "≥95%", label: "manual-reported Oracle-related application code-change reduction", body: "Reported from Oracle migration practice; workload-specific, not universal and not a forecast." },
          { value: "45", label: "documented extensions", body: "Grouped across diagnostics, data, search, integration, security, events, and utilities." },
        ],
      },
      {
        type: "cta",
        heading: "Start with the proof you need.",
        body: ["Investigate a mechanism, build a defined proof-of-concept scope, or prepare the product and commercial questions your team needs next."],
        actions: [
          { label: "Build your PoC scope", href: "/resources/evaluation-checklist/", kind: "primary" },
          { label: "Evaluate an Oracle workload", href: "/oracle-migration-evaluation/", kind: "secondary" },
          { label: "Prepare a demo brief", href: "/request-demo/?source=home-final", kind: "text" },
          { label: "Ask about product access", href: "/contact-sales/?source=home-final", kind: "text" },
        ],
      },
    ],
    withheldModules: [
      { id: "case-proof", status: "absent", requires: ["A01"] },
      { id: "partner-strip", status: "absent", requires: ["A08", "A06", "A12"] },
    ],
  },
  {
    id: "P07",
    status: "active",
    name: "Proof-of-concept method",
    path: "/evaluation/",
    canonicalPath: "/evaluation/",
    seo: {
      title: "Halo Database Proof-of-Concept Method",
      description: "Define the workload, test Halo against agreed criteria, and leave with a proceed, remediate, or stop decision.",
      canonicalPath: "/evaluation/",
      robots: "index, follow",
    },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Proof of concept" }],
    localNavigation: [],
    hero: {
      eyebrow: "PROOF OF CONCEPT",
      h1: "Turn product capability into a workload decision.",
      lead: "A Halo PoC defines the application, target architecture, and acceptance criteria before testing compatibility, performance, continuity, distributed behavior, and day-to-day operations.",
      actions: [
        { label: "Open the evaluation checklist", href: "/resources/evaluation-checklist/", kind: "primary" },
        { label: "Prepare a PoC", href: "/request-poc/?source=evaluation", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "steps",
        heading: "Five steps to a defensible decision",
        items: [
          { heading: "1. Frame the decision", body: ["Name the application, source product and version, business reason, owners, decision date, and non-negotiable requirements."] },
          { heading: "2. Map the dependency surface", body: ["Inventory objects, procedural logic, drivers, frameworks, integrations, transaction behavior, data profile, workload, and operating dependencies."] },
          { heading: "3. Select the Halo architecture", body: ["Choose the mode, topology, replication and recovery design, distributed components, operating environment, exact build, and optional modules in scope."] },
          { heading: "4. Run representative tests", body: ["Test application behavior, integrations, workload, failover, backup, restore, PITR, diagnostics, and operator tasks under agreed conditions."] },
          { heading: "5. Record the decision", body: ["Mark each material requirement passed as tested, passed with remediation, unsupported in scope, or not tested; assign owners and retest conditions before recommending proceed, remediate, or stop."] },
        ],
      },
      {
        type: "callout",
        label: "PRODUCT ACCESS",
        heading: "A Halo Database PoC needs the right package and license",
        body: ["Halo Database is commercial, licensed software; it is not the open-source openHalo project. Before testing begins, Halo Tech confirms the target platform and build, provides the installation package, and prepares a license for the PoC environment. Use the PoC preparation route to coordinate access with the company."],
      },
      {
        type: "comparison",
        heading: "A demo and a PoC answer different questions",
        columns: ["Demo", "Proof of concept"],
        rows: [
          ["Introduces documented capabilities", "Tests a defined workload"],
          ["Uses prepared product material", "Uses representative application inputs"],
          ["Helps decide whether to investigate", "Helps decide whether to proceed"],
          ["Does not establish application fit", "Produces scoped evidence and exceptions"],
        ],
      },
      {
        type: "cards",
        heading: "Run the lanes that affect the decision",
        items: [
          { heading: "Compatibility", body: ["Application behavior, database objects, procedural logic, drivers, tools, integrations, transactions, and errors."] },
          { heading: "Workload", body: ["Representative query mix, concurrency, batch work, resource use, stability, and agreed performance measures."] },
          { heading: "Continuity", body: ["Replication, failover, reconnect, backup, validation, restore, PITR, and former-primary rejoin."] },
          { heading: "Operations", body: ["Monitoring, HWR, diagnostics, maintenance, resource controls, administration tools, and ownership."] },
          { heading: "Distributed topology", body: ["DLB, TWR, HSM, or HDS routing, failure, consistency, placement, and lifecycle behavior when applicable."] },
        ],
      },
      {
        type: "checklist",
        heading: "What a useful PoC leaves behind",
        items: [
          "Source and target inventory",
          "Requirement-to-test matrix",
          "Reproducible environment record",
          "Observations and retained evidence",
          "Compatibility and exception register",
          "Remediation, ownership, and retest plan",
          "Proceed, remediate, or stop recommendation",
        ],
      },
      {
        type: "callout",
        label: "EVIDENCE DISCIPLINE",
        heading: "Keep source, conditions, and limits attached",
        body: ["A manual statement is not a workload result. A generic benchmark is not an application result. Every conclusion should preserve the build, environment, topology, inputs, measurement, and unresolved boundaries behind it."],
      },
      {
        type: "cta",
        heading: "Define what Halo must prove.",
        actions: [{ label: "Prepare a PoC", href: "/request-poc/?source=evaluation-final", kind: "primary" }],
      },
    ],
    withheldModules: [],
  },
  {
    id: "P08",
    status: "active",
    name: "Resources",
    path: "/resources/",
    canonicalPath: "/resources/",
    seo: {
      title: "Halo Database Resources",
      description: "Find Halo product, migration, architecture, recovery, distributed-data, operations, evidence, and evaluation resources by question.",
      canonicalPath: "/resources/",
      robots: "index, follow",
    },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Resources" }],
    localNavigation: [],
    hero: {
      eyebrow: "RESOURCES",
      h1: "Find the product answer by question—not by manual chapter.",
      lead: "Explore what Halo supports, how migration is evaluated, how continuity is designed, how the platform is operated, and what evidence still needs to be produced.",
      actions: [
        { label: "Start with the platform", href: "/product/", kind: "primary" },
        { label: "Open the evaluation checklist", href: "/resources/evaluation-checklist/", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "cards",
        heading: "Choose a path",
        items: [
          { heading: "Understand the platform", body: ["Start with the openHalo-based core, multimode architecture, and enterprise capability map."], actions: [{ label: "Product overview", href: "/product/", kind: "text" }, { label: "Architecture", href: "/product/architecture/", kind: "text" }] },
          { heading: "Plan compatibility and migration", body: ["Review Oracle, MySQL, and PostgreSQL behavior, then turn application dependencies into a migration assessment."], actions: [{ label: "Compatibility", href: "/product/compatibility/", kind: "text" }, { label: "Oracle migration", href: "/oracle-migration-evaluation/", kind: "text" }] },
          { heading: "Design continuity and distributed data", body: ["Explore replication, recovery, Shield, DLB, TWR, HSM, and HDS with their documented boundaries."], actions: [{ label: "Availability & recovery", href: "/product/availability-recovery/", kind: "text" }, { label: "Distributed data", href: "/product/distributed/", kind: "text" }] },
          { heading: "Operate and extend", body: ["Review tuning surfaces, resource controls, HWR, system visibility, data types, federation, and optional modules."], actions: [{ label: "Operations", href: "/product/operations/", kind: "text" }, { label: "Data & extensions", href: "/product/data-platform/", kind: "text" }] },
          { heading: "Trace claims", body: ["See the source behind material statements, what each establishes, and what still requires validation."], actions: [{ label: "Evidence & validation", href: "/resources/evidence/", kind: "text" }, { label: "Documentation basis", href: "/resources/documentation/", kind: "text" }] },
          { heading: "Prepare an evaluation", body: ["Capture the workload, target architecture, acceptance criteria, and decision owners before requesting a PoC."], actions: [{ label: "Evaluation checklist", href: "/resources/evaluation-checklist/", kind: "text" }, { label: "PoC method", href: "/evaluation/", kind: "text" }] },
        ],
      },
      {
        type: "callout",
        label: "CONTENT BOUNDARY",
        heading: "Product knowledge here; operating instructions in documentation",
        body: ["This website explains capability, architecture, value, and limits. SQL, commands, configuration files, terminal output, screenshots, and step-by-step operating procedures are intentionally not reproduced in the enterprise-site body."],
      },
    ],
    withheldModules: [],
  },
  {
    id: "P09",
    status: "active",
    name: "Documentation basis",
    path: "/resources/documentation/",
    canonicalPath: "/resources/documentation/",
    seo: {
      title: "Halo 1.0.16 Product Documentation Basis",
      description: "See how the Halo 1.0.16 manual is reorganized into enterprise product, migration, architecture, and operations content.",
      canonicalPath: "/resources/documentation/",
      robots: "index, follow",
    },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Resources", href: "/resources/" }, { label: "Documentation basis" }],
    localNavigation: [],
    hero: {
      eyebrow: "DOCUMENTATION BASIS",
      h1: "Product knowledge, reorganized for enterprise evaluation.",
      lead: "This website uses the complete Halo 1.0.16 user-manual Markdown set as its primary product source, then reorganizes that knowledge around customer questions rather than reproducing the manual chapter by chapter.",
      actions: [
        { label: "Review evidence", href: "/resources/evidence/", kind: "primary" },
        { label: "Explore the platform", href: "/product/", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "comparison",
        heading: "What belongs where",
        columns: ["On this website", "In technical documentation"],
        rows: [
          ["Product positioning and capability", "Exact commands and syntax"],
          ["Architecture and topology concepts", "Installation and CLI procedures"],
          ["Compatibility scope and boundaries", "SQL, DDL, DML, and language examples"],
          ["Migration and operational value", "Configuration files and parameter values"],
          ["Evidence limits and evaluation questions", "Terminal output, logs, and troubleshooting steps"],
        ],
      },
      {
        type: "accordion",
        heading: "The source families behind the site",
        items: [
          { heading: "Product and architecture", summary: "Chapters 1–2", details: ["Product origin and release history, instance/cluster architecture, transactions, storage, indexes, partitioning, and database objects."] },
          { heading: "Deployment and tuning", summary: "Chapters 3–6", details: ["Documented processor and operating-system families, installer workflow, initialization, character sets, and configuration surfaces."] },
          { heading: "Compatibility", summary: "Chapters 7–10", details: ["E5, multiple operating modes, and Oracle, MySQL, and native PostgreSQL behavior and boundaries."] },
          { heading: "Backup and availability", summary: "Chapters 11–15", details: ["Protection models, RMAN2, physical/logical/grouped replication, and Halo Shield."] },
          { heading: "Distributed capabilities", summary: "Chapters 16–19", details: ["DLB, TWR, HSM, and HDS architecture and operational boundaries."] },
          { heading: "Operations and tooling", summary: "Chapters 20–22", details: ["Resource controls, HWR, Statement Sharing, and DBeaver."] },
          { heading: "Reference inventories", summary: "Appendices A–G", details: ["SQL object families, RMAN2 scope, system catalogs/views, 45 extensions, structured errors, compatibility additions, and Shield cluster operations. Syntax and commands are excluded from the site body while the capabilities they prove are retained."] },
        ],
      },
      {
        type: "facts",
        heading: "Frozen source snapshot used for this refactor",
        items: [
          { value: "80", label: "Markdown files" },
          { value: "40,934", label: "source lines" },
          { value: "14,502", label: "nonblank non-code lines" },
          { value: "80/80", label: "hash matches", body: "Every file matched the source map at the implementation freeze." },
        ],
      },
      {
        type: "checklist",
        heading: "Before relying on a documented capability",
        items: [
          "Confirm the exact Halo version and build",
          "Confirm the operating mode and optional modules",
          "Separate capability description from configuration example",
          "Preserve stated limitations and prerequisites",
          "Validate the requirement with the intended application and topology",
        ],
      },
      {
        type: "callout",
        label: "VERSION NOTE",
        heading: "Halo 1.0.16 is the factual release baseline",
        body: ["The release history identifies Halo 1.0.16 as the second LTS release, published in June 2024. Current package availability, platform certification, and support scope still require confirmation for a specific deployment."],
      },
      {
        type: "callout",
        label: "PRODUCT ACCESS",
        heading: "Public documentation is not a public Halo Database download",
        body: ["Halo Database is commercial, licensed software. The official installation documentation directs evaluators to Halo Tech sales, support, or an authorized agent for the installation package, and to sales or support for the license file. For a PoC, coordinate the exact build, target environment, package, and license with Halo Tech before following the installation procedure."],
      },
      {
        type: "links",
        actions: [
          { label: "Contact Halo Tech for PoC access", href: "mailto:support@halodbtech.com?subject=Halo%20Database%20PoC%20access", kind: "primary" },
          { label: "Prepare a PoC", href: "/request-poc/?source=documentation-access", kind: "text" },
        ],
      },
    ],
    withheldModules: [],
  },
  {
    id: "P10",
    status: "active",
    name: "Evidence and validation",
    path: "/resources/evidence/",
    canonicalPath: "/resources/evidence/",
    seo: {
      title: "Evidence & Validation | Halo Database",
      description: "See what material Halo statements establish, their manual source, their limits, and what a workload evaluation must validate.",
      canonicalPath: "/resources/evidence/",
      robots: "index, follow",
    },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Resources", href: "/resources/" }, { label: "Evidence & Validation" }],
    localNavigation: [],
    hero: {
      eyebrow: "EVIDENCE & VALIDATION",
      h1: "See what each Halo claim establishes—and what it does not.",
      lead: "Material statements are paired with their manual source, practical meaning, boundary, and workload question.",
      actions: [
        { label: "Open the evaluation checklist", href: "/resources/evaluation-checklist/", kind: "primary" },
        { label: "See the documentation basis", href: "/resources/documentation/", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "evidence",
        heading: "Material product evidence",
        fieldLabels: { statement: "Documented statement", source: "Manual source", limit: "What it does not prove", test: "What to validate" },
        records: [
          { heading: "Product identity and release", statement: "Halo is described as an openHalo-based, general-purpose unified database. Halo 1.0.16 is listed as the second LTS release, published in June 2024.", source: "Chapters 1–2", limit: "This does not confirm current packaging, certification, regional service, or an English legal company identity.", test: "Confirm the exact build, package, platform, and support scope intended for deployment." },
          { heading: "Multimode compatibility", statement: "One instance can run Oracle, MySQL, and PostgreSQL modes concurrently; E5 spans protocol, parsing/semantics, optimization, and execution.", source: "Chapter 7; Chapters 8–10", limit: "This does not establish complete equivalence or unchanged behavior for every application.", test: "Test the data types, functions, objects, procedural behavior, drivers, transactions, and errors the application uses." },
          { heading: "Reported Oracle migration practice", statement: "The manual reports at least 95% lower Oracle-related application code changes in migration practice.", source: "Chapter 1; Oracle overview", limit: "This is not a universal percentage, zero-change promise, hour-scale promise, or performance guarantee.", test: "Measure required changes against a representative dependency inventory and PoC record." },
          { heading: "Continuity and recovery", statement: "The manual documents physical/logical replication and backup; incremental physical modes; validation; and PITR to time, LSN, transaction ID, restore point, or timeline.", source: "Chapters 11–15; Appendix B", limit: "Mechanisms alone do not establish an SLA, RPO, or RTO. Sync and async choices differ.", test: "Exercise the intended topology, failure, reconnect, data state, and operator procedure." },
          { heading: "Distributed data paths", statement: "DLB, TWR, HSM, and HDS address read distribution, write forwarding, shared storage, and sharded placement as distinct components.", source: "Chapters 16–19", limit: "The source does not establish universal active-active behavior, linear scale, online resharding, distributed transactions, or topology-independent durability.", test: "Select the component and topology, then test routing, failure, consistency, placement, lifecycle, and operations." },
          { heading: "Operations and observability", statement: "HWR snapshots and interval reports, 139 catalog/view objects, and 45 extension modules provide documented paths for visibility and diagnostics.", source: "Chapter 21; Appendices C–D", limit: "Counts do not mean every module is installed or enabled by default; HWR has dependencies and collection behavior.", test: "Confirm installed modules, permissions, collection settings, retention, overhead, and workflow." },
          { heading: "Documented platform reach", statement: "The installation material lists multiple x86, ARM, MIPS, and Alpha families and several Linux distributions plus FreeBSD.", source: "Chapter 3", limit: "A manual list is not a current certification or support matrix.", test: "Confirm processor, operating-system version, package, and support status before procurement." },
        ],
      },
      {
        type: "callout",
        label: "NOT PUBLISHED AS PRODUCT FACT",
        heading: "Claims without a sufficient canonical basis",
        body: ["No evidence record is published for DataOS, SQL firewall, universal RPO 0, universal sub-60-second RTO, zero code change, zero performance loss, HSM active-active/RAC equivalence, HDS linear scaling, or a general AI platform beyond the documented MRT/catalog mechanism."],
      },
    ],
    withheldModules: [],
  },
  {
    id: "P11",
    status: "active",
    name: "Evaluation checklist",
    path: "/resources/evaluation-checklist/",
    canonicalPath: "/resources/evaluation-checklist/",
    seo: {
      title: "Halo Database Evaluation Checklist",
      description: "Prepare the application, compatibility surface, data, workload, target architecture, operations, and acceptance record for a Halo PoC.",
      canonicalPath: "/resources/evaluation-checklist/",
      robots: "index, follow",
    },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Resources", href: "/resources/" }, { label: "Evaluation checklist" }],
    localNavigation: [],
    hero: {
      eyebrow: "EVALUATION CHECKLIST",
      h1: "Bring the application, architecture, and decision criteria.",
      lead: "Use this checklist to define a representative Halo evaluation before testing begins.",
      actions: [
        { label: "Prepare a PoC", href: "/request-poc/?source=checklist", kind: "primary" },
        { label: "See the PoC method", href: "/evaluation/", kind: "secondary" },
      ],
    },
    blocks: [
      { type: "checklist", heading: "1. Decision and source estate", items: ["Application, business purpose, and criticality", "Source product, edition, version, and topology", "Business owner, technical owner, and decision date", "Migration, consolidation, or architecture question", "Non-negotiable and stop-early requirements"] },
      { type: "checklist", heading: "2. Compatibility surface", items: ["Required Oracle, MySQL, or PostgreSQL mode", "Types, functions, operators, and query behavior", "Schemas, tables, indexes, partitions, views, and sequences", "Procedures, functions, packages, triggers, and temporary objects", "Transactions, isolation, locking, and error behavior", "DBLINK, foreign-data, and extension dependencies"] },
      { type: "checklist", heading: "3. Application and integration", items: ["Drivers, connection pools, frameworks, and ORM", "Jobs, reporting, administration, and monitoring tools", "Authentication, authorization, and cryptographic requirements", "Upstream, downstream, and external-service dependencies"] },
      { type: "checklist", heading: "4. Data and workload", items: ["Data volume, distribution, growth, and retention", "Representative transactions and query mix", "Concurrency, batch windows, and peak conditions", "Latency, throughput, stability, and resource criteria", "Sensitive-data and secure-transfer constraints"] },
      { type: "checklist", anchor: "target-architecture", heading: "5. Target architecture and continuity", items: ["Processor, operating system, storage, network, and topology", "Replication mode and synchronization level", "Failover, switchover, fencing, and application reconnect", "Backup type, validation, retention, restore, and PITR", "DLB, TWR, HSM, or HDS requirements when applicable"] },
      { type: "checklist", anchor: "operations", heading: "6. Operations and observability", items: ["Installation and configuration ownership", "Monitoring, HWR, and diagnostic evidence", "Resource controls and tuning responsibilities", "Maintenance, upgrade, and recovery procedures", "Required extensions and administration tools"] },
      { type: "checklist", heading: "7. Acceptance and decision record", items: ["Requirement owner and test owner", "Expected result and measurement method", "Evidence to retain", "Passed, remediation, unsupported, or untested status", "Retest conditions", "Proceed, remediate, or stop recommendation"] },
      {
        type: "callout",
        label: "DATA HANDLING",
        heading: "Keep sensitive material out of public inquiry routes",
        body: ["Do not place credentials, production records, customer data, or confidential database content in a public inquiry. Agree on secure transfer and representative test-data handling during qualification."],
      },
      { type: "cta", heading: "Ready to define the evidence plan?", actions: [{ label: "Prepare a PoC", href: "/request-poc/?source=checklist-final", kind: "primary" }] },
    ],
    withheldModules: [],
  },
  {
    id: "P14",
    status: "active",
    name: "About Halo Tech",
    path: "/company/",
    canonicalPath: "/company/",
    seo: {
      title: "About Halo Tech | Halo Database",
      description: "Meet the engineering team behind commercial Halo Database and the open-source openHalo project, and understand how to start an enterprise evaluation.",
      canonicalPath: "/company/",
      robots: "index, follow",
    },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Company" }],
    localNavigation: [
      { label: "Company", anchor: "company-story" },
      { label: "Capabilities", anchor: "company-capabilities" },
      { label: "Halo Database and openHalo", anchor: "product-paths" },
      { label: "Product history", anchor: "product-provenance" },
      { label: "PoC access", anchor: "commercial-access" },
      { label: "Contact", anchor: "company-contact" },
    ],
    hero: {
      eyebrow: "ABOUT HALO TECH",
      h1: "Database engineering, from kernel to enterprise rollout.",
      lead: "Halo Tech focuses on next-generation data management. Its leadership brings experience from tier-one financial institutions and global technology companies, while an engineering-led team works across database kernel research, product development, lifecycle maintenance, and enterprise implementation.",
      actions: [
        { label: "Explore Halo Database", href: "/product/", kind: "primary" },
        { label: "Discuss a PoC", href: "/request-poc/?source=company", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "prose",
        anchor: "company-story",
        heading: "Engineering-led and enterprise-grounded",
        paragraphs: [
          { text: "Halo Tech specializes in data management technology for demanding enterprise systems. More than 80% of the team works in technical roles, keeping product decisions close to database engineering and implementation realities." },
          { text: "The company maintains end-to-end capability across database kernel research, product engineering, lifecycle maintenance, and enterprise implementation. That combination connects core R&D with the assessment, migration, deployment, optimization, and ongoing work required in real customer environments." },
        ],
      },
      {
        type: "facts",
        heading: "An engineering-led organization",
        items: [
          { value: "80%+", label: "technical roles", body: "The official company profile describes a predominantly technical team." },
          { value: "4", label: "delivery disciplines", body: "Kernel research, product engineering, lifecycle maintenance, and enterprise implementation." },
          { value: "End-to-end", label: "delivery scope", body: "From assessment and migration through deployment, maintenance, and operations." },
        ],
      },
      {
        type: "cards",
        anchor: "company-capabilities",
        heading: "One team across the database lifecycle",
        items: [
          { heading: "Kernel research", body: ["Database internals, compatibility architecture, optimization, storage, and core-engine research."] },
          { heading: "Product engineering", body: ["Release development, tooling, integration, quality, and the work required to turn core technology into an enterprise product."] },
          { heading: "Lifecycle maintenance", body: ["Updates, maintenance, troubleshooting, and operational continuity after deployment."] },
          { heading: "Enterprise implementation", body: ["Assessment, migration, deployment, optimization, and system change in customer environments."] },
        ],
      },
      {
        type: "comparison",
        anchor: "product-paths",
        heading: "Halo Database and openHalo serve different paths",
        columns: ["Halo Database", "openHalo"],
        rows: [
          ["Offering — Commercial, licensed enterprise database software", "Offering — GPL-3.0 open-source database project initiated by Halo Tech"],
          ["Access — Installation packages and license files are provided through Halo Tech, support, or authorized agents", "Access — Source code is publicly available for inspection, building, and contribution"],
          ["Scope — Oracle, MySQL, and PostgreSQL operating modes with enterprise deployment and lifecycle services", "Scope — Protocol-level MySQL compatibility on a PostgreSQL foundation"],
          ["Next step — Qualify the environment, package, license, workload, and acceptance criteria with Halo Tech", "Next step — Explore the code, open an issue, improve documentation, or contribute code"],
        ],
      },
      {
        type: "cards",
        heading: "What openHalo makes available to the community",
        intro: ["openHalo is the company’s separate open-source project. It is designed to help MySQL-facing applications work with a PostgreSQL-based database while retaining familiar protocols and development workflows."],
        items: [
          { heading: "Native MySQL protocol", body: ["Applications can continue to use familiar MySQL clients, commands, and drivers against the project’s compatibility surface."] },
          { heading: "SQL compatibility", body: ["The project targets commonly used MySQL SQL dialects and behavior to reduce migration changes and risk."] },
          { heading: "Open engineering", body: ["Source code, documentation, examples, issue reporting, and code contribution are part of the public development path."] },
          { heading: "Teaching and participation", body: ["openHalo has been used as a Peking University graduate teaching-practice project and encourages student and community contribution."] },
        ],
      },
      {
        type: "links",
        actions: [
          { label: "Visit openHalo", href: "https://www.openhalo.org/", kind: "secondary" },
          { label: "View openHalo on GitHub", href: "https://github.com/HaloTech-Co-Ltd/openHalo", kind: "text" },
        ],
      },
      {
        type: "steps",
        anchor: "product-provenance",
        heading: "Product provenance",
        items: [
          { heading: "2012 — The starting problem", body: ["The founding team began database work around an Oracle application migration; the first recorded compatibility effort focused on SYSDATE behavior."] },
          { heading: "2021 — First V1 release", body: ["Halo 1.0.13 extended Oracle-oriented procedural compatibility."] },
          { heading: "2022 — First LTS", body: ["Halo 1.0.14 introduced E5, GB18030 support, PL/SQL Package capability, and MySQL protocol and syntax support."] },
          { heading: "June 2024 — Second LTS", body: ["Halo 1.0.16 documented concurrent PostgreSQL, MySQL, and Oracle modes and additional distributed components."] },
          { heading: "2025 — openHalo", body: ["Halo Tech launched the openHalo project to develop its MySQL protocol-compatibility path in the open."] },
        ],
      },
      {
        type: "callout",
        anchor: "commercial-access",
        label: "PLANNING A POC?",
        heading: "Halo Database access is coordinated with the company",
        body: ["Halo Database is commercial, licensed software; it is not the open-source openHalo project. To run a PoC, contact Halo Tech before installation. The team confirms the target platform and build, provides the appropriate installation package, and prepares a license file for the target server environment. A license that does not match the environment will prevent the database from starting."],
      },
      {
        type: "cards",
        anchor: "company-contact",
        heading: "Talk with Halo Tech",
        items: [
          { label: "EMAIL", heading: "support@halodbtech.com", body: ["Product access, licensing, technical support, and PoC coordination."], actions: [{ label: "Send an email", href: "mailto:support@halodbtech.com?subject=Halo%20Database%20inquiry", kind: "text" }] },
          { label: "PHONE", heading: "0571-87168929", body: ["The contact number published by Halo Tech for direct coordination."], actions: [{ label: "Call Halo Tech", href: "tel:+8657187168929", kind: "text" }] },
        ],
      },
      {
        type: "cta",
        heading: "Choose the path that matches your goal.",
        body: ["Coordinate a licensed Halo Database evaluation with the company, or explore openHalo as the public open-source project."],
        actions: [
          { label: "Discuss a Halo Database PoC", href: "mailto:support@halodbtech.com?subject=Halo%20Database%20PoC%20inquiry", kind: "primary" },
          { label: "Explore openHalo", href: "https://www.openhalo.org/", kind: "secondary" },
        ],
      },
    ],
    withheldModules: [],
  },
  {
    id: "P15",
    status: "active",
    name: "Plan a proof of concept",
    path: "/request-poc/",
    canonicalPath: "/request-poc/",
    seo: { title: "Plan a Halo Database PoC", description: "Coordinate a Halo Database installation package, environment-specific license, and workload-focused proof of concept with Halo Tech.", canonicalPath: "/request-poc/", robots: "noindex, follow" },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Plan a PoC" }],
    localNavigation: [
      { label: "Product access", anchor: "poc-product-access" },
      { label: "PoC process", anchor: "poc-process" },
      { label: "What to prepare", anchor: "poc-preparation" },
      { label: "Contact", anchor: "poc-contact" },
    ],
    hero: {
      eyebrow: "PLAN A PROOF OF CONCEPT",
      h1: "Plan the workload. Halo Tech coordinates product access.",
      lead: "Halo Database is commercial, licensed software—not the open-source openHalo project. A PoC begins by qualifying the workload and target environment with Halo Tech, which then coordinates the appropriate installation package, environment-specific license, and technical guidance.",
      actions: [
        { label: "Contact Halo Tech for PoC access", href: "mailto:support@halodbtech.com?subject=Halo%20Database%20PoC%20access", kind: "primary" },
        { label: "Open the evaluation checklist", href: "/resources/evaluation-checklist/", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "callout",
        anchor: "poc-product-access",
        label: "PRODUCT ACCESS",
        heading: "The installation package and license come from Halo Tech",
        body: ["Halo Database is not a self-service open-source download. The official installation guidance directs evaluators to sales, support, or an authorized agent for the installation package, and to sales or support for the license file. The license is generated for server-environment information and may encode validity, release, and connection limits; if it does not match the environment, the database will not start."],
      },
      {
        type: "steps",
        anchor: "poc-process",
        heading: "From qualification to evidence",
        items: [
          { heading: "1. Frame the decision", body: ["Name the application, source database, business reason, owners, acceptance criteria, and the questions the PoC must resolve."] },
          { heading: "2. Share the target environment", body: ["Provide the operating system, processor architecture, server count, topology, database modes, and optional components expected in the test."] },
          { heading: "3. Confirm package and license", body: ["Halo Tech confirms the applicable release and build, then coordinates the installation package and a license prepared for the agreed PoC environment."] },
          { heading: "4. Install and verify", body: ["Install the supplied build, place the matching license, initialize the database, and verify that the intended modes and services start correctly."] },
          { heading: "5. Run the workload and record the decision", body: ["Test representative behavior, performance, continuity, recovery, integrations, and operator tasks; retain the evidence, exceptions, remediation, and next decision."] },
        ],
      },
      {
        type: "checklist",
        anchor: "poc-preparation",
        heading: "Prepare before qualification",
        items: [
          "Organization, role, country or region, and business contact",
          "Source database, version, application purpose, and criticality",
          "Required Oracle, MySQL, or PostgreSQL operating mode and database dependencies",
          "Target operating system, processor architecture, server count, and topology",
          "Representative data, workload profile, continuity, recovery, and operating requirements",
          "Acceptance criteria, decision owners, and target decision date",
        ],
      },
      {
        type: "callout",
        label: "SAFE COORDINATION",
        heading: "Exchange sensitive environment details through an agreed channel",
        body: ["Do not send credentials, production records, customer data, or detailed hardware identifiers in an initial public email. First describe the environment at a high level; Halo Tech can then agree a secure method for any server information needed to prepare the license."],
      },
      {
        type: "links",
        anchor: "poc-contact",
        heading: "Start the conversation",
        actions: [
          { label: "Email support@halodbtech.com", href: "mailto:support@halodbtech.com?subject=Halo%20Database%20PoC%20access", kind: "primary" },
          { label: "Call 0571-87168929", href: "tel:+8657187168929", kind: "secondary" },
          { label: "Review the PoC method", href: "/evaluation/", kind: "text" },
        ],
      },
      {
        type: "cta",
        heading: "Ready to qualify a Halo Database PoC?",
        body: ["Send the high-level workload, target platform, and evaluation goal. Package, license, technical scope, timing, and regional availability are confirmed during qualification."],
        actions: [
          { label: "Contact Halo Tech", href: "mailto:support@halodbtech.com?subject=Halo%20Database%20PoC%20access", kind: "primary" },
          { label: "Review commercial planning", href: "/contact-sales/?source=request-poc", kind: "secondary" },
        ],
      },
    ],
    withheldModules: [{ id: "form-shell", status: "absent", requires: ["A06", "A12"] }],
  },
  {
    id: "P17",
    status: "active",
    name: "Prepare a demo brief",
    path: "/request-demo/",
    canonicalPath: "/request-demo/",
    seo: { title: "Prepare a Halo Database Demo Brief", description: "Choose the Halo capabilities to organize for a future product introduction.", canonicalPath: "/request-demo/", robots: "noindex, follow" },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Prepare a Demo Brief" }],
    localNavigation: [],
    hero: { eyebrow: "PREPARE A DEMO BRIEF", h1: "Choose the Halo capabilities you want to explore.", lead: "Use this route to prepare a future product-introduction brief. A demo can refine technical questions, but it does not validate application compatibility, performance, recovery objectives, or production readiness.", actions: [{ label: "Explore the platform", href: "/product/", kind: "primary" }, { label: "Prepare a PoC instead", href: "/request-poc/?source=demo", kind: "secondary" }] },
    blocks: [
      { type: "cards", heading: "Possible demo topics", items: [{ heading: "Compatibility and E5", body: ["Oracle, MySQL, and native PostgreSQL paths."] }, { heading: "Core architecture", body: ["Transactions, storage, indexing, and partitioning."] }, { heading: "Continuity", body: ["Replication, RMAN2, and Shield."] }, { heading: "Distributed data", body: ["DLB, TWR, HSM, and HDS."] }, { heading: "Operations", body: ["HWR, system visibility, resource controls, and extensions."] }] },
      { type: "comparison", heading: "What a demo can and cannot establish", columns: ["A demo can", "A demo cannot"], rows: [["Orient business and technical stakeholders", "Prove that an application moves unchanged"], ["Identify relevant architecture paths", "Establish representative performance or capacity"], ["Surface questions for evaluation", "Set an RPO, RTO, or SLA"], ["Help decide whether to prepare a PoC", "Estimate migration effort or production readiness"]] },
      { type: "callout", label: "INQUIRY STATUS", heading: "This remains an informational route", body: ["The current source set does not include an approved public scheduling endpoint, privacy notice, or consent flow. No form or response-time promise is published."] },
    ],
    withheldModules: [{ id: "form-shell", status: "absent", requires: ["A06", "A12"] }],
  },
  {
    id: "P16",
    status: "active",
    name: "Product access and commercial planning",
    path: "/contact-sales/",
    canonicalPath: "/contact-sales/",
    seo: { title: "Halo Database Product Access & Licensing", description: "Contact Halo Tech about Halo Database installation packages, licenses, PoC access, procurement, and regional availability.", canonicalPath: "/contact-sales/", robots: "noindex, follow" },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Product Access & Licensing" }],
    localNavigation: [],
    hero: {
      eyebrow: "PRODUCT ACCESS AND LICENSING",
      h1: "Discuss product access, licensing, and commercial fit.",
      lead: "Halo Database is commercial, licensed software. Contact Halo Tech for the appropriate installation package, license, PoC access, procurement questions, deployment scope, and regional availability. openHalo is the separate open-source project.",
      actions: [
        { label: "Email Halo Tech", href: "mailto:support@halodbtech.com?subject=Halo%20Database%20product%20access", kind: "primary" },
        { label: "Plan a workload PoC", href: "/request-poc/?source=sales", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "callout",
        label: "COMMERCIAL PRODUCT",
        heading: "Halo Database and openHalo have different access models",
        body: ["Halo Database installation packages and license files are provided through company coordination; they are not obtained from the openHalo repository. openHalo is the GPL-3.0 community project for MySQL protocol compatibility. A Halo Database PoC or deployment requires the company to confirm the applicable product build and license scope."],
      },
      {
        type: "cards",
        heading: "Contact Halo Tech",
        items: [
          { label: "EMAIL", heading: "support@halodbtech.com", body: ["Product packages, licenses, PoC coordination, technical support, and commercial questions."], actions: [{ label: "Send an email", href: "mailto:support@halodbtech.com?subject=Halo%20Database%20product%20access", kind: "text" }] },
          { label: "PHONE", heading: "0571-87168929", body: ["The contact number published by Halo Tech."], actions: [{ label: "Call Halo Tech", href: "tel:+8657187168929", kind: "text" }] },
        ],
      },
      {
        type: "checklist",
        heading: "Prepare the product-access context",
        items: [
          "Organization, role, country or region, and business contact",
          "Whether the request is for a PoC, product introduction, procurement review, or planned deployment",
          "Source database, application, and operating modes of interest",
          "Target operating system, processor architecture, server count, and topology",
          "Expected evaluation or deployment stage, timing, and decision owners",
          "Commercial, procurement, licensing, or service-availability questions",
        ],
      },
      {
        type: "cards",
        heading: "Choose the right conversation",
        items: [
          { heading: "Defined workload", body: ["Use the PoC path when a specific application, target environment, and acceptance criteria are known."], actions: [{ label: "Plan a PoC", href: "/request-poc/?source=sales-card", kind: "text" }] },
          { heading: "Product introduction", body: ["Use the demo path to orient stakeholders and refine product questions before a workload is ready."], actions: [{ label: "Prepare a demo brief", href: "/request-demo/?source=sales-card", kind: "text" }] },
          { heading: "Open-source exploration", body: ["Use openHalo when the goal is to inspect, build, or contribute to the public MySQL-compatibility project."], actions: [{ label: "Explore openHalo", href: "https://www.openhalo.org/", kind: "text" }] },
        ],
      },
      {
        type: "callout",
        label: "QUALIFICATION BOUNDARY",
        heading: "The exact package, license, support scope, and availability are confirmed for the engagement",
        body: ["An inquiry does not by itself confirm PoC acceptance, package entitlement, licensing terms, price, support level, regional availability, or response time. Halo Tech confirms those details after reviewing the intended environment and use."],
      },
      {
        type: "cta",
        heading: "Start with the access question you have.",
        actions: [
          { label: "Email Halo Tech", href: "mailto:support@halodbtech.com?subject=Halo%20Database%20product%20access", kind: "primary" },
          { label: "Plan a PoC", href: "/request-poc/?source=sales-final", kind: "secondary" },
        ],
      },
    ],
    withheldModules: [{ id: "form-shell", status: "absent", requires: ["A06", "A12"] }],
  },
  {
    id: "P20",
    status: "active",
    name: "Page not found",
    path: "/404/",
    canonicalPath: null,
    seo: { title: "Page not found | Halo Database", description: null, canonicalPath: null, robots: "noindex, follow" },
    breadcrumb: [],
    localNavigation: [],
    hero: { eyebrow: null, h1: "Page not found.", lead: "The page may have moved, or the address may be incorrect. Continue with one of the destinations below.", actions: [{ label: "Go to Home", href: "/", kind: "primary" }, { label: "Explore the platform", href: "/product/", kind: "text" }, { label: "Review documentation", href: "/resources/documentation/", kind: "text" }] },
    blocks: [],
    withheldModules: [],
  },
] as const satisfies readonly ActiveSitePage[];
