import type { ActiveSitePage } from "./site-content";

export const manualEnterprisePages = [
  {
    id: "P05",
    status: "active",
    name: "Availability and recovery",
    path: "/product/availability-recovery/",
    canonicalPath: "/product/availability-recovery/",
    seo: {
      title: "Availability & Recovery | Halo Database",
      description: "Explore Halo replication, grouped durability, Halo Shield orchestration, RMAN2 backup, validation, and point-in-time recovery.",
      canonicalPath: "/product/availability-recovery/",
      robots: "index, follow",
    },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Platform", href: "/product/" }, { label: "Availability & Recovery" }],
    localNavigation: [
      { label: "Continuity stack", anchor: "continuity-stack" },
      { label: "Replication", anchor: "replication" },
      { label: "Grouped replication", anchor: "grouped-replication" },
      { label: "Halo Shield", anchor: "shield" },
      { label: "Backup and recovery", anchor: "backup-recovery" },
      { label: "Validation", anchor: "recovery-validation" },
    ],
    hero: {
      eyebrow: "AVAILABILITY & RECOVERY",
      h1: "Keep services recoverable. Make the trade-offs visible.",
      lead: "Halo combines WAL-based replication, queryable standbys, failover orchestration, and logical and physical recovery paths. Commit policy, topology, distance, and operating discipline determine the result.",
      actions: [
        { label: "Plan a resilience evaluation", href: "/resources/evaluation-checklist/#target-architecture", kind: "primary" },
        { label: "See the PoC method", href: "/evaluation/", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "diagram",
        anchor: "continuity-stack",
        heading: "Four working layers support continuity",
        intro: ["Replication moves change, orchestration manages database roles, a service address directs traffic, and backup provides an independent recovery path."],
        layout: "hub",
        nodes: [
          { label: "APPLICATION", heading: "Service address / VIP", body: ["Traffic reaches the current read/write role."], tone: "muted" },
          { label: "DATA PLANE", heading: "Primary and readable standbys", body: ["Physical WAL streams and logical publication/subscription serve different replication needs."], tone: "accent" },
          { label: "CONTROL PLANE", heading: "Halo Shield", body: ["clustermgr on each node · etcd quorum · health · role lifecycle · fencing."], tone: "dark" },
          { label: "RECOVERY PLANE", heading: "RMAN2 and WAL archive", body: ["Backup, validation, restore, PITR, or standby preparation."], tone: "accent" },
        ],
        caption: ["Halo Shield, a separate keepalived reference pattern, replication, and RMAN2 serve different purposes and are not interchangeable layers."],
      },
      {
        type: "comparison",
        anchor: "replication",
        heading: "Choose the replication path by purpose",
        columns: ["Approach", "Appropriate use", "Important boundary"],
        rows: [
          ["Physical streaming", "Close standby copies, readable replicas, and failover topologies", "Commit policy and reachability determine latency and data exposure"],
          ["Logical publication/subscription", "Selective data movement", "Not a complete substitute for physical HA or backup"],
          ["Cascaded streaming", "Extend a topology through an intermediate standby", "Each link adds another lag and operating point"],
          ["Replication slots", "Retain required WAL for a consumer", "Delayed consumers can increase retained storage and need monitoring"],
        ],
      },
      {
        type: "callout",
        label: "DURABILITY CHOICE",
        heading: "Synchronous and asynchronous modes make different trade-offs",
        body: ["Default asynchronous replication can lose commits that have not reached a standby if the primary fails. Stronger synchronous waits reduce that window but can add latency or affect write availability when required standbys cannot respond."],
      },
      {
        type: "diagram",
        anchor: "grouped-replication",
        heading: "One primary, multiple replication purposes",
        intro: ["Grouped replication defines a main group and up to four additional groups, each with its own synchronous level. An additional group cannot be stronger than the main group."],
        layout: "cluster",
        nodes: [
          { label: "PRIMARY", heading: "Commit origin", body: ["Writes generate WAL for every configured replication path."], tone: "dark" },
          { label: "MAIN GROUP", heading: "Local availability", body: ["Synchronous and potential synchronous members can be observed per group."], tone: "accent" },
          { label: "ADDITIONAL GROUPS", heading: "Remote recovery roles", body: ["Up to four groups can use independent, no-stronger commit levels."], tone: "default" },
        ],
        caption: ["Documented synchronous strength runs remote_apply → on → remote_write → local/off. RPO 0 is a topology objective only while the required synchronously applied replica is reachable; it is not a universal SLA."],
      },
      {
        type: "accordion",
        anchor: "shield",
        heading: "Halo Shield manages the database role lifecycle",
        items: [
          { heading: "Reference architecture", summary: "Database nodes plus etcd", details: ["The manual illustrates one primary, two replicas, clustermgr on each database node, and a VIP that moves with the primary role. That database-node layout is a reference topology. Separately, the documented etcd quorum requires at least three members and an odd member count for leader election."] },
          { heading: "Consensus and fencing", summary: "Avoid dual primary roles", details: ["etcd maintains role and leader-lock state. A node that cannot renew the leader lock can stop its database, and minority-side availability is sacrificed to prevent split brain. Watchdog can provide an additional fencing layer."] },
          { heading: "Watchdog policy", summary: "off · automatic · required", details: ["Watchdog can restart a node if clustermgr stops making progress. In automatic mode, Shield can continue with a warning when no watchdog device is available; required mode rejects clustermgr startup without the device. The manual describes both software and hardware watchdog paths."] },
          { heading: "Automatic and manual transitions", summary: "Failure and maintenance paths", details: ["Shield supports automatic failover when detection conditions are met, operator-directed failover, and planned switchover. A planned switchover can cause a brief interruption; the site does not claim zero downtime."] },
          { heading: "Maintenance controls", summary: "Operate a protected cluster", details: ["Operators can pause and resume automatic failover, update dynamic DCS configuration, reinitialize a replica, restart or reload selected members, and coordinate rolling maintenance."] },
          { heading: "Operational evidence", summary: "See what changed", details: ["Status and lag, tree topology, transition history, current connection information, component logs, etcd health, and REST responses for primary, replica, cluster, and metrics support investigation."] },
          { heading: "Alternative keepalived pattern", summary: "Separate two-node design", details: ["The manual also documents a two-node streaming-replication pattern with keepalived and a VIP. It is distinct from Shield and should not be assumed to share the same quorum or fencing behavior."] },
        ],
      },
      {
        type: "accordion",
        anchor: "backup-recovery",
        heading: "Recover at the right level",
        items: [
          { heading: "Protection taxonomy", summary: "Full/incremental · logical/physical · hot/cold", details: ["A complete plan can include data, objects, users, privileges, and relevant environment information. Hot backup lets the database continue to serve reads and writes; cold backup requires shutdown."] },
          { heading: "Logical backup and restore", summary: "pg_dump · pg_dumpall · pg_restore", details: ["Coverage can be a database, schema, or table, or cluster-wide databases and global objects such as roles and tablespaces. Plain and archive formats support different workflows. The documented compatibility-object scope includes packages, type bodies, DBLINK, and synonyms with selective tool behavior. Logical methods are useful across versions and platforms but can be slower at scale and do not provide PITR."] },
          { heading: "RMAN2 physical recovery", summary: "FULL · DELTA · PAGE · PTRACK", details: ["RMAN2 documents full and incremental modes, including page-level change tracking through PTRACK, plus WAL streaming, zlib or pglz compression, parallel backup/restore/verification, integrity validation, and skipping never-written blocks. Physical backup requires the database to run in archive mode."] },
          { heading: "Point-in-time targets", summary: "Time · LSN · transaction · restore point · timeline", details: ["Recovery can stop at a documented point rather than only at the end of available WAL. The archive and backup chain must make that target reachable."] },
          { heading: "Restore, validate, and catch up", summary: "New-directory workflows", details: ["A restore can target a new directory for non-disruptive validation or standby preparation. FULL, DELTA, and PTRACK modes can support replica catch-up; PAGE mode is not documented for that catch-up path."] },
          { heading: "Lifecycle management", summary: "Catalogs, retention, and WAL handling", details: ["Backup catalogs, history, retention and TTL policies, WAL archive push/fetch/verification, named recovery targets, and backup validation support an auditable recovery program."] },
        ],
      },
      {
        type: "checklist",
        anchor: "recovery-validation",
        heading: "Validate the failure modes that matter",
        items: [
          "Commit latency and data exposure at each synchronous level",
          "Node, network, quorum, and service-address failures",
          "Replica lag and freshness of reads served from standbys",
          "WAL retention while consumers are delayed",
          "Planned switchover, unexpected failover, and former-primary rejoin",
          "Backup validation and timed restore or PITR rehearsals",
          "Monitoring and decision ownership during degraded operation",
        ],
        outro: ["Halo provides the mechanisms. The deployment must establish its own topology, commit policy, recovery sequence, and measured RPO/RTO."],
      },
      {
        type: "cta",
        heading: "Make recovery objectives testable.",
        actions: [{ label: "Plan an availability PoC", href: "/request-poc/?source=availability", kind: "primary" }],
      },
    ],
    withheldModules: [],
  },
  {
    id: "P24",
    status: "active",
    name: "Distributed data",
    path: "/product/distributed/",
    canonicalPath: "/product/distributed/",
    seo: {
      title: "Distributed Data | Halo Database",
      description: "Understand Halo DLB read scaling, TWR write forwarding, HSM shared storage, and HDS data sharding with explicit boundaries.",
      canonicalPath: "/product/distributed/",
      robots: "index, follow",
    },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Platform", href: "/product/" }, { label: "Distributed Data" }],
    localNavigation: [
      { label: "Capability comparison", anchor: "distributed-comparison" },
      { label: "DLB", anchor: "dlb" },
      { label: "TWR", anchor: "twr" },
      { label: "HSM", anchor: "hsm" },
      { label: "HDS", anchor: "hds" },
      { label: "Production boundary", anchor: "distributed-boundary" },
    ],
    hero: {
      eyebrow: "DISTRIBUTED DATA",
      h1: "Distribute reads, writes, and data with explicit architecture choices.",
      lead: "Halo documents separate mechanisms for read scaling, write forwarding, distributed shared storage, and sharded data placement. Each addresses a different constraint; none is presented as a universal distributed-database mode.",
      actions: [
        { label: "Review a distributed PoC", href: "/request-poc/?source=distributed", kind: "primary" },
        { label: "Explore core architecture", href: "/product/architecture/", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "comparison",
        anchor: "distributed-comparison",
        heading: "Four capabilities, four different jobs",
        columns: ["Capability", "Primary role", "Key boundary"],
        rows: [
          ["Halo DLB", "Read/write separation and read-pool expansion", "An ordinary DLB read-only node rejects writes"],
          ["TWR", "Database-aware write redirection from a read-only connection", "Requires an established primary/standby topology"],
          ["HSM", "Distributed shared storage managed outside the database process", "Reference topology and optional RDMA require deployment validation"],
          ["HDS", "Partitioned data placement behind one logical database", "The manual does not define every production concern around worker HA, resharding, or cross-shard transactions"],
        ],
      },
      {
        type: "diagram",
        anchor: "dlb",
        heading: "Halo DLB scales reads inside the database path",
        intro: ["DLB is implemented in the database kernel rather than as a separate SQL proxy. A read/write node accepts changes, streaming replication supplies read-only replicas, and the read pool distributes query work."],
        layout: "hub",
        nodes: [
          { label: "APPLICATION", heading: "DLB endpoint", body: ["The application reaches Halo through the configured database path."], tone: "muted" },
          { label: "RW", heading: "Read/write node", body: ["Changes execute here and feed streaming replication."], tone: "dark" },
          { label: "RO POOL", heading: "Read-only replicas", body: ["New RO nodes can enlarge the read pool and join the documented design automatically."], tone: "accent" },
          { label: "INTERNAL CHANNEL", heading: "dlb_fdw", body: ["Provides the node connection channel; scheduling remains in the kernel."], tone: "default" },
        ],
        caption: ["Ordinary DLB read-only nodes do not forward writes. TWR provides that separate behavior. Oracle-mode DLB depends on aux_oracle; the native mode does not."],
      },
      {
        type: "diagram",
        anchor: "twr",
        heading: "TWR keeps reads local and redirects writes",
        intro: ["TWR is embedded in the Halo kernel. It identifies operations that require a write, forwards them from an RO node to the RW node, and returns the result."],
        layout: "flow",
        nodes: [
          { label: "UNIFIED CONNECTION", heading: "Application reaches RO", body: ["The connection object can remain the read-only endpoint."], tone: "muted" },
          { label: "DATABASE-AWARE ROUTING", heading: "Classify the work", body: ["Statement · transaction · database object semantics."], tone: "accent" },
          { label: "READ", heading: "Execute locally", body: ["Read work stays on the RO node."], tone: "default" },
          { label: "WRITE", heading: "Forward to RW", body: ["The result returns through the original connection."], tone: "dark" },
        ],
        caption: ["TWR documents statement-level and transaction-block routing and can sit behind SLB, LVS, or F5. These are integration options, not latency guarantees."],
      },
      {
        type: "comparison",
        heading: "TWR and an external proxy are different architectures",
        columns: ["External proxy pattern", "Halo TWR"],
        rows: [
          ["Routing happens outside the database", "Routing is embedded in the Halo kernel"],
          ["Decisions use proxy-visible traffic", "Halo can use statement, object, and transaction state"],
          ["Applications or proxy rules maintain read/write separation", "A read-only connection can forward detected writes"],
          ["Proxy is a separate operating component", "TWR participates in the database topology"],
        ],
      },
      {
        type: "diagram",
        anchor: "hsm",
        heading: "HSM separates database access from shared-storage management",
        intro: ["HSM/hsmd documents a distributed storage architecture with metadata masters, data nodes, client SDKs and libraries, and etcd coordination."],
        layout: "hub",
        nodes: [
          { label: "HALO", heading: "Database instance", body: ["Accesses storage through the HSM client layer and SDK."], tone: "muted" },
          { label: "METADATA", heading: "Two hsmmaster nodes", body: ["The documented 1.0.16 deployment uses two master nodes with etcd coordination."], tone: "dark" },
          { label: "STORAGE", heading: "Three data nodes", body: ["The documented deployment assigns three mounted disks to each data node, with disk-group and filesystem operations."], tone: "accent" },
          { label: "OPERATIONS", heading: "Rebalance and task visibility", body: ["The management client covers node lifecycle, rebalance, tasks, and detailed storage state."], tone: "default" },
        ],
        caption: ["For Halo 1.0.16, the manual states a deployment prerequisite of two hsmmaster nodes and three data nodes with three mounted disks per data node; optional RDMA remains deployment-specific. Confirm later-build requirements rather than inferring active-active/RAC behavior, encryption, or a storage-durability policy."],
      },
      {
        type: "diagram",
        anchor: "hds",
        heading: "HDS places partitioned data across nodes",
        intro: ["Applications connect through a worker that presents one logical database. Partitioned foreign tables and shard_fdw map ranges to independent Halo data nodes."],
        layout: "flow",
        nodes: [
          { label: "APPLICATION", heading: "Standard JDBC", body: ["One logical database connection."], tone: "muted" },
          { label: "WORKER", heading: "SQL and partition routing", body: ["A partitioned parent table represents the logical data set."], tone: "accent" },
          { label: "SHARD CHANNEL", heading: "shard_fdw", body: ["Predicate pushdown and partition pruning reduce irrelevant remote work."], tone: "dark" },
          { label: "DATA NODES", heading: "Independent Halo instances", body: ["Each node stores the mapped subset through matching base tables."], tone: "accent" },
        ],
        caption: ["The manual demonstrates date/range placement and automatic routing. It does not document a universal worker-HA design, online resharding guarantee, or cross-shard transaction contract."],
      },
      {
        type: "checklist",
        anchor: "distributed-boundary",
        heading: "Confirm the production boundary",
        items: [
          "Read freshness and replication lag for DLB",
          "Statement, transaction, and object behavior through TWR",
          "Load-balancer and failure-routing behavior",
          "HSM node count, storage protection, network path, and RDMA availability",
          "HDS worker availability and recovery",
          "Shard-key and partitioning design",
          "Expansion or resharding procedure",
          "Cross-shard transaction requirements",
        ],
        outro: ["Do not substitute linear-scaling, millisecond-routing, zero-change, or single-point-elimination claims for an architecture review."],
      },
      {
        type: "cta",
        heading: "Validate the component and topology together.",
        actions: [{ label: "Prepare a distributed-data PoC", href: "/request-poc/?source=distributed-final", kind: "primary" }],
      },
    ],
    withheldModules: [],
  },
  {
    id: "P06",
    status: "active",
    name: "Operations and observability",
    path: "/product/operations/",
    canonicalPath: "/product/operations/",
    seo: {
      title: "Operations & Observability | Halo Database",
      description: "Explore Halo platform coverage, tuning surfaces, resource controls, HWR diagnostics, system visibility, and DBA tooling.",
      canonicalPath: "/product/operations/",
      robots: "index, follow",
    },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Platform", href: "/product/" }, { label: "Operations & Observability" }],
    localNavigation: [
      { label: "Deployment fit", anchor: "deployment-fit" },
      { label: "Control surfaces", anchor: "control-surfaces" },
      { label: "Resource guardrails", anchor: "resource-guardrails" },
      { label: "System visibility", anchor: "system-visibility" },
      { label: "HWR", anchor: "hwr" },
      { label: "Diagnostics and tooling", anchor: "diagnostics-tooling" },
    ],
    hero: {
      eyebrow: "OPERATIONS & OBSERVABILITY",
      h1: "Operate Halo with familiar controls and visible evidence.",
      lead: "Halo exposes settings, catalogs, statistics, reports, resource controls, and administration tools for deployment fit, workload control, historical diagnosis, and day-to-day inspection.",
      actions: [
        { label: "Open the operations checklist", href: "/resources/evaluation-checklist/#operations", kind: "primary" },
        { label: "Explore recovery", href: "/product/availability-recovery/", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "accordion",
        anchor: "deployment-fit",
        heading: "Fit the documented deployment environment",
        intro: ["The manual lists a broad platform range. Treat it as documented coverage; confirm exact versions, packages, and current support status for the intended release."],
        items: [
          { heading: "Processor families", summary: "x86 · ARM · MIPS · Alpha", details: ["Documented x86 families include Intel, AMD, Zhaoxin, and Hygon; ARM includes Kunpeng and Phytium; MIPS includes Loongson; Alpha includes Sunway."] },
          { heading: "Operating-system families", summary: "Linux and FreeBSD", details: ["Kylin, NeoKylin, UnionTech, openEuler, Ubuntu, Red Hat Enterprise Linux, CentOS, and FreeBSD are listed in the installation material."] },
          { heading: "Installer workflow", summary: "Automated preparation", details: ["The installer detects the operating system and covers dependency handling, service-user setup, cluster initialization, core configuration, archive setup, licensing, service startup, compatibility-mode databases, and HugePages handling."] },
          { heading: "Character sets", summary: "UTF-8 and GB18030", details: ["UTF-8 is the documented default. The manual states support for GB18030-2022 Level 3. GBK is not promoted because its status is not stated with the same clarity."] },
        ],
      },
      {
        type: "accordion",
        anchor: "control-surfaces",
        heading: "Tune through defined operating concerns",
        items: [
          { heading: "Connectivity and authentication", details: ["Network listeners, client access, authentication rules, connection protection, and session behavior define how workloads enter the database."] },
          { heading: "Memory, I/O, and processes", details: ["Memory allocation, background processes, parallel work, disk cost assumptions, and I/O behavior adapt the engine to the host and workload."] },
          { heading: "WAL, archive, and durability", details: ["WAL generation, checkpoints, commit behavior, archive handling, and pglz or lz4 compression choices balance throughput, recoverability, and storage."] },
          { heading: "Query optimization", details: ["Planner switches, cost assumptions, statistics, statement behavior, and parallel-query controls influence plan selection. They are tuning inputs, not universal presets."] },
          { heading: "Autovacuum and maintenance", details: ["Automatic cleanup and analysis protect table health, visibility information, and planner statistics over time."] },
        ],
      },
      {
        type: "cards",
        anchor: "resource-guardrails",
        heading: "Apply focused resource guardrails",
        items: [
          { heading: "Process-level CPU limit", body: ["pg_pcpu_limit constrains selected database-process CPU use by suspending and resuming processes. It is not a workload resource-group or queueing framework."] },
          { heading: "Per-role connection limits", body: ["Connection ceilings can keep one database identity from consuming all session capacity."] },
          { heading: "Idle-session timeout", body: ["Inactive sessions can be closed after a defined interval, releasing abandoned connections and related session resources."] },
        ],
      },
      {
        type: "facts",
        anchor: "system-visibility",
        heading: "Catalogs and views expose current state",
        items: [
          { value: "64", label: "base catalogs", body: "Database objects, security, optimizer statistics, text search, federation, and replication metadata." },
          { value: "11", label: "Halo catalogs", body: "Compatibility objects, query mapping, and model/runtime registration." },
          { value: "64", label: "system views", body: "Activity, I/O, WAL, replication, SSL, progress, and object statistics." },
          { value: "139", label: "documented system objects", body: "Presented by operational domain, not as a manual-sized list." },
        ],
      },
      {
        type: "accordion",
        heading: "Operational visibility by domain",
        items: [
          { heading: "Sessions, activity, and locks", details: ["Current queries, backend activity, locks, cursors, prepared statements, two-phase work, role state, and row-lock inspection support live investigation."] },
          { heading: "I/O, memory, and storage", details: ["Shared buffers, backend memory, I/O, background writing, checkpoints, free-space maps, tuple and index bloat, relation sizes, and low-level pages support progressively deeper diagnosis."] },
          { heading: "WAL, archive, and replication", details: ["Archive, WAL, sender/receiver, slots, origins, subscriptions, errors, synchronization state, lag, and recovery prefetch expose continuity health."] },
          { heading: "Maintenance progress", details: ["Progress is available for analyze, base backup, cluster or VACUUM FULL, copy, index creation or reindexing, and vacuum operations."] },
          { heading: "Configuration and connection security", details: ["Settings, configuration-file parsing, HBA and ident checks, SSL state, certificate details, extensions, and runtime versions support configuration review."] },
        ],
      },
      {
        type: "diagram",
        anchor: "hwr",
        heading: "HWR moves from a live symptom to a historical interval",
        intro: ["HWR collects scheduled database snapshots and produces HTML reports across a selected interval. It can collect sequentially from multiple databases and servers."],
        layout: "flow",
        nodes: [
          { label: "COLLECT", heading: "Scheduled snapshots", body: ["Activity, workload, I/O, WAL, function, and object statistics."], tone: "muted" },
          { label: "RETAIN", heading: "Historical samples", body: ["Configurable retention and sample metadata."], tone: "accent" },
          { label: "SELECT", heading: "Interval or baseline", body: ["Sample IDs · time range · baseline · latest pair."], tone: "dark" },
          { label: "REPORT", heading: "HTML evidence", body: ["Top-N activity, resource behavior, and optional growth views."], tone: "accent" },
        ],
        caption: ["A report needs at least two samples. HWR depends on PL/pgSQL, dblink, scheduled cron work, and pg_stat_statements; sampling resets pg_stat_statements, so timing should be coordinated with other monitoring consumers."],
      },
      {
        type: "accordion",
        anchor: "diagnostics-tooling",
        heading: "Diagnostics, execution reuse, and DBA tooling",
        items: [
          { heading: "Workload and plan diagnostics", details: ["pg_stat_statements aggregates planning, execution, row, block, I/O, and WAL metrics. auto_explain can record plans for slow statements. pgstattuple, amcheck, pg_visibility, pg_buffercache, pageinspect, and related modules cover integrity, bloat, cache, and storage evidence with documented cost and consistency limits."] },
          { heading: "Statement Sharing", details: ["none, normal, and exact modes control reuse of statement processing to reduce repeated parse and compile work. The manual’s single-environment benchmark is not republished as a general result."] },
          { heading: "DBeaver", details: ["The cross-platform DBeaver client can browse databases, schemas, tables, views, columns, constraints, and indexes; view data; use the SQL workspace; and manage transaction behavior. Bundled no-install packaging remains release-dependent and is not promised here."] },
          { heading: "Operational safeguards", details: ["Some inspection functions are privileged, can scan large relations, or do not provide a perfectly consistent snapshot. Diagnostic depth should be matched to impact and access policy."] },
        ],
      },
      {
        type: "cta",
        heading: "Make the operating model part of the evaluation.",
        actions: [{ label: "Build an operations PoC", href: "/request-poc/?source=operations", kind: "primary" }],
      },
    ],
    withheldModules: [],
  },
  {
    id: "P25",
    status: "active",
    name: "Data platform and extensions",
    path: "/product/data-platform/",
    canonicalPath: "/product/data-platform/",
    seo: {
      title: "Data Platform & Extensions | Halo Database",
      description: "Explore Halo extensions, data types, search, federation, security, events, diagnostics, and the documented MRT registry boundary.",
      canonicalPath: "/product/data-platform/",
      robots: "index, follow",
    },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Platform", href: "/product/" }, { label: "Data & Extensions" }],
    localNavigation: [
      { label: "Extension catalog", anchor: "extension-catalog" },
      { label: "All modules", anchor: "all-modules" },
      { label: "Federation", anchor: "federation" },
      { label: "Halo catalogs", anchor: "halo-catalogs" },
      { label: "MRT", anchor: "mrt" },
      { label: "Evaluation boundary", anchor: "extension-boundary" },
    ],
    hero: {
      eyebrow: "DATA PLATFORM & EXTENSIONS",
      h1: "Extend the database where the documented capability fits.",
      lead: "Halo combines a broad SQL object model with optional modules for diagnostics, indexing, text processing, federation, security, data types, events, and sampling. Its catalogs also document a modest in-database model/runtime foundation.",
      actions: [
        { label: "Validate extension requirements", href: "/request-poc/?source=data-platform", kind: "primary" },
        { label: "Explore core architecture", href: "/product/architecture/", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "facts",
        anchor: "extension-catalog",
        heading: "Optional modules expand a stable core",
        intro: ["The manual documents 45 extensions. They are organized by purpose so visitors can discover capability without navigating function signatures or setup procedures."],
        items: [
          { value: "12", label: "administration and diagnostics", body: "Integrity, plans, cache, storage, workload, lock, and TLS inspection." },
          { value: "9", label: "indexing and search", body: "Alternative opclasses, case handling, dictionaries, fuzzy and trigram search, accents." },
          { value: "12", label: "types and transformations", body: "Multidimensional, hierarchical, semi-structured, identifier, large-object, pivot, UUID, and XML utilities." },
          { value: "12", label: "integration, security, and events", body: "Foreign access, hashing/crypto, SELinux labels, notifications, decoding hooks, and sampling." },
        ],
      },
      {
        type: "accordion",
        anchor: "all-modules",
        heading: "Browse all documented modules by purpose",
        items: [
          { heading: "Administration, integrity, and diagnostics", summary: "12 modules", details: ["Server administration, index integrity, automatic plan logging, page/cache/free-space inspection, prewarming, row locks, workload statistics, tuple/index bloat, visibility, and TLS connection details."], tags: ["adminpack", "amcheck", "auto_explain", "pageinspect", "pg_buffercache", "pg_freespacemap", "pg_prewarm", "pgrowlocks", "pg_stat_statements", "pgstattuple", "pg_visibility", "sslinfo"] },
          { heading: "Indexing, search, and text processing", summary: "9 modules", details: ["Bloom supplies compact, lossy equality signatures that can return false-positive candidates for recheck. B-tree-equivalent GIN/GiST operator classes, locale-dependent case-insensitive text, text dictionaries, fuzzy algorithms, trigram similarity, and accent normalization cover different search patterns rather than one interchangeable index family."], tags: ["bloom", "btree_gin", "btree_gist", "citext", "dict_int", "dict_xsyn", "fuzzystrmatch", "pg_trgm", "unaccent"] },
          { heading: "Data types and transformations", summary: "12 modules", details: ["Capabilities include cubes with a documented 100-dimension limit, spherical—not GIS—distance utilities, single-value text key/value data, non-null integer-array operations, publishing identifiers whose prefix data may need updating, large-object references with separate orphan handling, hierarchies, seven-significant-digit uncertainty intervals, pivot/hierarchy functions, UUID variants, and XML/XPath with build-dependent XSLT support. intagg is deprecated."], tags: ["cube", "earthdistance", "hstore", "intagg", "intarray", "isn", "lo", "ltree", "seg", "tablefunc", "uuid-ossp", "xml2"] },
          { heading: "External and federated access", summary: "3 modules", details: ["Session-level database links, server-file foreign tables, and standards-oriented PostgreSQL-compatible foreign tables."], tags: ["dblink", "file_fdw", "postgres_fdw"] },
          { heading: "Security and security labeling", summary: "4 modules", details: ["Authentication delay can slow brute-force attempts but is not denial-of-service protection. Password-policy checks, hashing/HMAC/password hashing/PGP/randomness, and SELinux-integrated mandatory access checks for supported operations each have distinct boundaries."], tags: ["auth_delay", "passwordcheck", "pgcrypto", "sepgsql"] },
          { heading: "Events, decoding, and sampling", summary: "5 modules", details: ["Trigger examples, row-change notification, a logical-decoding development example, and row- or time-limited sampling are documented. The sampling methods do not promise a random or repeatable sample, and the examples do not become production CDC services by name alone."], tags: ["spi", "tcn", "test_decoding", "tsm_system_rows", "tsm_system_time"] },
        ],
      },
      {
        type: "callout",
        label: "MODULE BOUNDARIES",
        heading: "An extension name is not a blanket guarantee",
        body: ["intagg is deprecated; spi and test_decoding are examples rather than enterprise services; passwordcheck has explicit high-security limitations; sepgsql does not cover every DDL/DCL or row-level case; and raw pgcrypto encryption is discouraged. These boundaries remain part of the product explanation."],
      },
      {
        type: "diagram",
        anchor: "federation",
        heading: "Connect data without turning the page into a tutorial",
        intro: ["Halo’s extension set includes database links, file foreign tables, and PostgreSQL-compatible foreign servers. Each connector has its own transaction, security, and pushdown behavior."],
        layout: "hub",
        nodes: [
          { label: "HALO", heading: "Query and object model", body: ["Foreign tables and remote relationships participate in local planning."], tone: "muted" },
          { label: "POSTGRES_FDW", heading: "Standards-oriented federation", body: ["Connection reuse, schema import, safe filter/projection/join pushdown, local transaction mapping, and remote statistics. Remote prepared 2PC is not supported."], tone: "accent" },
          { label: "DBLINK", heading: "Session-level remote access", body: ["Named connections, queries, commands, cursors, asynchronous results, notifications, and inspection. postgres_fdw is the preferred higher-level path where it fits."], tone: "dark" },
          { label: "FILE_FDW", heading: "Server-file foreign tables", body: ["COPY-readable files or controlled program output can become queryable tables; privileged file/program access requires careful security handling."], tone: "default" },
        ],
        caption: ["Do not generalize remote ACID, pushdown, or performance beyond each connector’s documented behavior. postgres_fdw does not prepare a remote transaction for two-phase commit."],
      },
      {
        type: "accordion",
        heading: "Data, search, analytics, and security capabilities",
        items: [
          { heading: "Text and similarity", details: ["Integer and synonym dictionaries, fuzzystrmatch algorithms, trigram similarity and indexed LIKE/regex, accent-insensitive text search, and case-insensitive citext support different search needs and language boundaries."] },
          { heading: "Specialized data", details: ["cube, hstore, intarray, ltree, seg, ISN identifiers, large-object references, UUID variants, XML/XPath, spherical-distance utilities, and table pivot/hierarchy functions extend the data model without implying a full GIS or analytics platform."] },
          { heading: "Events and change surfaces", details: ["LISTEN/NOTIFY and tcn row-change notifications expose event primitives. test_decoding is a development example, not a production CDC connector or delivery guarantee."] },
          { heading: "Cryptographic functions", details: ["pgcrypto provides digest and HMAC functions, salted password hashing, PGP symmetric/public-key operations, secure random bytes, and UUID generation. It does not establish encryption at rest or end-to-end protection, and trusted SSL/client-server handling remains necessary."] },
          { heading: "Security controls", details: ["Roles, privileges, row-level policies, security labels, optional authentication delay, and optional SELinux MAC for supported objects complement each other. None should be described as a complete security posture by itself."] },
        ],
      },
      {
        type: "accordion",
        anchor: "halo-catalogs",
        heading: "Eleven Halo catalogs extend database introspection",
        items: [
          { heading: "Compatibility object registries", details: ["Synonyms, registered directories, database links, recycle-bin objects, packages, type bodies, session/package variables, and view definitions are exposed through Halo-specific metadata."], tags: ["pg_synonym", "pg_directory", "pg_dblink", "pg_dbarecyclebin", "pg_package", "pg_typebody", "pg_variable", "pg_viewdef"] },
          { heading: "Runtime and query registries", details: ["Model definitions, runtime handlers, and Oracle-style SQL query mapping are represented in dedicated catalogs."], tags: ["pg_model", "pg_mrt", "pg_querymap"] },
        ],
      },
      {
        type: "prose",
        anchor: "mrt",
        heading: "MRT at its documented scope",
        paragraphs: [
          { text: "The manual identifies an in-database model/runtime mechanism. pg_model holds model-definition metadata such as name, type, provider, algorithm, options, and access information; pg_mrt maps runtime names to handlers. The inspected manual snapshot records a GGUF-related runtime handler." },
          { text: "This establishes a catalog and handler foundation to evaluate. It does not establish a supported-model matrix, public inference API, sizing guidance, hardware acceleration, or packaging availability. DataOS has no basis in the canonical Markdown and is not published as a Halo capability." },
        ],
      },
      {
        type: "checklist",
        anchor: "extension-boundary",
        heading: "Evaluate the module, not just the name",
        items: [
          "Availability in the target Halo build",
          "Module version and upgrade path",
          "Operating-system or database dependencies",
          "Privilege and security implications",
          "Remote transaction and pushdown behavior",
          "Observation overhead for diagnostic modules",
          "Model and runtime support required by the workload",
        ],
        outro: ["The right claim is the capability documented for a selected build—not an assumption that every module is installed, enabled, or suitable for every workload."],
      },
      {
        type: "cta",
        heading: "Bring extension and MRT requirements into the PoC scope.",
        actions: [{ label: "Prepare a technical evaluation", href: "/request-poc/?source=data-platform-final", kind: "primary" }],
      },
    ],
    withheldModules: [],
  },
] as const satisfies readonly ActiveSitePage[];
