import type { ActiveSitePage } from "./site-content";

export const manualJourneyPages = [
  {
    id: "P01",
    status: "active",
    name: "Home",
    path: "/",
    canonicalPath: "/",
    seo: {
      title: "Halo Database | One Platform for Heterogeneous Workloads",
      description: "Explore Halo multimode compatibility, versioned behavior testing, recovery, workload diagnostics, and SQL policy controls.",
      canonicalPath: "/",
      robots: "index, follow",
    },
    breadcrumb: [],
    localNavigation: [],
    hero: {
      eyebrow: "UNIFIED DATABASE PLATFORM",
      h1: "One database platform. Three operating modes.",
      lead: "Halo 1.0.16 supports Oracle, MySQL, and PostgreSQL operating modes within one cluster. Follow a workload from mode selection through behavior-level testing, continuity and recovery, and a decision record.",
      actions: [
        { label: "See how Halo works", href: "/product/", kind: "primary" },
        { label: "Evaluate a migration", href: "/oracle-migration-evaluation/", kind: "secondary" },
        { label: "Prepare a PoC", href: "/request-poc/?source=home", kind: "text" },
      ],
    },
    blocks: [
      {
        type: "facts",
        anchor: "platform-signals",
        items: [
          { value: "3", label: "operating modes", body: "Oracle, MySQL, and PostgreSQL modes within one Halo 1.0.16 cluster." },
          { value: "1", label: "versioned target", body: "A shared candidate for workload evaluation—not proof that every application moves unchanged." },
          { value: "4", label: "connected stages", body: "Define the workload, select a mode, test behavior, and record a decision." },
        ],
      },
      {
        type: "cards",
        anchor: "migration-pressure",
        heading: "Make migration risk testable.",
        intro: [
          "A database move becomes difficult where application behavior, operating-mode choice, continuity, and recovery meet. Halo gives each question a visible place in a workload-led evaluation.",
        ],
        items: [
          {
            label: "BEHAVIOR",
            heading: "Test what the application actually uses",
            body: ["Evaluate protocol behavior, types, functions, objects, procedural logic, transactions, errors, drivers, and integrations—not a generic compatibility percentage."],
            actions: [{ label: "Explore compatibility", href: "/product/compatibility/", kind: "text" }],
          },
          {
            label: "MODE CHOICE",
            heading: "Keep the target version and mode explicit",
            body: ["Halo 1.0.16 supports Oracle, MySQL, and PostgreSQL operating modes within one cluster. The exact setup and workload fit still need versioned validation."],
            actions: [{ label: "See the architecture", href: "/product/architecture/", kind: "text" }],
          },
          {
            label: "RECOVERABILITY",
            heading: "Separate continuity from recovery",
            body: ["Replication carries changes along another data path; synchronous or asynchronous behavior and lag must be validated for the proposed configuration. Backup validation, restore, and point-in-time recovery answer a different failure question."],
            actions: [{ label: "Plan continuity", href: "/product/availability-recovery/", kind: "text" }],
          },
        ],
      },
      {
        type: "diagram",
        anchor: "compatibility-engine",
        eyebrow: "MULTIMODE EVALUATION",
        heading: "Follow one workload from mode to evidence",
        intro: ["Three operating modes create a versioned target to test. They do not establish complete product equivalence or prove that an application moves unchanged."],
        layout: "flow",
        nodes: [
          { label: "DEFINE", heading: "Set the workload boundary", body: ["Inventory protocol, SQL, objects, procedural logic, transactions, drivers, tools, recovery objectives, and acceptance criteria."], tone: "muted" },
          { label: "SELECT", heading: "Choose an operating mode", body: ["Select Oracle, MySQL, or PostgreSQL behavior within the Halo 1.0.16 cluster."], tone: "accent" },
          { label: "TEST", heading: "Exercise versioned behavior", body: ["Use representative data and concurrency to test compatibility, continuity, recovery, diagnostics, and operator tasks."], tone: "dark" },
          { label: "DECIDE", heading: "Record fit and decide", body: ["Mark what worked as tested, what needs remediation, and what remains unresolved; then tie the result to agreed criteria."], tone: "accent" },
        ],
        caption: ["A selected mode is a test surface, not a complete-equivalence or unchanged-application promise."],
      },
      {
        type: "cards",
        anchor: "platform-capabilities",
        heading: "Explore the mechanisms behind the decision",
        intro: ["Switch between three documented controls to see the problem each one addresses, how the mechanism works, and what a representative PoC still has to prove."],
        items: [
          { label: "RECOVER", heading: "Replicate for continuity. Recover from a verified point.", body: ["Halo 1.0.16 documents physical and logical replication and logical and physical backup, restore, validation, incremental backup, and point-in-time recovery workflows."], actions: [{ label: "Plan continuity", href: "/product/availability-recovery/", kind: "text" }] },
          { label: "OBSERVE", heading: "Capture the interval. Explain what changed.", body: ["Halo 1.0.16 documents HWR-based snapshot collection and HTML reporting for workload and performance analysis."], actions: [{ label: "Explore HWR", href: "/product/operations/#hwr", kind: "text" }] },
          { label: "CONTROL", heading: "Test an SQL firewall policy before enforcing it.", body: ["The Halo 1.0.16 manual documents an SQL firewall mechanism and related test cases."], actions: [{ label: "Review the evidence", href: "/resources/evidence/", kind: "text" }] },
        ],
      },
      {
        type: "cta",
        heading: "Bring the workload. Build the migration case.",
        body: ["Define the compatibility, workload, recovery, and operating evidence your team needs before committing to the move. Keep each claim, source, limit, test, and decision adjacent."],
        actions: [
          { label: "Prepare a workload PoC", href: "/request-poc/?source=home-final", kind: "primary" },
          { label: "Review claims and limits", href: "/resources/evidence/", kind: "secondary" },
          { label: "Plan a demo", href: "/request-demo/?source=home-final", kind: "text" },
        ],
      },
    ],
    withheldModules: [
      { id: "case-proof", status: "absent", requires: ["A01"] },
      { id: "partner-strip", status: "absent", requires: ["A08", "A06", "A12"] },
    ],
  },
  {
    id: "P07",
    status: "active",
    name: "Proof-of-concept method",
    path: "/evaluation/",
    canonicalPath: "/evaluation/",
    seo: {
      title: "Halo Database Proof-of-Concept Method",
      description: "Define the workload, test Halo against agreed criteria, and leave with a proceed, remediate, or stop decision.",
      canonicalPath: "/evaluation/",
      robots: "index, follow",
    },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Proof of concept" }],
    localNavigation: [],
    hero: {
      eyebrow: "PROOF OF CONCEPT",
      h1: "Turn product capability into a workload decision.",
      lead: "A Halo PoC defines the application, target architecture, and acceptance criteria before testing compatibility, performance, continuity, distributed behavior, and day-to-day operations.",
      actions: [
        { label: "Open the evaluation checklist", href: "/resources/evaluation-checklist/", kind: "primary" },
        { label: "Prepare a PoC", href: "/request-poc/?source=evaluation", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "steps",
        heading: "Five steps to a defensible decision",
        items: [
          { heading: "1. Frame the decision", body: ["Name the application, source product and version, business reason, owners, decision date, and non-negotiable requirements."] },
          { heading: "2. Map the dependency surface", body: ["Inventory objects, procedural logic, drivers, frameworks, integrations, transaction behavior, data profile, workload, and operating dependencies."] },
          { heading: "3. Select the Halo architecture", body: ["Choose the mode, topology, replication and recovery design, distributed components, operating environment, exact build, and optional modules in scope."] },
          { heading: "4. Run representative tests", body: ["Test application behavior, integrations, workload, failover, backup, restore, PITR, diagnostics, and operator tasks under agreed conditions."] },
          { heading: "5. Record the decision", body: ["Mark each material requirement passed as tested, passed with remediation, unsupported in scope, or not tested; assign owners and retest conditions before recommending proceed, remediate, or stop."] },
        ],
      },
      {
        type: "comparison",
        heading: "A demo and a PoC answer different questions",
        columns: ["Demo", "Proof of concept"],
        rows: [
          ["Introduces documented capabilities", "Tests a defined workload"],
          ["Uses prepared product material", "Uses representative application inputs"],
          ["Helps decide whether to investigate", "Helps decide whether to proceed"],
          ["Does not establish application fit", "Produces scoped evidence and exceptions"],
        ],
      },
      {
        type: "cards",
        heading: "Run the lanes that affect the decision",
        items: [
          { heading: "Compatibility", body: ["Application behavior, database objects, procedural logic, drivers, tools, integrations, transactions, and errors."] },
          { heading: "Workload", body: ["Representative query mix, concurrency, batch work, resource use, stability, and agreed performance measures."] },
          { heading: "Continuity", body: ["Replication, failover, reconnect, backup, validation, restore, PITR, and former-primary rejoin."] },
          { heading: "Operations", body: ["Monitoring, HWR, diagnostics, maintenance, resource controls, administration tools, and ownership."] },
          { heading: "Distributed topology", body: ["DLB, TWR, HSM, or HDS routing, failure, consistency, placement, and lifecycle behavior when applicable."] },
        ],
      },
      {
        type: "checklist",
        heading: "What a useful PoC leaves behind",
        items: [
          "Source and target inventory",
          "Requirement-to-test matrix",
          "Reproducible environment record",
          "Observations and retained evidence",
          "Compatibility and exception register",
          "Remediation, ownership, and retest plan",
          "Proceed, remediate, or stop recommendation",
        ],
      },
      {
        type: "callout",
        label: "EVIDENCE DISCIPLINE",
        heading: "Keep source, conditions, and limits attached",
        body: ["A manual statement is not a workload result. A generic benchmark is not an application result. Every conclusion should preserve the build, environment, topology, inputs, measurement, and unresolved boundaries behind it."],
      },
      {
        type: "cta",
        heading: "Define what Halo must prove.",
        actions: [{ label: "Prepare a PoC", href: "/request-poc/?source=evaluation-final", kind: "primary" }],
      },
    ],
    withheldModules: [],
  },
  {
    id: "P08",
    status: "active",
    name: "Resources",
    path: "/resources/",
    canonicalPath: "/resources/",
    seo: {
      title: "Halo Database Resources",
      description: "Find Halo product, migration, architecture, recovery, distributed-data, operations, evidence, and evaluation resources by question.",
      canonicalPath: "/resources/",
      robots: "index, follow",
    },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Resources" }],
    localNavigation: [],
    hero: {
      eyebrow: "RESOURCES",
      h1: "Find the product answer by question—not by manual chapter.",
      lead: "Explore what Halo supports, how migration is evaluated, how continuity is designed, how the platform is operated, and what evidence still needs to be produced.",
      actions: [
        { label: "Start with the platform", href: "/product/", kind: "primary" },
        { label: "Open the evaluation checklist", href: "/resources/evaluation-checklist/", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "cards",
        heading: "Choose a path",
        items: [
          { heading: "Understand the platform", body: ["Start with the openHalo-based core, multimode architecture, and enterprise capability map."], actions: [{ label: "Product overview", href: "/product/", kind: "text" }, { label: "Architecture", href: "/product/architecture/", kind: "text" }] },
          { heading: "Plan compatibility and migration", body: ["Review Oracle, MySQL, and PostgreSQL behavior, then turn application dependencies into a migration assessment."], actions: [{ label: "Compatibility", href: "/product/compatibility/", kind: "text" }, { label: "Oracle migration", href: "/oracle-migration-evaluation/", kind: "text" }] },
          { heading: "Design continuity and distributed data", body: ["Explore replication, recovery, Shield, DLB, TWR, HSM, and HDS with their documented boundaries."], actions: [{ label: "Availability & recovery", href: "/product/availability-recovery/", kind: "text" }, { label: "Distributed data", href: "/product/distributed/", kind: "text" }] },
          { heading: "Operate and extend", body: ["Review tuning surfaces, resource controls, HWR, system visibility, data types, federation, and optional modules."], actions: [{ label: "Operations", href: "/product/operations/", kind: "text" }, { label: "Data & extensions", href: "/product/data-platform/", kind: "text" }] },
          { heading: "Trace claims", body: ["See the source behind material statements, what each establishes, and what still requires validation."], actions: [{ label: "Evidence & validation", href: "/resources/evidence/", kind: "text" }, { label: "Documentation basis", href: "/resources/documentation/", kind: "text" }] },
          { heading: "Prepare an evaluation", body: ["Capture the workload, target architecture, acceptance criteria, and decision owners before requesting a PoC."], actions: [{ label: "Evaluation checklist", href: "/resources/evaluation-checklist/", kind: "text" }, { label: "PoC method", href: "/evaluation/", kind: "text" }] },
        ],
      },
      {
        type: "callout",
        label: "CONTENT BOUNDARY",
        heading: "Product knowledge here; operating instructions in documentation",
        body: ["This website explains capability, architecture, value, and limits. SQL, commands, configuration files, terminal output, screenshots, and step-by-step operating procedures are intentionally not reproduced in the enterprise-site body."],
      },
    ],
    withheldModules: [],
  },
  {
    id: "P09",
    status: "active",
    name: "Documentation basis",
    path: "/resources/documentation/",
    canonicalPath: "/resources/documentation/",
    seo: {
      title: "Halo 1.0.16 Product Documentation Basis",
      description: "See how the Halo 1.0.16 manual is reorganized into enterprise product, migration, architecture, and operations content.",
      canonicalPath: "/resources/documentation/",
      robots: "index, follow",
    },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Resources", href: "/resources/" }, { label: "Documentation basis" }],
    localNavigation: [],
    hero: {
      eyebrow: "DOCUMENTATION BASIS",
      h1: "Product knowledge, reorganized for enterprise evaluation.",
      lead: "This website uses the complete Halo 1.0.16 user-manual Markdown set as its primary product source, then reorganizes that knowledge around customer questions rather than reproducing the manual chapter by chapter.",
      actions: [
        { label: "Review evidence", href: "/resources/evidence/", kind: "primary" },
        { label: "Explore the platform", href: "/product/", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "comparison",
        heading: "What belongs where",
        columns: ["On this website", "In technical documentation"],
        rows: [
          ["Product positioning and capability", "Exact commands and syntax"],
          ["Architecture and topology concepts", "Installation and CLI procedures"],
          ["Compatibility scope and boundaries", "SQL, DDL, DML, and language examples"],
          ["Migration and operational value", "Configuration files and parameter values"],
          ["Evidence limits and evaluation questions", "Terminal output, logs, and troubleshooting steps"],
        ],
      },
      {
        type: "accordion",
        heading: "The source families behind the site",
        items: [
          { heading: "Product and architecture", summary: "Chapters 1–2", details: ["Product origin and release history, instance/cluster architecture, transactions, storage, indexes, partitioning, and database objects."] },
          { heading: "Deployment and tuning", summary: "Chapters 3–6", details: ["Documented processor and operating-system families, installer workflow, initialization, character sets, and configuration surfaces."] },
          { heading: "Compatibility", summary: "Chapters 7–10", details: ["E5, multiple operating modes, and Oracle, MySQL, and native PostgreSQL behavior and boundaries."] },
          { heading: "Backup and availability", summary: "Chapters 11–15", details: ["Protection models, RMAN2, physical/logical/grouped replication, and Halo Shield."] },
          { heading: "Distributed capabilities", summary: "Chapters 16–19", details: ["DLB, TWR, HSM, and HDS architecture and operational boundaries."] },
          { heading: "Operations and tooling", summary: "Chapters 20–22", details: ["Resource controls, HWR, Statement Sharing, and DBeaver."] },
          { heading: "Reference inventories", summary: "Appendices A–G", details: ["SQL object families, RMAN2 scope, system catalogs/views, 45 extensions, structured errors, compatibility additions, and Shield cluster operations. Syntax and commands are excluded from the site body while the capabilities they prove are retained."] },
        ],
      },
      {
        type: "facts",
        heading: "Frozen source snapshot used for this refactor",
        items: [
          { value: "80", label: "Markdown files" },
          { value: "40,934", label: "source lines" },
          { value: "14,502", label: "nonblank non-code lines" },
          { value: "80/80", label: "hash matches", body: "Every file matched the source map at the implementation freeze." },
        ],
      },
      {
        type: "checklist",
        heading: "Before relying on a documented capability",
        items: [
          "Confirm the exact Halo version and build",
          "Confirm the operating mode and optional modules",
          "Separate capability description from configuration example",
          "Preserve stated limitations and prerequisites",
          "Validate the requirement with the intended application and topology",
        ],
      },
      {
        type: "callout",
        label: "VERSION NOTE",
        heading: "Halo 1.0.16 is the factual release baseline",
        body: ["The release history identifies Halo 1.0.16 as the second LTS release, published in June 2024. Current package availability, platform certification, and support scope still require confirmation for a specific deployment."],
      },
    ],
    withheldModules: [],
  },
  {
    id: "P10",
    status: "active",
    name: "Evidence and validation",
    path: "/resources/evidence/",
    canonicalPath: "/resources/evidence/",
    seo: {
      title: "Evidence & Validation | Halo Database",
      description: "See what material Halo statements establish, their manual source, their limits, and what a workload evaluation must validate.",
      canonicalPath: "/resources/evidence/",
      robots: "index, follow",
    },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Resources", href: "/resources/" }, { label: "Evidence & Validation" }],
    localNavigation: [],
    hero: {
      eyebrow: "EVIDENCE & VALIDATION",
      h1: "See what each Halo claim establishes—and what it does not.",
      lead: "Material statements are paired with their manual source, practical meaning, boundary, and workload question.",
      actions: [
        { label: "Open the evaluation checklist", href: "/resources/evaluation-checklist/", kind: "primary" },
        { label: "See the documentation basis", href: "/resources/documentation/", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "evidence",
        heading: "Material product evidence",
        fieldLabels: { statement: "Documented statement", source: "Manual source", limit: "What it does not prove", test: "What to validate" },
        records: [
          { heading: "Product identity and release", statement: "Halo is described as an openHalo-based, general-purpose unified database. Halo 1.0.16 is listed as the second LTS release, published in June 2024.", source: "Chapters 1–2", limit: "This does not confirm current packaging, certification, regional service, or an English legal company identity.", test: "Confirm the exact build, package, platform, and support scope intended for deployment." },
          { heading: "Multimode compatibility", statement: "One instance can run Oracle, MySQL, and PostgreSQL modes concurrently; E5 spans protocol, parsing/semantics, optimization, and execution.", source: "Chapter 7; Chapters 8–10", limit: "This does not establish complete equivalence or unchanged behavior for every application.", test: "Test the data types, functions, objects, procedural behavior, drivers, transactions, and errors the application uses." },
          { heading: "Reported Oracle migration practice", statement: "The manual reports at least 95% lower Oracle-related application code changes in migration practice.", source: "Chapter 1; Oracle overview", limit: "This is not a universal percentage, zero-change promise, hour-scale promise, or performance guarantee.", test: "Measure required changes against a representative dependency inventory and PoC record." },
          { heading: "Continuity and recovery", statement: "The manual documents physical/logical replication and backup; incremental physical modes; validation; and PITR to time, LSN, transaction ID, restore point, or timeline.", source: "Chapters 11–15; Appendix B", limit: "Mechanisms alone do not establish an SLA, RPO, or RTO. Sync and async choices differ.", test: "Exercise the intended topology, failure, reconnect, data state, and operator procedure." },
          { heading: "Distributed data paths", statement: "DLB, TWR, HSM, and HDS address read distribution, write forwarding, shared storage, and sharded placement as distinct components.", source: "Chapters 16–19", limit: "The source does not establish universal active-active behavior, linear scale, online resharding, distributed transactions, or topology-independent durability.", test: "Select the component and topology, then test routing, failure, consistency, placement, lifecycle, and operations." },
          { heading: "Operations and observability", statement: "HWR snapshots and interval reports, 139 catalog/view objects, and 45 extension modules provide documented paths for visibility and diagnostics.", source: "Chapter 21; Appendices C–D", limit: "Counts do not mean every module is installed or enabled by default; HWR has dependencies and collection behavior.", test: "Confirm installed modules, permissions, collection settings, retention, overhead, and workflow." },
          { heading: "Documented platform reach", statement: "The installation material lists multiple x86, ARM, MIPS, and Alpha families and several Linux distributions plus FreeBSD.", source: "Chapter 3", limit: "A manual list is not a current certification or support matrix.", test: "Confirm processor, operating-system version, package, and support status before procurement." },
        ],
      },
      {
        type: "callout",
        label: "NOT PUBLISHED AS PRODUCT FACT",
        heading: "Claims without a sufficient canonical basis",
        body: ["No evidence record is published for DataOS, SQL firewall, universal RPO 0, universal sub-60-second RTO, zero code change, zero performance loss, HSM active-active/RAC equivalence, HDS linear scaling, or a general AI platform beyond the documented MRT/catalog mechanism."],
      },
    ],
    withheldModules: [],
  },
  {
    id: "P11",
    status: "active",
    name: "Evaluation checklist",
    path: "/resources/evaluation-checklist/",
    canonicalPath: "/resources/evaluation-checklist/",
    seo: {
      title: "Halo Database Evaluation Checklist",
      description: "Prepare the application, compatibility surface, data, workload, target architecture, operations, and acceptance record for a Halo PoC.",
      canonicalPath: "/resources/evaluation-checklist/",
      robots: "index, follow",
    },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Resources", href: "/resources/" }, { label: "Evaluation checklist" }],
    localNavigation: [],
    hero: {
      eyebrow: "EVALUATION CHECKLIST",
      h1: "Bring the application, architecture, and decision criteria.",
      lead: "Use this checklist to define a representative Halo evaluation before testing begins.",
      actions: [
        { label: "Prepare a PoC", href: "/request-poc/?source=checklist", kind: "primary" },
        { label: "See the PoC method", href: "/evaluation/", kind: "secondary" },
      ],
    },
    blocks: [
      { type: "checklist", heading: "1. Decision and source estate", items: ["Application, business purpose, and criticality", "Source product, edition, version, and topology", "Business owner, technical owner, and decision date", "Migration, consolidation, or architecture question", "Non-negotiable and stop-early requirements"] },
      { type: "checklist", heading: "2. Compatibility surface", items: ["Required Oracle, MySQL, or PostgreSQL mode", "Types, functions, operators, and query behavior", "Schemas, tables, indexes, partitions, views, and sequences", "Procedures, functions, packages, triggers, and temporary objects", "Transactions, isolation, locking, and error behavior", "DBLINK, foreign-data, and extension dependencies"] },
      { type: "checklist", heading: "3. Application and integration", items: ["Drivers, connection pools, frameworks, and ORM", "Jobs, reporting, administration, and monitoring tools", "Authentication, authorization, and cryptographic requirements", "Upstream, downstream, and external-service dependencies"] },
      { type: "checklist", heading: "4. Data and workload", items: ["Data volume, distribution, growth, and retention", "Representative transactions and query mix", "Concurrency, batch windows, and peak conditions", "Latency, throughput, stability, and resource criteria", "Sensitive-data and secure-transfer constraints"] },
      { type: "checklist", anchor: "target-architecture", heading: "5. Target architecture and continuity", items: ["Processor, operating system, storage, network, and topology", "Replication mode and synchronization level", "Failover, switchover, fencing, and application reconnect", "Backup type, validation, retention, restore, and PITR", "DLB, TWR, HSM, or HDS requirements when applicable"] },
      { type: "checklist", anchor: "operations", heading: "6. Operations and observability", items: ["Installation and configuration ownership", "Monitoring, HWR, and diagnostic evidence", "Resource controls and tuning responsibilities", "Maintenance, upgrade, and recovery procedures", "Required extensions and administration tools"] },
      { type: "checklist", heading: "7. Acceptance and decision record", items: ["Requirement owner and test owner", "Expected result and measurement method", "Evidence to retain", "Passed, remediation, unsupported, or untested status", "Retest conditions", "Proceed, remediate, or stop recommendation"] },
      {
        type: "callout",
        label: "DATA HANDLING",
        heading: "Keep sensitive material out of public inquiry routes",
        body: ["Do not place credentials, production records, customer data, or confidential database content in a public inquiry. Agree on secure transfer and representative test-data handling during qualification."],
      },
      { type: "cta", heading: "Ready to define the evidence plan?", actions: [{ label: "Prepare a PoC", href: "/request-poc/?source=checklist-final", kind: "primary" }] },
    ],
    withheldModules: [],
  },
  {
    id: "P14",
    status: "active",
    name: "About Halo",
    path: "/company/",
    canonicalPath: "/company/",
    seo: {
      title: "About Halo Database",
      description: "Learn how an Oracle migration problem led to Halo’s multimode, openHalo-based database platform.",
      canonicalPath: "/company/",
      robots: "index, follow",
    },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Company" }],
    localNavigation: [],
    hero: {
      eyebrow: "ABOUT HALO",
      h1: "Built from a migration problem. Evolved into a unified database.",
      lead: "Halo’s documented history began in 2012 with the challenge of moving an Oracle application while reducing migration risk and cost. Compatibility remained part of the product architecture as Halo expanded into a multimode enterprise database.",
      actions: [
        { label: "Explore the platform", href: "/product/", kind: "primary" },
        { label: "Plan commercial questions", href: "/contact-sales/?source=company", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "steps",
        heading: "Product provenance",
        items: [
          { heading: "2012 — The starting problem", body: ["The founding team began database work around an Oracle application migration; the first recorded compatibility effort focused on SYSDATE behavior."] },
          { heading: "2021 — First V1 release", body: ["Halo 1.0.13 extended Oracle-oriented procedural compatibility."] },
          { heading: "2022 — First LTS", body: ["Halo 1.0.14 introduced E5, GB18030 support, PL/SQL Package capability, and MySQL protocol and syntax support. Its enterprise-kernel lineage was later released as openHalo."] },
          { heading: "2023 — Halo 1.0.15", body: ["Procedural compatibility and Oracle sequence behavior continued to expand."] },
          { heading: "June 2024 — Second LTS", body: ["Halo 1.0.16 documented concurrent PostgreSQL, MySQL, and Oracle modes and additional distributed components."] },
        ],
      },
      {
        type: "prose",
        heading: "Compatibility is part of the database path",
        paragraphs: [{ text: "E5 spans client protocol, parsing and semantic handling, optimization, and execution. Halo’s compatibility proposition is architectural—but every migration result remains workload-specific." }],
      },
      {
        type: "cards",
        heading: "The documented product direction",
        items: [
          { heading: "Heterogeneous workload compatibility", body: ["Oracle, MySQL, and native PostgreSQL paths in one database platform."] },
          { heading: "Enterprise continuity and recovery", body: ["Replication, backup, PITR, grouped durability, and Shield lifecycle management."] },
          { heading: "Distributed access and placement", body: ["DLB, TWR, HSM, and HDS as distinct architecture patterns."] },
          { heading: "Database operations and visibility", body: ["Tuning surfaces, system metadata, HWR history, diagnostics, and DBA tooling."] },
        ],
      },
      {
        type: "callout",
        label: "COMPANY INFORMATION BOUNDARY",
        heading: "Product provenance is documented; corporate details still need approval",
        body: ["A verified English legal company name, registration details, office locations, team biographies, customer references, partner claims, and regional service scope should be added only after company approval."],
      },
    ],
    withheldModules: [],
  },
  {
    id: "P15",
    status: "active",
    name: "Prepare a proof of concept",
    path: "/request-poc/",
    canonicalPath: "/request-poc/",
    seo: { title: "Prepare a Halo Database PoC", description: "Prepare a workload-specific Halo proof-of-concept plan.", canonicalPath: "/request-poc/", robots: "noindex, follow" },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Prepare a PoC" }],
    localNavigation: [],
    hero: { eyebrow: "PREPARE A PROOF OF CONCEPT", h1: "Define what Halo needs to prove.", lead: "Use this route to prepare a PoC scope when a specific application, representative workload, target architecture, and decision criteria can be identified. No submission channel is implied.", actions: [{ label: "Open the checklist", href: "/resources/evaluation-checklist/", kind: "primary" }, { label: "See the PoC method", href: "/evaluation/", kind: "secondary" }] },
    blocks: [
      { type: "checklist", heading: "Use a PoC when", items: ["A source product and application are known", "Material compatibility or integration questions can be listed", "Representative workload and architecture inputs are available", "Continuity, recovery, or operating criteria affect the decision", "Business and technical owners can review the result"] },
      { type: "checklist", heading: "Prepare before qualification", items: ["Organization and country or region", "Source product, version, and deployment model", "Application purpose and criticality", "Required mode and database dependencies", "Representative data and workload profile", "Target architecture and continuity requirements", "Acceptance criteria, owners, and decision date"] },
      { type: "steps", heading: "What a scoped engagement should establish", items: [{ heading: "1. Qualification", body: ["Confirm product, regional, and engagement fit."] }, { heading: "2. Test plan", body: ["Agree requirements, inputs, responsibilities, environment, and evidence format."] }, { heading: "3. Decision record", body: ["Classify outcomes, remediation, ownership, retest conditions, and next decision."] }] },
      { type: "callout", label: "INQUIRY STATUS", heading: "The submission workflow is not active on this site", body: ["No verified contact endpoint, privacy notice, or consent flow has been approved in the current source set. The page therefore provides preparation guidance without a public form, response-time promise, or implied engagement acceptance."] },
    ],
    withheldModules: [{ id: "form-shell", status: "absent", requires: ["A06", "A12"] }],
  },
  {
    id: "P17",
    status: "active",
    name: "Plan a demo",
    path: "/request-demo/",
    canonicalPath: "/request-demo/",
    seo: { title: "Plan a Halo Database Demo", description: "Choose the Halo capabilities to explore in a future product introduction.", canonicalPath: "/request-demo/", robots: "noindex, follow" },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Plan a Demo" }],
    localNavigation: [],
    hero: { eyebrow: "PLAN A DEMO", h1: "Choose the Halo capabilities you want to explore.", lead: "Use this route to plan a future product introduction. A demo can refine technical questions, but it does not validate application compatibility, performance, recovery objectives, or production readiness.", actions: [{ label: "Explore the platform", href: "/product/", kind: "primary" }, { label: "Prepare a PoC instead", href: "/request-poc/?source=demo", kind: "secondary" }] },
    blocks: [
      { type: "cards", heading: "Possible demo topics", items: [{ heading: "Compatibility and E5", body: ["Oracle, MySQL, and native PostgreSQL paths."] }, { heading: "Core architecture", body: ["Transactions, storage, indexing, and partitioning."] }, { heading: "Continuity", body: ["Replication, RMAN2, and Shield."] }, { heading: "Distributed data", body: ["DLB, TWR, HSM, and HDS."] }, { heading: "Operations", body: ["HWR, system visibility, resource controls, and extensions."] }] },
      { type: "comparison", heading: "What a demo can and cannot establish", columns: ["A demo can", "A demo cannot"], rows: [["Orient business and technical stakeholders", "Prove that an application moves unchanged"], ["Identify relevant architecture paths", "Establish representative performance or capacity"], ["Surface questions for evaluation", "Set an RPO, RTO, or SLA"], ["Help decide whether to prepare a PoC", "Estimate migration effort or production readiness"]] },
      { type: "callout", label: "INQUIRY STATUS", heading: "This remains an informational route", body: ["The current source set does not include an approved public scheduling endpoint, privacy notice, or consent flow. No form or response-time promise is published."] },
    ],
    withheldModules: [{ id: "form-shell", status: "absent", requires: ["A06", "A12"] }],
  },
  {
    id: "P16",
    status: "active",
    name: "Commercial planning",
    path: "/contact-sales/",
    canonicalPath: "/contact-sales/",
    seo: { title: "Halo Database Commercial Planning", description: "Prepare commercial, procurement, deployment-scope, or regional-fit questions for Halo Database.", canonicalPath: "/contact-sales/", robots: "noindex, follow" },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Commercial Planning" }],
    localNavigation: [],
    hero: { eyebrow: "COMMERCIAL PLANNING", h1: "Prepare commercial, procurement, and regional-fit questions.", lead: "Use this route to organize licensing, procurement, deployment-scope, or service-availability questions. No public sales channel or response-time promise is available in the approved source set.", actions: [{ label: "Prepare a workload PoC", href: "/request-poc/?source=sales", kind: "primary" }, { label: "Plan a product introduction", href: "/request-demo/?source=sales", kind: "secondary" }] },
    blocks: [
      { type: "checklist", heading: "Prepare the commercial context", items: ["Organization, role, and country or region", "Current database estate", "Products or operating modes of interest", "Intended deployment stage and timing", "Commercial or procurement question", "Stakeholders involved in the decision"] },
      { type: "cards", heading: "Choose the right preparation path", items: [{ heading: "Defined workload", body: ["Use the PoC path to prepare compatibility, performance, recovery, and operating evidence."], actions: [{ label: "Prepare a PoC", href: "/request-poc/?source=sales-card", kind: "text" }] }, { heading: "Product introduction", body: ["Use the demo path to orient stakeholders and refine questions."], actions: [{ label: "Plan a demo", href: "/request-demo/?source=sales-card", kind: "text" }] }, { heading: "Still researching", body: ["Use the platform and resources pages without disclosing confidential material."], actions: [{ label: "Explore the platform", href: "/product/", kind: "text" }] }] },
      { type: "callout", label: "COMMERCIAL BOUNDARY", heading: "No regional or response-time promise is implied", body: ["The website does not establish regional service coverage, licensing terms, commercial availability, a legal company identity, or response time. No email, phone, office, or form destination is invented without verified company material."] },
    ],
    withheldModules: [{ id: "form-shell", status: "absent", requires: ["A06", "A12"] }],
  },
  {
    id: "P20",
    status: "active",
    name: "Page not found",
    path: "/404/",
    canonicalPath: null,
    seo: { title: "Page not found | Halo Database", description: null, canonicalPath: null, robots: "noindex, follow" },
    breadcrumb: [],
    localNavigation: [],
    hero: { eyebrow: null, h1: "Page not found.", lead: "The page may have moved, or the address may be incorrect. Continue with one of the destinations below.", actions: [{ label: "Go to Home", href: "/", kind: "primary" }, { label: "Explore the platform", href: "/product/", kind: "text" }, { label: "Review documentation", href: "/resources/documentation/", kind: "text" }] },
    blocks: [],
    withheldModules: [],
  },
] as const satisfies readonly ActiveSitePage[];
