import type { ActiveSitePage } from "./site-content";

export const manualCorePages = [
  {
    id: "P02",
    status: "active",
    name: "Product overview",
    path: "/product/",
    canonicalPath: "/product/",
    seo: {
      title: "Halo Database Platform Overview",
      description:
        "Explore Halo compatibility modes, database architecture, availability, distributed data, recovery, and operational capabilities.",
      canonicalPath: "/product/",
      robots: "index, follow",
    },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Platform" }],
    localNavigation: [],
    hero: {
      eyebrow: "HALO DATABASE PLATFORM",
      h1: "A unified database platform for compatibility-led modernization.",
      lead:
        "Halo is a general-purpose database built on the openHalo kernel. It combines Oracle, MySQL, and native PostgreSQL operating modes with transactional storage, continuity, recovery, distributed-data options, and DBA tooling.",
      actions: [
        { label: "Explore compatibility", href: "/product/compatibility/", kind: "primary" },
        { label: "See the architecture", href: "/product/architecture/", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "facts",
        heading: "The documented platform at a glance",
        items: [
          { value: "3", label: "operating modes", body: "Oracle, MySQL, and PostgreSQL operating modes are documented within one cluster." },
          { value: "4", label: "E5 layers", body: "Protocol, parsing and semantics, optimization, and execution." },
          { value: "6", label: "core index methods", body: "B-tree, Hash, GiST, SP-GiST, GIN, and BRIN." },
          { value: "45", label: "documented extensions", body: "Grouped across data, integration, security, and diagnostics." },
        ],
      },
      {
        type: "diagram",
        eyebrow: "PLATFORM MODEL",
        heading: "One kernel, three application paths",
        intro: [
          "Each operating mode has its own connection and behavior layer. The underlying Halo kernel provides the database foundations beneath those paths.",
        ],
        layout: "flow",
        nodes: [
          { label: "APPLICATIONS", heading: "Oracle · MySQL · PostgreSQL", body: ["Drivers, tools, and application traffic."], tone: "muted" },
          { label: "INDEPENDENT ENDPOINTS", heading: "Compatibility entry", body: ["Protocol and mode-specific connection behavior."], tone: "accent" },
          { label: "E5 FOUR-LAYER MODEL", heading: "Interpret and execute", body: ["Protocol · semantics · optimizer · execution; PostgreSQL is the native, no-extension mode."], tone: "dark" },
          { label: "HALO KERNEL", heading: "Database foundations", body: ["Transactions · WAL · storage · indexes · partitions · visibility."], tone: "accent" },
        ],
        caption: [
          "Compatibility is implemented across the request path, not presented as syntax conversion alone. Coverage and boundaries remain mode-specific.",
        ],
      },
      {
        type: "cards",
        heading: "What the platform covers",
        items: [
          {
            label: "MODERNIZE",
            heading: "Compatibility and migration",
            body: ["Assess protocols, types, SQL semantics, procedural logic, metadata, and integration dependencies against the workload you intend to move."],
            actions: [{ label: "Review compatibility", href: "/product/compatibility/", kind: "text" }],
          },
          {
            label: "BUILD",
            heading: "Core database foundations",
            body: ["ACID transactions, MVCC isolation, WAL durability, savepoints, rich indexing, multilevel partitioning, and a broad object model."],
            actions: [{ label: "Explore core technology", href: "/product/architecture/", kind: "text" }],
          },
          {
            label: "PROTECT",
            heading: "Availability and recovery",
            body: ["Physical and logical backup, point-in-time recovery, streaming and logical replication, readable replicas, grouped replication, and Halo Shield."],
            actions: [{ label: "Plan continuity", href: "/product/availability-recovery/", kind: "text" }],
          },
          {
            label: "DISTRIBUTE",
            heading: "Data placement and access",
            body: ["DLB, TWR, HSM, and HDS address read scaling, write forwarding, shared storage, and sharded data as distinct topologies."],
            actions: [{ label: "Explore distributed data", href: "/product/distributed/", kind: "text" }],
          },
          {
            label: "OPERATE",
            heading: "Visibility and control",
            body: ["HWR reports, system catalogs and views, diagnostic modules, resource controls, and DBeaver integration support DBA workflows."],
            actions: [{ label: "Explore operations", href: "/product/operations/", kind: "text" }],
          },
          {
            label: "EXTEND",
            heading: "Data and extensions",
            body: ["Optional modules cover integrity, indexing, data types, search, federation, security, events, sampling, and model/runtime registries."],
            actions: [{ label: "Explore extensions", href: "/product/data-platform/", kind: "text" }],
          },
        ],
      },
      {
        type: "comparison",
        heading: "Choose the topology that matches the problem",
        columns: ["Topology", "What it adds", "Decision to validate"],
        rows: [
          ["Single Halo cluster", "Multiple databases, transactional storage, WAL, and native visibility", "Workload behavior and resource design"],
          ["Replicated service", "Primary and readable standbys with synchronous or asynchronous streaming", "Commit latency, lag, and data exposure"],
          ["Managed high availability", "Shield coordination, health checks, fencing, role management, and VIP movement", "Quorum, failover, reconnect, and maintenance"],
          ["Read-scaled access", "DLB read distribution and optional TWR write forwarding", "Read freshness and routing behavior"],
          ["Distributed placement", "HDS sharding or HSM shared-storage architecture", "Data model, failure boundary, and operations"],
        ],
      },
      {
        type: "steps",
        heading: "A roadmap shaped by migration practice",
        items: [
          { heading: "2012 — Origin", body: ["Halo development began in response to an Oracle application migration challenge; SYSDATE was the first recorded compatibility keyword."] },
          { heading: "2021 — Halo 1.0.13", body: ["The first V1 release extended Oracle-oriented procedural compatibility."] },
          { heading: "2022 — First LTS", body: ["Halo 1.0.14 introduced E5, GB18030 support, PL/SQL Package capability, and MySQL protocol and syntax support."] },
          { heading: "2023 — Halo 1.0.15", body: ["Procedural and Oracle sequence behavior continued to expand."] },
          { heading: "June 2024 — Second LTS", body: ["Halo 1.0.16 documented Oracle, MySQL, and PostgreSQL operating modes within one cluster and additional distributed components. The enterprise kernel lineage was later released as openHalo."] },
        ],
      },
      {
        type: "callout",
        label: "ARCHITECTURE OUTCOME",
        heading: "Capabilities are building blocks, not universal guarantees",
        body: [
          "Availability, migration effort, performance, and data-loss exposure depend on the selected mode, topology, settings, and workload. Use the platform map to choose what needs to be tested.",
        ],
      },
      {
        type: "cta",
        heading: "Turn the platform map into a workload decision.",
        body: ["Define the application dependencies, target architecture, and acceptance evidence before selecting a migration or deployment path."],
        actions: [
          { label: "Use the PoC method", href: "/evaluation/", kind: "primary" },
          { label: "Prepare a PoC", href: "/request-poc/?source=product", kind: "secondary" },
        ],
      },
    ],
    withheldModules: [],
  },
  {
    id: "P23",
    status: "active",
    name: "Architecture and core technology",
    path: "/product/architecture/",
    canonicalPath: "/product/architecture/",
    seo: {
      title: "Architecture & Core Technology | Halo Database",
      description: "Understand Halo instances, clusters, transactions, isolation, indexing, partitioning, storage, and database objects.",
      canonicalPath: "/product/architecture/",
      robots: "index, follow",
    },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Platform", href: "/product/" }, { label: "Architecture" }],
    localNavigation: [
      { label: "Instance and cluster", anchor: "instance-cluster" },
      { label: "Transactions", anchor: "transactions" },
      { label: "Indexing", anchor: "indexing" },
      { label: "Partitioning", anchor: "partitioning" },
      { label: "Object model", anchor: "object-model" },
      { label: "Storage and durability", anchor: "storage-durability" },
    ],
    hero: {
      eyebrow: "ARCHITECTURE & CORE TECHNOLOGY",
      h1: "Understand the database beneath the compatibility layer.",
      lead: "Memory, backend and background processes coordinate transactional work. WAL, checkpoints, storage pages, indexes, partitions, and maintenance processes manage the persistent cluster below.",
      actions: [
        { label: "Explore compatibility", href: "/product/compatibility/", kind: "primary" },
        { label: "Review availability", href: "/product/availability-recovery/", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "diagram",
        anchor: "instance-cluster",
        heading: "Inside a Halo deployment",
        intro: ["An instance is the active memory-and-process environment. A cluster is the persistent collection of databases and supporting files managed by it."],
        layout: "hub",
        nodes: [
          { label: "CLIENTS", heading: "Connection requests", body: ["Each connection is served by a backend process."], tone: "muted" },
          { label: "INSTANCE", heading: "Shared and local memory", body: ["Working state shared across processes and private to each process."], tone: "accent" },
          { label: "BACKGROUND", heading: "Database processes", body: ["WAL Writer · Background Writer · Checkpointer · Autovacuum · Statistics Collector."], tone: "dark" },
          { label: "PERSISTENT CLUSTER", heading: "Multiple databases and files", body: ["Data files · WAL · auxiliary files."], tone: "accent" },
        ],
        caption: ["One cluster can contain multiple independent databases. This is not, by itself, a claim about a particular tenant-isolation model."],
      },
      {
        type: "prose",
        anchor: "transactions",
        heading: "Transaction behavior is explicit",
        paragraphs: [
          { text: "Halo supports implicit and explicit transactions, savepoints, commit, and rollback. MVCC lets readers and writers proceed concurrently while the selected isolation level determines which committed changes a transaction can observe." },
        ],
      },
      {
        type: "comparison",
        heading: "Isolation levels",
        columns: ["Requested level", "Documented Halo behavior", "Design implication"],
        rows: [
          ["Read Uncommitted", "Handled as Read Committed under MVCC", "Do not expect dirty-read behavior"],
          ["Read Committed", "Default isolation", "Each statement works from committed visibility"],
          ["Repeatable Read", "Stable transactional view with stricter conflict handling", "Use when repeatable reads matter"],
          ["Serializable", "Strongest documented isolation", "Applications must retry serialization failures"],
        ],
      },
      {
        type: "accordion",
        anchor: "indexing",
        heading: "Indexes for different access patterns",
        intro: ["Halo exposes six core index methods and several design variants. The right method depends on data shape, operators, ordering, and write cost."],
        items: [
          { heading: "B-tree", summary: "Equality, range, and order", details: ["The default general-purpose method for equality and ordered range access."], tags: ["multicolumn", "unique", "sort order", "expression", "partial", "covering"] },
          { heading: "Hash", summary: "Equality", details: ["An equality-oriented access method for supported operator classes."] },
          { heading: "GiST and SP-GiST", summary: "Specialized structures", details: ["Operator-class-driven methods for specialized data, search, and in some cases nearest-neighbor access."], tags: ["GiST", "SP-GiST", "nearest neighbor"] },
          { heading: "GIN", summary: "Values with searchable components", details: ["An inverted index suited to composite values such as full-text and JSONB. GIN does not provide index-only scans."] },
          { heading: "BRIN", summary: "Large physically correlated tables", details: ["Compact block-range summaries for tables whose values correlate with physical order."] },
          { heading: "Design trade-offs", summary: "Reads, writes, and storage", details: ["Broader indexes can improve selected reads while increasing write work and storage. Partial indexes depend on predicates the planner can prove; covering payloads also add size."] },
        ],
      },
      {
        type: "diagram",
        anchor: "partitioning",
        heading: "Partition by lifecycle and access pattern",
        intro: ["Halo documents range, list, hash, and multilevel partitioning, with pruning and attach, detach, and rename lifecycle operations."],
        layout: "cluster",
        nodes: [
          { label: "RANGE", heading: "Ordered boundaries", body: ["Time, numeric, or other ordered ranges."], tone: "accent" },
          { label: "LIST", heading: "Named categories", body: ["Regions, classes, or discrete values."], tone: "default" },
          { label: "HASH", heading: "Key buckets", body: ["Remainder-based distribution across defined partitions."], tone: "dark" },
        ],
        caption: ["Multilevel designs can combine methods. Partitioning is a physical design choice, not an automatic performance guarantee; key selection and predicates determine whether pruning is effective."],
      },
      {
        type: "accordion",
        anchor: "object-model",
        heading: "A broad database object model",
        items: [
          { heading: "Data and presentation", details: ["Tables, foreign tables, ordinary views, materialized views, sequences, constraints, comments, and generated stored columns. Ordinary views reflect current source data; materialized views persist query results and trade freshness for an explicit refresh lifecycle."], tags: ["tables", "views", "materialized views", "sequences", "constraints"] },
          { heading: "Logic and extensibility", details: ["Functions, procedures, triggers, custom types, operators, operator classes and families, languages, collations, conversions, and extensions."], tags: ["functions", "procedures", "triggers", "types", "operators"] },
          { heading: "Security and governance", details: ["Roles, privileges, default access controls, row-level policies, security labels, and optional SELinux-linked controls for supported operations."] },
          { heading: "Integration and replication", details: ["Foreign-data wrappers, servers and user mappings, publications and subscriptions, replication origins and slots, and LISTEN/NOTIFY event primitives."] },
          { heading: "Compatibility objects", details: ["Packages, package/type bodies, synonyms, directories, database links, global temporary tables, recycle-bin metadata, and query mapping extend the object model for migration work."] },
        ],
      },
      {
        type: "diagram",
        anchor: "storage-durability",
        heading: "Storage, durability, and maintenance work together",
        layout: "flow",
        nodes: [
          { label: "1", heading: "Transaction change", body: ["Data and index work begins in the transactional engine."], tone: "muted" },
          { label: "2", heading: "WAL record", body: ["The change is represented in write-ahead logging."], tone: "accent" },
          { label: "3", heading: "Data pages", body: ["Rows are stored in 8 KB pages."], tone: "default" },
          { label: "4", heading: "Checkpoint and archive", body: ["Background writing, checkpoints, archiving, and backup shape recovery."], tone: "dark" },
          { label: "5", heading: "Ongoing maintenance", body: ["Autovacuum and statistics maintain visibility and planning information."], tone: "accent" },
        ],
        caption: ["Durability and recovery outcomes depend on WAL, checkpoint, archive, backup, and replication settings chosen for the deployment."],
      },
      {
        type: "cta",
        heading: "Connect the core architecture to the workload.",
        body: ["Review the mode, transaction, data-model, index, partition, and recovery assumptions that matter to your application."],
        actions: [{ label: "Open the evaluation checklist", href: "/resources/evaluation-checklist/", kind: "primary" }],
      },
    ],
    withheldModules: [],
  },
  {
    id: "P04",
    status: "active",
    name: "Compatibility",
    path: "/product/compatibility/",
    canonicalPath: "/product/compatibility/",
    seo: {
      title: "Oracle, MySQL & PostgreSQL Compatibility | Halo Database",
      description: "Review Halo compatibility across protocols, data types, SQL behavior, procedural logic, metadata, and explicit workload boundaries.",
      canonicalPath: "/product/compatibility/",
      robots: "index, follow",
    },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Platform", href: "/product/" }, { label: "Compatibility" }],
    localNavigation: [
      { label: "E5 model", anchor: "e5-model" },
      { label: "Operating modes", anchor: "mode-comparison" },
      { label: "Oracle", anchor: "oracle" },
      { label: "MySQL", anchor: "mysql" },
      { label: "PostgreSQL", anchor: "postgresql" },
      { label: "Workload boundaries", anchor: "boundaries" },
    ],
    hero: {
      eyebrow: "DATABASE COMPATIBILITY",
      h1: "Compatibility across protocol, language, and execution behavior.",
      lead: "Halo addresses the layers applications encounter: connection protocol, parsing and semantics, optimization, and execution. Oracle, MySQL, and native PostgreSQL modes can coexist while their feature sets and boundaries remain distinct.",
      actions: [
        { label: "Evaluate an Oracle workload", href: "/oracle-migration-evaluation/", kind: "primary" },
        { label: "See the architecture", href: "/product/architecture/", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "diagram",
        anchor: "e5-model",
        heading: "The E5 compatibility model",
        layout: "flow",
        nodes: [
          { label: "01", heading: "Communication protocol", body: ["How applications and tools connect."], tone: "muted" },
          { label: "02", heading: "Parsing and semantics", body: ["How types, functions, syntax, and object behavior are interpreted."], tone: "accent" },
          { label: "03", heading: "Optimizer", body: ["How compatible statements enter planning."], tone: "dark" },
          { label: "04", heading: "Execution", body: ["How the selected behavior is carried out by the Halo kernel."], tone: "accent" },
        ],
        caption: ["The E5 overview includes Oracle, MySQL, and PostgreSQL in its four-layer model. PostgreSQL is also documented as the native mode requiring no compatibility extension; this site preserves both statements without treating them as mutually exclusive."],
      },
      {
        type: "comparison",
        anchor: "mode-comparison",
        heading: "Three modes can coexist without hiding their boundaries",
        columns: ["Mode", "Compatibility focus", "Scope to validate"],
        rows: [
          ["Oracle", "Protocol, Oracle-oriented types/functions, characteristic SQL, PL/oraSQL, Package, and dictionary views", "Feature-level and client-level behavior"],
          ["MySQL", "Protocol, common MySQL 5.6–8.0 features, types, functions, operators, and characteristic DML", "Settings that affect application-visible behavior"],
          ["PostgreSQL", "Native protocol, types, functions, objects, indexes, partitioning, and administration", "Required core families and extensions; no invented target release"],
        ],
      },
      {
        type: "callout",
        label: "MODE ACTIVATION",
        heading: "An endpoint is only one part of compatibility",
        body: ["Oracle and MySQL syntax require the corresponding aux_oracle or aux_mysql extension in the target database. MySQL clients also require compatible password authentication. PostgreSQL is the native mode and needs no compatibility extension. These are product prerequisites; exact setup steps remain in technical documentation."],
      },
      {
        type: "accordion",
        anchor: "oracle",
        heading: "Oracle compatibility, organized by dependency",
        intro: ["Named functions and database objects are part of the product surface. They are shown here as capabilities, not as executable examples."],
        items: [
          { heading: "Data types and date behavior", summary: "Oracle-oriented families", details: ["Documented families include NUMBER, BINARY_FLOAT, BINARY_DOUBLE, VARCHAR2, NVARCHAR2, RAW, BLOB, CLOB, BYTEA, LONG, BOOLEAN, and date/time types. Oracle-style DATE behavior is configurable and must be confirmed for the target workload."], tags: ["NUMBER", "VARCHAR2", "NVARCHAR2", "RAW", "BLOB", "CLOB", "BOOLEAN"] },
          { heading: "SQL and built-in behavior", summary: "Queries and expressions", details: ["Coverage includes ROWNUM, MINUS, DECODE, MERGE, CONNECT BY, common table expressions, analytics, sequences, SYSDATE, DUAL, empty-string handling, Oracle outer joins, formatting, and selected output behavior."], tags: ["ROWNUM", "MINUS", "DECODE", "MERGE", "CONNECT BY", "SYSDATE", "DUAL"] },
          { heading: "PL/oraSQL and Package", summary: "Procedural application logic", details: ["Anonymous blocks, procedures, functions, exceptions, dynamic SQL, cursors, and packages containing public interfaces, routines, types, cursors, variables, constants, and exceptions are documented."], tags: ["PACKAGE", "PACKAGE BODY", "TYPE BODY", "REF CURSOR"] },
          { heading: "System packages", summary: "Compatibility services", details: ["DBMS_ALERT supports asynchronous notification; DBMS_PIPE supports session communication; DBMS_ASSERT validates inputs; DBMS_OUTPUT, DBMS_UTILITY, DBMS_RANDOM, and UTL_FILE cover their documented procedural roles. DBMS_RANDOM is not cryptographic, and UTL_FILE is constrained by registered directories and permissions."], tags: ["DBMS_ALERT", "DBMS_ASSERT", "DBMS_OUTPUT", "DBMS_PIPE", "DBMS_RANDOM", "DBMS_UTILITY", "UTL_FILE"] },
          { heading: "Metadata and administration", summary: "Dictionary visibility", details: ["Oracle-oriented views cover objects, tables, columns, constraints, indexes, procedures, source, views, segments, and product-version information."], tags: ["USER_OBJECTS", "USER_TABLES", "USER_TAB_COLUMNS", "USER_SOURCE", "DBA_SEGMENTS"] },
          { heading: "DBLINK and remote access", summary: "Oracle and PostgreSQL targets", details: ["DBLINK supports documented query and data-change operations against remote Oracle and PostgreSQL systems. It depends on aux_oracle and oracle_fdw in the local database, a schema matching the connection user, and a reachable remote database identity. Remote UPDATE and DELETE also carry the documented primary-key boundary."] },
          { heading: "Flashback and recycle-bin recovery", summary: "Historical reads and dropped objects", details: ["Flashback Query provides historical reads of committed data within the available retention window. It requires commit-timestamp tracking at instance level, restart-level activation, and explicit session enablement. The recycle bin records eligible dropped objects for Flashback to Before Drop recovery and supports an explicit purge lifecycle."] },
          { heading: "Global temporary tables", summary: "Session- or transaction-scoped data", details: ["Global temporary tables provide isolated temporary data, indexes, and schema-visible definitions with either session or transaction lifetime. The capability must be enabled at database level and takes effect after a database service restart."] },
        ],
      },
      {
        type: "accordion",
        anchor: "mysql",
        heading: "MySQL compatibility, with behavior controls exposed",
        items: [
          { heading: "Types and functions", details: ["Numeric, character, ENUM, SET, BLOB, DATE, DATETIME, TIMESTAMP, and four-digit YEAR types are documented, with date, string, numeric, hash, control-flow, and aggregate function families."], tags: ["ENUM", "SET", "AUTO_INCREMENT", "LAST_INSERT_ID", "GROUP_CONCAT"] },
          { heading: "Operators and characteristic DML", details: ["Comparison, logical, and bitwise operators accompany REPLACE INTO, INSERT IGNORE, duplicate-key update behavior, INSERT SET, LIMIT, prepared statements, and session user variables."], tags: ["REPLACE INTO", "INSERT IGNORE", "ON DUPLICATE KEY UPDATE", "LIMIT"] },
          { heading: "Schema and application semantics", details: ["MySQL mode documents schema/database equivalence, backtick identifiers, cross-database queries, FORCE INDEX, create-as/select and create-like patterns, multitable joins and updates, aliases, and generated stored columns where applicable."] },
          { heading: "Client protocol", details: ["MySQL mode exposes the documented native protocol path for MySQL-oriented command-line, JDBC, and ODBC clients. Compatibility still belongs at the driver, pool, authentication, and transaction-behavior level rather than being inferred from a successful connection."] },
          { heading: "Behavior settings", details: ["Packet size, timestamp defaults, error rollback, reported server version, identifier case, multitable data changes, AUTO_INCREMENT behavior, and encoding validation can affect what an application observes. The reported version string is configurable and is not the Halo product version."] },
          { heading: "Known differences", details: ["YEAR accepts four-digit values in the documented behavior. TIMESTAMP defaults to NULL and does not implicitly update without explicit behavior. These differences should remain in the migration test plan."] },
        ],
      },
      {
        type: "accordion",
        anchor: "postgresql",
        heading: "Native PostgreSQL capabilities remain available",
        items: [
          { heading: "Types and functions", details: ["Native numeric, character, date/time, Boolean, BYTEA, JSON, XML, aggregate, and window-function families are documented."], tags: ["JSON", "XML", "BYTEA", "RANK", "ROW_NUMBER", "LEAD", "LAG"] },
          { heading: "Indexes and partitioning", details: ["Six core index methods, multicolumn, unique, expression, partial, and generated-column indexing accompany range, list, hash, multilevel partitioning, pruning, and partition lifecycle operations."] },
          { heading: "Views and relational objects", details: ["Ordinary views compute current results; materialized views persist results and require refresh. Sequences, constraints, roles, permissions, triggers, joins, comments, defaults, and stored generated columns round out the documented object behavior."] },
          { heading: "Native client path", details: ["PostgreSQL mode uses the native protocol for PostgreSQL-oriented clients such as psql and JDBC and does not require the Oracle or MySQL compatibility extensions. The manual does not define a target PostgreSQL release version, so the website names explicit capability families instead of claiming version-wide equivalence."] },
        ],
      },
      {
        type: "accordion",
        anchor: "boundaries",
        heading: "Boundaries to carry into a PoC",
        items: [
          { heading: "Oracle semantics that need a focused test", details: ["Oracle DATE behavior depends on configuration. LISTAGG is documented without WITHIN GROUP; regular expressions use POSIX Advanced Regular Expressions; BITAND works through integer conversion; NVL2 requires compatible result types; and a documented SUBTRACT form is limited."] },
          { heading: "Remote access and procedural clients", details: ["Remote UPDATE and DELETE through Oracle DBLINK require a primary key on the remote table. Some procedural script terminator behavior varies by client, so client tooling belongs in the compatibility test."] },
          { heading: "Structured error behavior", details: ["Native and Oracle endpoints use stable five-character SQLSTATE classes with separate object fields where available. Oracle mode adds private UE and HERR error families. The MySQL protocol endpoint uses MySQL-style numeric errors and SQLSTATE, so error handling is protocol-specific."] },
          { heading: "Why boundaries are published", details: ["They do not negate compatibility. They identify where representative tests provide more useful evidence than a blanket equivalence percentage."] },
        ],
      },
      {
        type: "cta",
        heading: "Move from feature lists to workload evidence.",
        body: ["Inventory the protocol, schema objects, SQL semantics, procedural code, metadata views, error handling, and remote dependencies your application uses."],
        actions: [
          { label: "Plan an Oracle evaluation", href: "/oracle-migration-evaluation/", kind: "primary" },
          { label: "Open the checklist", href: "/resources/evaluation-checklist/", kind: "secondary" },
        ],
      },
    ],
    withheldModules: [],
  },
  {
    id: "P03",
    status: "active",
    name: "Oracle migration evaluation",
    path: "/oracle-migration-evaluation/",
    canonicalPath: "/oracle-migration-evaluation/",
    seo: {
      title: "Oracle Migration Evaluation | Halo Database",
      description: "Evaluate Oracle protocol, schema, SQL, PL/SQL, Package, metadata, DBLINK, recovery, and operating dependencies on Halo.",
      canonicalPath: "/oracle-migration-evaluation/",
      robots: "index, follow",
    },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Oracle migration" }],
    localNavigation: [
      { label: "Migration principle", anchor: "migration-principle" },
      { label: "Dependency inventory", anchor: "dependency-inventory" },
      { label: "Evaluation flow", anchor: "evaluation-flow" },
      { label: "Oracle surfaces", anchor: "oracle-surfaces" },
      { label: "Migration pressure", anchor: "migration-pressure" },
      { label: "PoC outcomes", anchor: "poc-outcomes" },
    ],
    hero: {
      eyebrow: "ORACLE MIGRATION EVALUATION",
      h1: "Evaluate compatibility before you estimate the rewrite.",
      lead: "Halo documents Oracle-oriented behavior across protocol, data types, SQL semantics, PL/oraSQL, Package, dictionary views, and remote access. A migration evaluation shows what can remain, what needs configuration, and what still requires change.",
      actions: [
        { label: "Prepare a workload PoC", href: "/request-poc/?source=oracle-migration", kind: "primary" },
        { label: "Explore Oracle compatibility", href: "/product/compatibility/#oracle", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "callout",
        anchor: "migration-principle",
        label: "MIGRATION PRINCIPLE",
        heading: "Compatibility can reduce change; it does not remove validation",
        body: ["Halo originated in an Oracle migration project and its Oracle mode is designed to reduce database-layer and application rewriting. The result still depends on the source system’s behaviors, dependencies, and operational assumptions."],
      },
      {
        type: "cards",
        anchor: "dependency-inventory",
        heading: "Inventory what drives migration effort",
        items: [
          { heading: "Connection path", body: ["Drivers, protocol expectations, endpoints, connection pools, and database tools."] },
          { heading: "Schema and data model", body: ["Types, sequences, constraints, indexes, partitions, temporary tables, and object naming."] },
          { heading: "SQL semantics", body: ["Functions, ROWNUM, joins, MINUS, MERGE, hierarchy, analytics, empty strings, and date behavior."] },
          { heading: "Procedural logic", body: ["PL/oraSQL blocks, routines, exceptions, cursors, dynamic SQL, Package APIs, and session state."] },
          { heading: "Administration and integration", body: ["Dictionary views, DBLINK, foreign access, error handling, jobs, reporting, and monitoring."] },
        ],
      },
      {
        type: "steps",
        anchor: "evaluation-flow",
        heading: "A four-stage evaluation",
        items: [
          { heading: "1. Map", body: ["Classify dependencies by protocol, schema, SQL, procedural logic, metadata, remote access, continuity, and operations."] },
          { heading: "2. Match", body: ["Identify documented Halo behavior, configuration requirements, and known boundaries for each dependency."] },
          { heading: "3. Validate", body: ["Run representative business transactions and operational scenarios in the intended mode and topology."] },
          { heading: "4. Decide", body: ["Record retained behavior, required configuration, necessary changes, and unresolved risks before setting the plan."] },
        ],
      },
      {
        type: "accordion",
        anchor: "oracle-surfaces",
        heading: "Oracle surfaces available for assessment",
        items: [
          { heading: "Types and data behavior", details: ["NUMBER and floating-point families; VARCHAR2 and NVARCHAR2; RAW and large objects; Boolean and date/time families; configurable Oracle-style DATE; and empty-string handling."] },
          { heading: "SQL behavior", details: ["ROWNUM, MINUS, DECODE, MERGE, Oracle outer joins, hierarchy, sequences, SYSDATE, DUAL, common table expressions, analytics, formatting, and selected output behavior."] },
          { heading: "PL/oraSQL and Package", details: ["Blocks, procedures, functions, exceptions, cursors, dynamic SQL, packages, types, variables, constants, and the documented system-package set."] },
          { heading: "Metadata and integration", details: ["Oracle-oriented dictionary views, synonyms, directories, DBLINK, query mapping, historical committed reads, recycle-bin metadata, and session- or transaction-scoped global temporary tables."] },
        ],
      },
      {
        type: "comparison",
        anchor: "migration-pressure",
        heading: "Turn rewrite pressure into test questions",
        columns: ["Potential pressure", "Halo surface to assess", "Evidence to capture"],
        rows: [
          ["Changing connectivity", "Oracle-compatible endpoint", "Driver, pool, and tool results"],
          ["Translating schema types", "Oracle-oriented type families", "Loaded values, precision, and dates"],
          ["Rewriting SQL", "Characteristic Oracle SQL and functions", "Representative query and transaction results"],
          ["Rebuilding procedural logic", "PL/oraSQL and Package", "Compile, state, and execution outcomes"],
          ["Replacing metadata queries", "Oracle-oriented dictionary views", "Fields used by administrative workflows"],
          ["Redesigning remote access", "DBLINK and foreign-data paths", "Read/write, key, and transaction expectations"],
          ["Rebuilding continuity", "Replication, RMAN2, and Shield", "Recovery, failover, reconnect, and runbook evidence"],
        ],
      },
      {
        type: "callout",
        label: "PRACTICE-DERIVED EVIDENCE",
        heading: "Keep reported migration reduction in context",
        body: ["The Halo manual reports at least 95% lower Oracle-related application code changes in migration practice. This is supporting evidence from the source manual, not a universal outcome, zero-change promise, performance guarantee, or substitute for an inventory and PoC."],
      },
      {
        type: "checklist",
        anchor: "poc-outcomes",
        heading: "What a PoC should resolve",
        items: [
          "Can representative applications connect through the intended endpoint?",
          "Are required types, SQL semantics, objects, and procedural behaviors preserved?",
          "Are transaction isolation, error behavior, and client tooling acceptable?",
          "Which compatibility settings are required?",
          "Which documented boundaries affect the workload?",
          "Do backup, recovery, replication, and failover meet the selected topology’s objectives?",
          "Which remaining items are application changes, operational changes, or open decisions?",
        ],
        outro: ["The useful output is a decision record: retained behavior, required configuration, verified changes, and unresolved risk."],
      },
      {
        type: "cta",
        heading: "Build the migration case from representative evidence.",
        actions: [
          { label: "Prepare a PoC", href: "/request-poc/?source=oracle-migration-final", kind: "primary" },
          { label: "Open the evaluation checklist", href: "/resources/evaluation-checklist/", kind: "secondary" },
        ],
      },
    ],
    withheldModules: [],
  },
] as const satisfies readonly ActiveSitePage[];
