import type { ActiveSitePage } from "./site-content";

export const manualJourneyPages = [
  {
    id: "P01",
    status: "active",
    name: "Home",
    path: "/",
    canonicalPath: "/",
    seo: {
      title: "Halo Database | One Database, Three Operating Modes",
      description: "Explore how Halo 1.0.16 handles compatibility, migration decisions, conditional role changes, database-aware routing, and partitioned data placement.",
      canonicalPath: "/",
      robots: "index, follow",
    },
    breadcrumb: [],
    localNavigation: [],
    hero: {
      eyebrow: "Compatibility-led database modernization",
      h1: "One database. Three ways in.",
      lead: "Halo 1.0.16 supports Oracle, MySQL, and PostgreSQL operating modes within one cluster. Explore compatibility, migration, continuity, and distributed data one mechanism at a time.",
      actions: [
        { label: "Explore the mechanisms", href: "#technology-story", kind: "primary" },
        { label: "Explore the architecture", href: "/product/architecture/", kind: "secondary" },
        { label: "Prepare a demo brief", href: "/request-demo/?source=home-hero", kind: "text" },
      ],
    },
    blocks: [
      {
        type: "diagram",
        anchor: "technology-story",
        eyebrow: "Five problems · Five distinct mechanisms",
        heading: "See what changes inside Halo.",
        intro: [
          "Each section isolates one customer problem, the Halo mechanism that addresses it, and the result a team can evaluate next.",
        ],
        layout: "flow",
        nodes: [
          {
            label: "COMPATIBILITY",
            heading: "Keep expected application behavior in view.",
            body: [
              "Migration risk is rarely SQL alone: protocol, types, procedural logic, metadata, and optimizer-visible semantics can all matter.",
              "Halo E5 carries a selected Oracle, MySQL, or native PostgreSQL operating-mode request through protocol, parsing and semantics, optimization, and execution.",
              "Teams can trace where behavior is interpreted before validating exact workload coverage.",
            ],
            tone: "accent",
          },
          {
            label: "MIGRATION",
            heading: "Turn hidden dependencies into decisions.",
            body: [
              "Moving rows does not resolve procedural logic, remote access, drivers, tools, or transactional expectations.",
              "The evaluation path inventories each dependency, maps documented candidates, assigns representative tests, and keeps remediation or unresolved gaps visible.",
              "The team leaves with retain, verify, remediate, or stop decisions instead of a generic compatibility percentage.",
            ],
            tone: "default",
          },
          {
            label: "HIGH AVAILABILITY",
            heading: "Move a role only after the control path agrees.",
            body: [
              "A failed primary can become a split-brain risk if traffic moves before control state and fencing are established.",
              "Shield evaluates health plus etcd quorum and leader state, protects the topology through fencing, checks replica eligibility, and coordinates role and VIP movement when conditions pass.",
              "A role change becomes an explicit, conditional sequence—not an unconditional failover promise.",
            ],
            tone: "dark",
          },
          {
            label: "READ / WRITE ROUTING",
            heading: "Let database semantics choose the path.",
            body: [
              "A read-only connection usually cannot accept a write without application or proxy routing logic.",
              "TWR uses statement semantics, transaction state, and object type to keep read work local and forward detected writes to the read/write node, returning the result through the original connection.",
              "Teams can evaluate a database-aware route without treating TWR as an external proxy or a latency guarantee.",
            ],
            tone: "accent",
          },
          {
            label: "SHARDING",
            heading: "Route a partition to the data that owns its range.",
            body: [
              "A distributed query becomes wasteful when every data node receives work that its range cannot answer.",
              "HDS presents one logical database through a worker; partition mappings, shard_fdw, predicate pushdown, and pruning direct relevant ranges to independent Halo data nodes.",
              "Teams can understand the placement model before evaluating worker availability, resharding, and cross-shard transaction requirements.",
            ],
            tone: "muted",
          },
        ],
        caption: ["These are simplified mechanism explainers, not deployment topologies. Results depend on the Halo build, selected mode or component, settings, workload, topology, and operating policy."],
      },
      {
        type: "facts",
        anchor: "product-proof",
        heading: "Migration started the product. Workload evidence decides the fit.",
        intro: ["The Halo 1.0.16 documentation records the history and product counts below. None replaces evaluation against the target workload and topology."],
        items: [
          { value: "2012", label: "manual-traced migration origin", body: "The Halo manual traces the database lineage to an Oracle application migration challenge." },
          { value: "≥95%", label: "manual-reported Oracle-related application code-change reduction", body: "Reported from Oracle migration practice; workload-specific, not universal and not a forecast." },
          { value: "45", label: "documented extensions", body: "Grouped across diagnostics, data, search, integration, security, events, and utilities." },
        ],
      },
      {
        type: "cta",
        heading: "Start with the proof you need.",
        body: ["Investigate a mechanism, build a defined proof-of-concept scope, or prepare the product and commercial questions your team needs next."],
        actions: [
          { label: "Open the evaluation checklist", href: "/resources/evaluation-checklist/", kind: "primary" },
          { label: "Evaluate an Oracle workload", href: "/oracle-migration-evaluation/", kind: "secondary" },
          { label: "Prepare a demo brief", href: "/request-demo/?source=home-final", kind: "text" },
          { label: "Ask about product access", href: "/contact-sales/?source=home-final", kind: "text" },
        ],
      },
    ],
    withheldModules: [
      { id: "case-proof", status: "absent", requires: ["A01"] },
      { id: "partner-strip", status: "absent", requires: ["A08", "A06", "A12"] },
    ],
  },
  {
    id: "P07",
    status: "active",
    name: "Proof-of-concept method",
    path: "/evaluation/",
    canonicalPath: "/evaluation/",
    seo: {
      title: "Halo Database Proof-of-Concept Method",
      description: "Define the workload, test Halo against agreed criteria, and leave with a proceed, remediate, or stop decision.",
      canonicalPath: "/evaluation/",
      robots: "index, follow",
    },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Proof of concept" }],
    localNavigation: [],
    hero: {
      eyebrow: "PROOF OF CONCEPT",
      h1: "Turn product capability into a workload decision.",
      lead: "A Halo PoC defines the application, target architecture, and acceptance criteria before testing compatibility, performance, continuity, distributed behavior, and day-to-day operations.",
      actions: [
        { label: "Open the evaluation checklist", href: "/resources/evaluation-checklist/", kind: "primary" },
        { label: "Plan a PoC", href: "/request-poc/?source=evaluation", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "steps",
        heading: "Five steps to a defensible decision",
        items: [
          { heading: "1. Frame the decision", body: ["Name the application, source product and version, business reason, owners, decision date, and non-negotiable requirements."] },
          { heading: "2. Map the dependency surface", body: ["Inventory objects, procedural logic, drivers, frameworks, integrations, transaction behavior, data profile, workload, and operating dependencies."] },
          { heading: "3. Select the Halo architecture", body: ["Choose the mode, topology, replication and recovery design, distributed components, operating environment, exact build, and optional modules in scope."] },
          { heading: "4. Run representative tests", body: ["Test application behavior, integrations, workload, failover, backup, restore, PITR, diagnostics, and operator tasks under agreed conditions."] },
          { heading: "5. Record the decision", body: ["Mark each material requirement passed as tested, passed with remediation, unsupported in scope, or not tested; assign owners and retest conditions before recommending proceed, remediate, or stop."] },
        ],
      },
      {
        type: "callout",
        label: "PRODUCT ACCESS",
        heading: "A Halo Database PoC needs the right package and license",
        body: ["Halo Database is commercial, licensed software. Installation packages and evaluation licenses are coordinated with Halo Tech. openHalo is a separate GPL-3.0 open-source project.", "Before testing begins, Halo Tech confirms the target platform and build, provides the installation package, and prepares a license for the agreed PoC environment."],
      },
      {
        type: "comparison",
        heading: "A demo and a PoC answer different questions",
        columns: ["Demo", "Proof of concept"],
        rows: [
          ["Introduces documented capabilities", "Tests a defined workload"],
          ["Uses prepared product material", "Uses representative application inputs"],
          ["Helps decide whether to investigate", "Helps decide whether to proceed"],
          ["Does not establish application fit", "Produces scoped evidence and exceptions"],
        ],
      },
      {
        type: "cards",
        heading: "Run the lanes that affect the decision",
        items: [
          { heading: "Compatibility", body: ["Application behavior, database objects, procedural logic, drivers, tools, integrations, transactions, and errors."] },
          { heading: "Workload", body: ["Representative query mix, concurrency, batch work, resource use, stability, and agreed performance measures."] },
          { heading: "Continuity", body: ["Replication, failover, reconnect, backup, validation, restore, PITR, and former-primary rejoin."] },
          { heading: "Operations", body: ["Monitoring, HWR, diagnostics, maintenance, resource controls, administration tools, and ownership."] },
          { heading: "Distributed topology", body: ["DLB, TWR, HSM, or HDS routing, failure, consistency, placement, and lifecycle behavior when applicable."] },
        ],
      },
      {
        type: "checklist",
        heading: "What a useful PoC leaves behind",
        items: [
          "Source and target inventory",
          "Requirement-to-test matrix",
          "Reproducible environment record",
          "Observations and retained evidence",
          "Compatibility and exception register",
          "Remediation, ownership, and retest plan",
          "Proceed, remediate, or stop recommendation",
        ],
      },
      {
        type: "callout",
        label: "EVIDENCE DISCIPLINE",
        heading: "Keep source, conditions, and limits attached",
        body: ["A manual statement is not a workload result. A generic benchmark is not an application result. Every conclusion should preserve the build, environment, topology, inputs, measurement, and unresolved boundaries behind it."],
      },
      {
        type: "cta",
        heading: "Define what Halo must prove.",
        actions: [{ label: "Plan a PoC", href: "/request-poc/?source=evaluation-final", kind: "primary" }],
      },
    ],
    withheldModules: [],
  },
  {
    id: "P08",
    status: "active",
    name: "Resources",
    path: "/resources/",
    canonicalPath: "/resources/",
    seo: {
      title: "Halo Database Resources",
      description: "Find Halo product, migration, architecture, recovery, distributed-data, operations, evidence, and evaluation resources by question.",
      canonicalPath: "/resources/",
      robots: "index, follow",
    },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Resources" }],
    localNavigation: [],
    hero: {
      eyebrow: "RESOURCES",
      h1: "Find the product answer by question—not by manual chapter.",
      lead: "Explore what Halo supports, how migration is evaluated, how continuity is designed, how the platform is operated, and what evidence still needs to be produced.",
      actions: [
        { label: "Start with the platform", href: "/product/", kind: "primary" },
        { label: "Open the evaluation checklist", href: "/resources/evaluation-checklist/", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "cards",
        heading: "Choose a path",
        items: [
          { heading: "Understand the platform", body: ["Start with the Halo core architecture, multimode behavior, and enterprise capability map."], actions: [{ label: "Product overview", href: "/product/", kind: "text" }, { label: "Architecture", href: "/product/architecture/", kind: "text" }] },
          { heading: "Plan compatibility and migration", body: ["Review Oracle, MySQL, and PostgreSQL behavior, then turn application dependencies into a migration assessment."], actions: [{ label: "Compatibility", href: "/product/compatibility/", kind: "text" }, { label: "Oracle migration", href: "/oracle-migration-evaluation/", kind: "text" }] },
          { heading: "Design continuity and distributed data", body: ["Explore replication, recovery, Shield, DLB, TWR, HSM, and HDS with their documented boundaries."], actions: [{ label: "Availability & recovery", href: "/product/availability-recovery/", kind: "text" }, { label: "Distributed data", href: "/product/distributed/", kind: "text" }] },
          { heading: "Operate and extend", body: ["Review tuning surfaces, resource controls, HWR, system visibility, data types, federation, and optional modules."], actions: [{ label: "Operations", href: "/product/operations/", kind: "text" }, { label: "Data & extensions", href: "/product/data-platform/", kind: "text" }] },
          { heading: "Trace claims", body: ["See the source behind material statements, what each establishes, and what still requires validation."], actions: [{ label: "Evidence & validation", href: "/resources/evidence/", kind: "text" }, { label: "Documentation basis", href: "/resources/documentation/", kind: "text" }] },
          { heading: "Prepare an evaluation", body: ["Capture the workload, target architecture, acceptance criteria, and decision owners before requesting a PoC."], actions: [{ label: "Evaluation checklist", href: "/resources/evaluation-checklist/", kind: "text" }, { label: "PoC method", href: "/evaluation/", kind: "text" }] },
        ],
      },
      {
        type: "callout",
        label: "CONTENT BOUNDARY",
        heading: "Product knowledge here; operating instructions in documentation",
        body: ["This website explains capability, architecture, value, and limits. SQL, commands, configuration files, terminal output, screenshots, and step-by-step operating procedures are intentionally not reproduced in the enterprise-site body."],
      },
    ],
    withheldModules: [],
  },
  {
    id: "P09",
    status: "active",
    name: "Documentation basis",
    path: "/resources/documentation/",
    canonicalPath: "/resources/documentation/",
    seo: {
      title: "Halo 1.0.16 Product Documentation Basis",
      description: "See how the Halo 1.0.16 manual is reorganized into enterprise product, migration, architecture, and operations content.",
      canonicalPath: "/resources/documentation/",
      robots: "index, follow",
    },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Resources", href: "/resources/" }, { label: "Documentation basis" }],
    localNavigation: [],
    hero: {
      eyebrow: "DOCUMENTATION BASIS",
      h1: "Product knowledge, reorganized for enterprise evaluation.",
      lead: "This website uses the complete Halo 1.0.16 user-manual Markdown set as its primary product source, then reorganizes that knowledge around customer questions rather than reproducing the manual chapter by chapter.",
      actions: [
        { label: "Review evidence", href: "/resources/evidence/", kind: "primary" },
        { label: "Explore the platform", href: "/product/", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "comparison",
        heading: "What belongs where",
        columns: ["On this website", "In technical documentation"],
        rows: [
          ["Product positioning and capability", "Exact commands and syntax"],
          ["Architecture and topology concepts", "Installation and CLI procedures"],
          ["Compatibility scope and boundaries", "SQL, DDL, DML, and language examples"],
          ["Migration and operational value", "Configuration files and parameter values"],
          ["Evidence limits and evaluation questions", "Terminal output, logs, and troubleshooting steps"],
        ],
      },
      {
        type: "accordion",
        heading: "The source families behind the site",
        items: [
          { heading: "Product and architecture", summary: "Chapters 1–2", details: ["Product origin and release history, instance/cluster architecture, transactions, storage, indexes, partitioning, and database objects."] },
          { heading: "Deployment and tuning", summary: "Chapters 3–6", details: ["Documented processor and operating-system families, installer workflow, initialization, character sets, and configuration surfaces."] },
          { heading: "Compatibility", summary: "Chapters 7–10", details: ["E5, multiple operating modes, and Oracle, MySQL, and native PostgreSQL behavior and boundaries."] },
          { heading: "Backup and availability", summary: "Chapters 11–15", details: ["Protection models, RMAN2, physical/logical/grouped replication, and Halo Shield."] },
          { heading: "Distributed capabilities", summary: "Chapters 16–19", details: ["DLB, TWR, HSM, and HDS architecture and operational boundaries."] },
          { heading: "Operations and tooling", summary: "Chapters 20–22", details: ["Resource controls, HWR, Statement Sharing, and DBeaver."] },
          { heading: "Reference inventories", summary: "Appendices A–G", details: ["SQL object families, RMAN2 scope, system catalogs/views, 45 extensions, structured errors, compatibility additions, and Shield cluster operations. Syntax and commands are excluded from the site body while the capabilities they prove are retained."] },
        ],
      },
      {
        type: "facts",
        heading: "Frozen source snapshot used for this refactor",
        items: [
          { value: "80", label: "Markdown files" },
          { value: "40,934", label: "source lines" },
          { value: "14,502", label: "nonblank non-code lines" },
          { value: "80/80", label: "hash matches", body: "Every file matched the source map at the implementation freeze." },
        ],
      },
      {
        type: "checklist",
        heading: "Before relying on a documented capability",
        items: [
          "Confirm the exact Halo version and build",
          "Confirm the operating mode and optional modules",
          "Separate capability description from configuration example",
          "Preserve stated limitations and prerequisites",
          "Validate the requirement with the intended application and topology",
        ],
      },
      {
        type: "callout",
        label: "VERSION NOTE",
        heading: "Halo 1.0.16 is the factual release baseline",
        body: ["The release history identifies Halo 1.0.16 as the second LTS release, published in June 2024. Current package availability, platform certification, and support scope still require confirmation for a specific deployment."],
      },
      {
        type: "callout",
        label: "PRODUCT ACCESS",
        heading: "Public documentation is not a public Halo Database download",
        body: ["Halo Database is commercial, licensed software. Installation packages and evaluation licenses are coordinated with Halo Tech. openHalo is a separate GPL-3.0 open-source project.", "The official installation documentation directs evaluators to Halo Tech or an authorized agent for the package and license file. Coordinate the exact build and target environment before following the installation procedure."],
      },
      {
        type: "links",
        actions: [
          { label: "Email Halo Tech about a PoC", href: "mailto:support@halodbtech.com?subject=Halo%20Database%20PoC%20access", kind: "primary" },
          { label: "Plan a PoC", href: "/request-poc/?source=documentation-access", kind: "text" },
        ],
      },
    ],
    withheldModules: [],
  },
  {
    id: "P10",
    status: "active",
    name: "Evidence and validation",
    path: "/resources/evidence/",
    canonicalPath: "/resources/evidence/",
    seo: {
      title: "Evidence & Validation | Halo Database",
      description: "See what material Halo statements establish, their manual source, their limits, and what a workload evaluation must validate.",
      canonicalPath: "/resources/evidence/",
      robots: "index, follow",
    },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Resources", href: "/resources/" }, { label: "Evidence & Validation" }],
    localNavigation: [],
    hero: {
      eyebrow: "EVIDENCE & VALIDATION",
      h1: "See what each Halo claim establishes—and what it does not.",
      lead: "Material statements are paired with their manual source, practical meaning, boundary, and workload question.",
      actions: [
        { label: "Open the evaluation checklist", href: "/resources/evaluation-checklist/", kind: "primary" },
        { label: "See the documentation basis", href: "/resources/documentation/", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "evidence",
        heading: "Material product evidence",
        fieldLabels: { statement: "Documented statement", source: "Manual source", limit: "What it does not prove", test: "What to validate" },
        records: [
          { heading: "Product identity and release", statement: "Halo is described as a general-purpose unified database. Halo 1.0.16 is listed as the second LTS release, published in June 2024.", source: "Chapters 1–2", limit: "This does not confirm current packaging, certification, regional service, or an English legal company identity. The separate openHalo project has its own GPL-3.0 distribution model.", test: "Confirm the exact build, package, platform, and support scope intended for deployment." },
          { heading: "Multimode compatibility", statement: "One instance can run Oracle, MySQL, and PostgreSQL modes concurrently; E5 spans protocol, parsing/semantics, optimization, and execution.", source: "Chapter 7; Chapters 8–10", limit: "This does not establish complete equivalence or unchanged behavior for every application.", test: "Test the data types, functions, objects, procedural behavior, drivers, transactions, and errors the application uses." },
          { heading: "Reported Oracle migration practice", statement: "The manual reports at least 95% lower Oracle-related application code changes in migration practice.", source: "Chapter 1; Oracle overview", limit: "This is not a universal percentage, zero-change promise, hour-scale promise, or performance guarantee.", test: "Measure required changes against a representative dependency inventory and PoC record." },
          { heading: "Continuity and recovery", statement: "The manual documents physical/logical replication and backup; incremental physical modes; validation; and PITR to time, LSN, transaction ID, restore point, or timeline.", source: "Chapters 11–15; Appendix B", limit: "Mechanisms alone do not establish an SLA, RPO, or RTO. Sync and async choices differ.", test: "Exercise the intended topology, failure, reconnect, data state, and operator procedure." },
          { heading: "Distributed data paths", statement: "DLB, TWR, HSM, and HDS address read distribution, write forwarding, shared storage, and sharded placement as distinct components.", source: "Chapters 16–19", limit: "The source does not establish universal active-active behavior, linear scale, online resharding, distributed transactions, or topology-independent durability.", test: "Select the component and topology, then test routing, failure, consistency, placement, lifecycle, and operations." },
          { heading: "Operations and observability", statement: "HWR snapshots and interval reports, 139 catalog/view objects, and 45 extension modules provide documented paths for visibility and diagnostics.", source: "Chapter 21; Appendices C–D", limit: "Counts do not mean every module is installed or enabled by default; HWR has dependencies and collection behavior.", test: "Confirm installed modules, permissions, collection settings, retention, overhead, and workflow." },
          { heading: "Documented platform reach", statement: "The installation material lists multiple x86, ARM, MIPS, and Alpha families and several Linux distributions plus FreeBSD.", source: "Chapter 3", limit: "A manual list is not a current certification or support matrix.", test: "Confirm processor, operating-system version, package, and support status before procurement." },
        ],
      },
      {
        type: "callout",
        label: "NOT PUBLISHED AS PRODUCT FACT",
        heading: "Claims without a sufficient canonical basis",
        body: ["No evidence record is published for DataOS, SQL firewall, universal RPO 0, universal sub-60-second RTO, zero code change, zero performance loss, HSM active-active/RAC equivalence, HDS linear scaling, or a general AI platform beyond the documented MRT/catalog mechanism."],
      },
    ],
    withheldModules: [],
  },
  {
    id: "P11",
    status: "active",
    name: "Evaluation checklist",
    path: "/resources/evaluation-checklist/",
    canonicalPath: "/resources/evaluation-checklist/",
    seo: {
      title: "Halo Database Evaluation Checklist",
      description: "Prepare the application, compatibility surface, data, workload, target architecture, operations, and acceptance record for a Halo PoC.",
      canonicalPath: "/resources/evaluation-checklist/",
      robots: "index, follow",
    },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Resources", href: "/resources/" }, { label: "Evaluation checklist" }],
    localNavigation: [],
    hero: {
      eyebrow: "EVALUATION CHECKLIST",
      h1: "Bring the application, architecture, and decision criteria.",
      lead: "Use this checklist to define a representative Halo evaluation before testing begins.",
      actions: [
        { label: "Plan a PoC", href: "/request-poc/?source=checklist", kind: "primary" },
        { label: "See the PoC method", href: "/evaluation/", kind: "secondary" },
      ],
    },
    blocks: [
      { type: "checklist", heading: "1. Decision and source estate", items: ["Application, business purpose, and criticality", "Source product, edition, version, and topology", "Business owner, technical owner, and decision date", "Migration, consolidation, or architecture question", "Non-negotiable and stop-early requirements"] },
      { type: "checklist", heading: "2. Compatibility surface", items: ["Required Oracle, MySQL, or PostgreSQL mode", "Types, functions, operators, and query behavior", "Schemas, tables, indexes, partitions, views, and sequences", "Procedures, functions, packages, triggers, and temporary objects", "Transactions, isolation, locking, and error behavior", "DBLINK, foreign-data, and extension dependencies"] },
      { type: "checklist", heading: "3. Application and integration", items: ["Drivers, connection pools, frameworks, and ORM", "Jobs, reporting, administration, and monitoring tools", "Authentication, authorization, and cryptographic requirements", "Upstream, downstream, and external-service dependencies"] },
      { type: "checklist", heading: "4. Data and workload", items: ["Data volume, distribution, growth, and retention", "Representative transactions and query mix", "Concurrency, batch windows, and peak conditions", "Latency, throughput, stability, and resource criteria", "Sensitive-data and secure-transfer constraints"] },
      { type: "checklist", anchor: "target-architecture", heading: "5. Target architecture and continuity", items: ["Processor, operating system, storage, network, and topology", "Replication mode and synchronization level", "Failover, switchover, fencing, and application reconnect", "Backup type, validation, retention, restore, and PITR", "DLB, TWR, HSM, or HDS requirements when applicable"] },
      { type: "checklist", anchor: "operations", heading: "6. Operations and observability", items: ["Installation and configuration ownership", "Monitoring, HWR, and diagnostic evidence", "Resource controls and tuning responsibilities", "Maintenance, upgrade, and recovery procedures", "Required extensions and administration tools"] },
      { type: "checklist", heading: "7. Acceptance and decision record", items: ["Requirement owner and test owner", "Expected result and measurement method", "Evidence to retain", "Passed, remediation, unsupported, or untested status", "Retest conditions", "Proceed, remediate, or stop recommendation"] },
      {
        type: "callout",
        label: "DATA HANDLING",
        heading: "Keep sensitive material out of public inquiry routes",
        body: ["Do not place credentials, production records, customer data, or confidential database content in a public inquiry. Agree on secure transfer and representative test-data handling during qualification."],
      },
      { type: "cta", heading: "Ready to define the evidence plan?", actions: [{ label: "Plan a PoC", href: "/request-poc/?source=checklist-final", kind: "primary" }] },
    ],
    withheldModules: [],
  },
  {
    id: "P13",
    status: "active",
    name: "Ecosystem partners",
    path: "/partners/",
    canonicalPath: "/partners/",
    seo: {
      title: "Partners & Compatibility Ecosystem | Halo Tech",
      description: "Explore Halo Tech’s published compatibility ecosystem and the paths for product verification, technical integration, and private partnership discussions.",
      canonicalPath: "/partners/",
      robots: "index, follow",
    },
    breadcrumb: [
      { label: "Home", href: "/" },
      { label: "About Us", href: "/company/" },
      { label: "Partners" },
    ],
    localNavigation: [
      { label: "Relationship boundary", anchor: "partner-boundary" },
      { label: "Compatibility ecosystem", anchor: "compatibility-ecosystem" },
      { label: "Published roster", anchor: "partner-roster" },
      { label: "Cooperation paths", anchor: "cooperation-paths" },
      { label: "Contact", anchor: "partner-contact" },
    ],
    hero: {
      eyebrow: "ECOSYSTEM AND PARTNERS",
      h1: "Compatibility first, collaboration by discussion.",
      lead: "Halo Tech has published compatibility and mutual-certification work across operating systems, processors, infrastructure software, and industry applications. Separate commercial or channel relationships, if any, are discussed privately and are not established by this page.",
      actions: [
        { label: "Explore Halo Database", href: "/product/", kind: "primary" },
        { label: "Email about ecosystem compatibility", href: "mailto:support@halodbtech.com?subject=Halo%20ecosystem%20compatibility%20inquiry", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "callout",
        anchor: "partner-boundary",
        label: "RELATIONSHIP BOUNDARY",
        heading: "Compatibility activity is not the same as a commercial partnership",
        body: ["Compatibility testing, mutual certification, technical integration, and commercial or channel cooperation are different relationships. This page does not grant partner status, authorization, resale rights, territory, exclusivity, pricing, certification rights, benefits, lead supply, support commitments, or endorsement."],
      },
      {
        type: "cards",
        anchor: "compatibility-ecosystem",
        heading: "Published compatibility ecosystem",
        intro: ["Halo Tech’s published company material describes compatibility and mutual-certification work involving operating-system, processor, middleware, infrastructure, and application vendors. Confirm the exact product versions, certificate scope, date, and current status when a procurement or deployment decision depends on a named platform."],
        items: [
          { heading: "Operating systems", body: ["Discuss supported platform versions, deployment requirements, and the evidence required for the intended environment."] },
          { heading: "Processors and hardware", body: ["Confirm processor architecture, server platform, operating system, and the exact product build together."] },
          { heading: "Middleware and infrastructure", body: ["Define interfaces, topology, versions, and representative integration workflows before drawing a compatibility conclusion."] },
          { heading: "Applications and integration", body: ["Validate the actual application path, drivers, workload, and operating assumptions rather than relying on a logo alone."] },
        ],
      },
      {
        type: "gallery",
        anchor: "partner-roster",
        heading: "Published ecosystem roster",
        intro: ["These organizations are reproduced from Halo Tech’s current official Partners page. Inclusion records the published roster only; it does not by itself establish a current customer relationship, commercial appointment, endorsement, or the scope and validity of any compatibility certificate."],
        layout: "grid",
        fit: "contain",
        items: [
          { src: "/partners/logos/01-kylin-software.png", alt: "Kylin Software logo from Halo Tech’s published ecosystem roster", width: 400, height: 128, caption: "Kylin Software" },
          { src: "/partners/logos/02-uniontech-software.png", alt: "UnionTech Software logo from Halo Tech’s published ecosystem roster", width: 400, height: 128, caption: "UnionTech Software" },
          { src: "/partners/logos/03-nfs-china.png", alt: "NFS China logo from Halo Tech’s published ecosystem roster", width: 400, height: 128, caption: "NFS China" },
          { src: "/partners/logos/04-neesse-software.png", alt: "Neesse Software logo from Halo Tech’s published ecosystem roster", width: 400, height: 128, caption: "Neesse Software" },
          { src: "/partners/logos/05-tongtech.png", alt: "TongTech logo from Halo Tech’s published ecosystem roster", width: 400, height: 128, caption: "TongTech" },
          { src: "/partners/logos/06-baolande.png", alt: "Baolande logo from Halo Tech’s published ecosystem roster", width: 400, height: 128, caption: "Baolande" },
          { src: "/partners/logos/07-primeton.png", alt: "Primeton logo from Halo Tech’s published ecosystem roster", width: 400, height: 128, caption: "Primeton" },
          { src: "/partners/logos/08-apusic.jpg", alt: "Apusic logo from Halo Tech’s published ecosystem roster", width: 300, height: 76, caption: "Apusic" },
          { src: "/partners/logos/09-weaver.jpg", alt: "Weaver logo from Halo Tech’s published ecosystem roster", width: 136, height: 50, caption: "Weaver" },
          { src: "/partners/logos/10-enmotech.png", alt: "Enmotech logo from Halo Tech’s published ecosystem roster", width: 400, height: 128, caption: "Enmotech" },
          { src: "/partners/logos/11-scutech.png", alt: "SCUTech logo from Halo Tech’s published ecosystem roster", width: 400, height: 128, caption: "SCUTech" },
          { src: "/partners/logos/12-dsg.png", alt: "DSG logo from Halo Tech’s published ecosystem roster", width: 400, height: 128, caption: "DSG" },
          { src: "/partners/logos/13-hundsun.png", alt: "Hundsun logo from Halo Tech’s published ecosystem roster", width: 167, height: 64, caption: "Hundsun" },
          { src: "/partners/logos/14-loongson.jpg", alt: "Loongson logo from Halo Tech’s published ecosystem roster", width: 136, height: 50, caption: "Loongson" },
          { src: "/partners/logos/15-dhcc.png", alt: "DHCC logo from Halo Tech’s published ecosystem roster", width: 263, height: 78, caption: "DHCC" },
          { src: "/partners/logos/16-heren-health.png", alt: "Heren Health logo from Halo Tech’s published ecosystem roster", width: 258, height: 76, caption: "Heren Health" },
          { src: "/partners/logos/17-smartdot.png", alt: "Smartdot logo from Halo Tech’s published ecosystem roster", width: 180, height: 74, caption: "Smartdot" },
          { src: "/partners/logos/18-isoft-infrastructure-software.png", alt: "iSOFT Infrastructure Software logo from Halo Tech’s published ecosystem roster", width: 201, height: 58, caption: "iSOFT Infrastructure Software" },
          { src: "/partners/logos/19-cvicse-middleware.png", alt: "Cvicse Middleware logo from Halo Tech’s published ecosystem roster", width: 366, height: 80, caption: "Cvicse Middleware" },
          { src: "/partners/logos/20-china-unicom-digital-technology.png", alt: "China Unicom Digital Technology logo from Halo Tech’s published ecosystem roster", width: 282, height: 72, caption: "China Unicom Digital Technology" },
          { src: "/partners/logos/21-cetc-shentai.png", alt: "CETC Shentai logo from Halo Tech’s published ecosystem roster", width: 344, height: 96, caption: "CETC Shentai" },
          { src: "/partners/logos/22-lanxum.png", alt: "Lanxum logo from Halo Tech’s published ecosystem roster", width: 242, height: 91, caption: "Lanxum" },
          { src: "/partners/logos/23-sunwayworld.png", alt: "SunwayWorld logo from Halo Tech’s published ecosystem roster", width: 281, height: 74, caption: "SunwayWorld" },
          { src: "/partners/logos/24-csu-data.png", alt: "CSU Data logo from Halo Tech’s published ecosystem roster", width: 197, height: 56, caption: "CSU Data" },
          { src: "/partners/logos/25-fiotp.png", alt: "FIOTP logo from Halo Tech’s published ecosystem roster", width: 217, height: 76, caption: "FIOTP" },
          { src: "/partners/logos/26-hangnuo-zhixin.png", alt: "Hangnuo Zhixin logo from Halo Tech’s published ecosystem roster", width: 155, height: 106, caption: "Hangnuo Zhixin" },
          { src: "/partners/logos/27-ronghe-technology.png", alt: "Ronghe Technology logo from Halo Tech’s published ecosystem roster", width: 197, height: 83, caption: "Ronghe Technology" },
          { src: "/partners/logos/28-xiamen-zhiheng.png", alt: "Xiamen Zhiheng logo from Halo Tech’s published ecosystem roster", width: 264, height: 83, caption: "Xiamen Zhiheng" },
          { src: "/partners/logos/29-zcbus.png", alt: "ZCBUS logo from Halo Tech’s published ecosystem roster", width: 169, height: 112, caption: "ZCBUS" },
          { src: "/partners/logos/30-fajiajia.png", alt: "Fajiajia logo from Halo Tech’s published ecosystem roster", width: 256, height: 82, caption: "Fajiajia" },
          { src: "/partners/logos/31-eyou.png", alt: "eYou logo from Halo Tech’s published ecosystem roster", width: 159, height: 52, caption: "eYou" },
          { src: "/partners/logos/32-zhenguan-zhongxin.png", alt: "Zhenguan Zhongxin logo from Halo Tech’s published ecosystem roster", width: 204, height: 66, caption: "Zhenguan Zhongxin" },
          { src: "/partners/logos/33-zhongxin-yunchuang.png", alt: "Zhongxin Yunchuang logo from Halo Tech’s published ecosystem roster", width: 244, height: 67, caption: "Zhongxin Yunchuang" },
          { src: "/partners/logos/34-suma.png", alt: "suma logo from Halo Tech’s published ecosystem roster", width: 400, height: 128, caption: "suma" },
          { src: "/partners/logos/35-china-mobile.png", alt: "China Mobile logo from Halo Tech’s published ecosystem roster", width: 400, height: 128, caption: "China Mobile" },
        ],
      },
      {
        type: "cards",
        anchor: "cooperation-paths",
        heading: "Ways to discuss compatibility or cooperation",
        items: [
          { heading: "Compatibility verification", body: ["Describe the software or hardware combination, versions, intended deployment, and evidence needed to validate it."] },
          { heading: "Technical integration", body: ["Describe the interfaces, deployment boundary, representative use case, and the teams that would own the integration."] },
          { heading: "Commercial or channel inquiry", body: ["Email Halo Tech to open a private discussion. No eligibility decision, appointment, territory, price, or benefit is published on this page."] },
          { heading: "Training or certification inquiry", body: ["Ask Halo Tech to confirm whether a relevant offering currently exists and what scope or prerequisites would apply."] },
        ],
      },
      {
        type: "checklist",
        heading: "What to include in the first email",
        items: [
          "Organization and public website",
          "Country or market of interest",
          "Compatibility, integration, or commercial topic",
          "Relevant product, platform, version, and intended use",
          "Applicable technical, sales, delivery, or support context",
          "Only non-confidential information needed to understand the inquiry",
        ],
      },
      {
        type: "cta",
        anchor: "partner-contact",
        heading: "Open a private ecosystem or partnership conversation.",
        body: ["Use email to share the proposed relationship and its context. Any relationship, scope, authorization, or commercial terms require separate written confirmation."],
        actions: [
          { label: "Email Halo Tech about ecosystem or partnership", href: "mailto:support@halodbtech.com?subject=Halo%20ecosystem%20or%20partnership%20inquiry", kind: "primary" },
          { label: "About Halo Tech", href: "/company/", kind: "secondary" },
        ],
      },
    ],
    withheldModules: [],
  },
  {
    id: "P14",
    status: "active",
    name: "About Halo Tech",
    path: "/company/",
    canonicalPath: "/company/",
    seo: {
      title: "About Halo Tech | Halo Database",
      description: "Meet Halo Tech, its engineering-led database team, full-lifecycle capabilities, company history, innovation record, and qualifications.",
      canonicalPath: "/company/",
      robots: "index, follow",
    },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "About Us" }],
    localNavigation: [
      { label: "Position and vision", anchor: "company-story" },
      { label: "Team and capabilities", anchor: "company-capabilities" },
      { label: "Published company snapshot", anchor: "company-snapshot" },
      { label: "Company timeline", anchor: "company-timeline" },
      { label: "Qualifications", anchor: "company-qualifications" },
    ],
    hero: {
      eyebrow: "ABOUT HALO TECH",
      h1: "Database engineering, from kernel to enterprise rollout.",
      lead: "Halo Tech focuses on next-generation data management. Its leadership brings experience from tier-one financial institutions and global technology companies, while an engineering-led team works across database kernel research, product development, lifecycle maintenance, and enterprise implementation.",
      actions: [
        { label: "Explore Halo Database", href: "/product/", kind: "primary" },
        { label: "Plan a PoC", href: "/request-poc/?source=company", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "prose",
        anchor: "company-story",
        heading: "Focused on practical data infrastructure",
        paragraphs: [
          { text: "Halo Tech develops data-management technology for demanding enterprise systems. The company’s goal is to make database modernization more controllable by connecting kernel engineering with the realities of migration, deployment, operations, and long-term maintenance." },
          { text: "Its leadership and founding team bring experience from financial institutions and global technology companies. That background keeps product work grounded in production constraints, operational ownership, and the evidence enterprises need before changing a core data platform." },
        ],
      },
      {
        type: "cards",
        anchor: "company-capabilities",
        heading: "One team across the database lifecycle",
        intro: ["More than 80% of the team is reported to work in technical roles. Halo Tech combines core research, product delivery, and field implementation instead of treating them as separate handoffs."],
        items: [
          { heading: "Kernel research", body: ["Database internals, compatibility architecture, optimization, storage, and core-engine research."] },
          { heading: "Product engineering", body: ["Release development, tooling, integration, quality, and the work required to turn core technology into an enterprise product."] },
          { heading: "Lifecycle maintenance", body: ["Updates, maintenance, troubleshooting, and operational continuity after deployment."] },
          { heading: "Enterprise implementation", body: ["Assessment, migration, deployment, optimization, and system change in customer environments."] },
        ],
      },
      {
        type: "facts",
        anchor: "company-snapshot",
        heading: "Published company snapshot",
        intro: ["These figures reproduce the official About-page statistics. The source page does not state a measurement date, so they should be read as a published company snapshot rather than a live count."],
        items: [
          { value: "40+", label: "team members" },
          { value: "80%+", label: "technical roles" },
          { value: "36+", label: "intellectual property" },
          { value: "101+", label: "clients" },
          { value: "2", label: "locations" },
        ],
      },
      {
        type: "cards",
        heading: "Five technical capability areas",
        intro: ["The official company profile highlights these capability areas. They are presented as engineering directions, without the source page’s unqualified percentage bars."],
        items: [
          { heading: "Multi-mode parsing engine", body: ["Compatibility work across protocol, parsing, semantics, optimization, and execution paths."] },
          { heading: "DLB and TWR", body: ["Database-aware read distribution and statement-sensitive write routing for defined topologies."] },
          { heading: "Distributed shared storage", body: ["HSM architecture for deployments that require a shared-storage path."] },
          { heading: "Multi-group replication", body: ["Replication design for grouped continuity and deployment requirements."] },
          { heading: "Hybrid deployment", body: ["Architecture choices that combine supported components for a specific environment and workload."] },
        ],
      },
      {
        type: "steps",
        anchor: "company-timeline",
        heading: "From founding-team experience to company development",
        items: [
          { heading: "2013–2018 — Founding Team Experience", body: ["The future founding team accumulated database-migration experience in financial-system projects and studied Oracle and MySQL internals."] },
          { heading: "2019–2020 — Founding Team Experience", body: ["The team advanced its work through a core insurance-system Oracle replacement project before the company was established."] },
          { heading: "2021 — Company Founded", body: ["Halo Tech was established and began releasing the Halo Database product line."] },
          { heading: "2022–2023 — Product and IP Development", body: ["The company expanded its software-copyright and patent portfolio and was included in an MIIT innovation-product map."] },
          { heading: "2024 — Ecosystem Construction", body: ["Compatibility and mutual-certification work expanded across operating-system and processor ecosystems, including Kirin, UnionTech, Kunpeng, and Hygon."] },
          { heading: "2025 — Open-Source Contribution", body: ["Halo Tech launched openHalo as a separate public project focused on MySQL compatibility for PostgreSQL."] },
        ],
      },
      {
        type: "facts",
        heading: "Published innovation and ecosystem record",
        items: [
          { value: "30+", label: "software copyrights" },
          { value: "5+", label: "patents" },
          { value: "1+", label: "utility models" },
          { value: "21+", label: "mutual-certification relationships", body: "This is the official published mutual-certification figure, not a count of channel partners or management-system certificates." },
        ],
      },
      {
        type: "gallery",
        anchor: "company-qualifications",
        heading: "Current management-system certifications",
        intro: ["These five certificate images are reproduced from Halo Tech’s official About page. They document organization-level management systems, not product certification. The certificate holder and scope remain visible in each source image."],
        layout: "grid",
        fit: "contain",
        items: [
          { src: "/company/certifications/iso-20000-1.png", alt: "ISO IEC 20000-1 2018 information technology service management certificate", width: 1587, height: 2245, caption: "ISO/IEC 20000-1:2018 · Certificate 1982025ITSM0129R0N · Valid 29 August 2025–28 August 2028.", href: "/company/certifications/iso-20000-1.png" },
          { src: "/company/certifications/iso-9001.png", alt: "ISO 9001 2015 quality management system certificate", width: 3174, height: 4490, caption: "ISO 9001:2015 · Certificate 19822QL6084R1S · Valid through 28 December 2028.", href: "/company/certifications/iso-9001.png" },
          { src: "/company/certifications/iso-14001.jpg", alt: "ISO 14001 2015 environmental management system certificate", width: 1280, height: 1811, caption: "ISO 14001:2015 · Certificate 19822EL2644R1S · Valid through 28 December 2028.", href: "/company/certifications/iso-14001.jpg" },
          { src: "/company/certifications/iso-27001.png", alt: "ISO IEC 27001 2022 information security management system certificate", width: 1587, height: 2245, caption: "ISO/IEC 27001:2022 · Certificate 19825ISMSH0224R0S · Valid through 28 August 2028.", href: "/company/certifications/iso-27001.png" },
          { src: "/company/certifications/iso-45001.jpg", alt: "ISO 45001 2018 occupational health and safety management system certificate", width: 1280, height: 1811, caption: "ISO 45001:2018 · Certificate 19822SL1419R1S · Valid through 28 December 2028.", href: "/company/certifications/iso-45001.jpg" },
        ],
      },
      {
        type: "gallery",
        heading: "Historical qualifications",
        intro: ["Historical material is separated from current certifications so an expired appraisal is not presented as active."],
        layout: "single",
        fit: "contain",
        items: [
          { src: "/company/certifications/cmmi-level-3-2023.png", alt: "Historical CMMI Development maturity level 3 appraisal result", width: 1733, height: 1200, caption: "CMMI-DEV V2.0 Maturity Level 3 · Appraisal 64404 · Appraised 7 April 2023 · Expired 7 April 2026 · Historical qualification only.", href: "/company/certifications/cmmi-level-3-2023.png" },
        ],
      },
    ],
    withheldModules: [],
  },
  {
    id: "P27",
    status: "active",
    name: "Contact Halo Tech",
    path: "/contact-us/",
    canonicalPath: "/contact-us/",
    seo: {
      title: "Contact Halo Tech | Halo Database",
      description: "Contact Halo Tech by email about the company, Halo Database product access, a proof of concept, product questions, or ecosystem compatibility.",
      canonicalPath: "/contact-us/",
      robots: "index, follow",
    },
    breadcrumb: [
      { label: "Home", href: "/" },
      { label: "About Us", href: "/company/" },
      { label: "Contact Us" },
    ],
    localNavigation: [
      { label: "Choose a path", anchor: "contact-paths" },
      { label: "Email context", anchor: "contact-context" },
      { label: "Contact boundary", anchor: "contact-boundary" },
    ],
    hero: {
      eyebrow: "CONTACT HALO TECH",
      h1: "Start with the question you have.",
      lead: "Website inquiries are handled by email. Choose the path below for company questions, Halo Database product access, a proof of concept, an existing-product question, or ecosystem compatibility.",
      actions: [
        { label: "Email Halo Tech", href: "mailto:support@halodbtech.com?subject=Halo%20Tech%20inquiry", kind: "primary" },
        { label: "Product Access & Licensing", href: "/contact-sales/", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "cards",
        anchor: "contact-paths",
        heading: "Choose the right path",
        items: [
          { heading: "Product access and licensing", body: ["For Halo Database installation packages, environment-matched licenses, procurement, or commercial availability."], actions: [{ label: "Product Access & Licensing", href: "/contact-sales/", kind: "text" }] },
          { heading: "Plan a proof of concept", body: ["For a defined workload, target environment, and decision criteria."], actions: [{ label: "Plan a PoC", href: "/request-poc/?source=contact-us", kind: "text" }] },
          { heading: "Existing-product question", body: ["Include the Halo version, operating environment, and a concise description of the question. Any applicable support scope is confirmed separately."], actions: [{ label: "Email a product question", href: "mailto:support@halodbtech.com?subject=Halo%20Database%20product%20question", kind: "text" }] },
          { heading: "Company inquiry", body: ["For a factual question about Halo Tech or this website."], actions: [{ label: "Email a company inquiry", href: "mailto:support@halodbtech.com?subject=Halo%20Tech%20company%20inquiry", kind: "text" }] },
          { heading: "Ecosystem or partnership inquiry", body: ["For compatibility verification, technical integration, or a private partnership discussion."], actions: [{ label: "Review the Partners page", href: "/partners/", kind: "text" }] },
          { heading: "openHalo", body: ["For the separate GPL-3.0 open-source project, continue to its project page and public repository."], actions: [{ label: "Explore openHalo", href: "/open-halo/", kind: "text" }] },
        ],
      },
      {
        type: "checklist",
        anchor: "contact-context",
        heading: "What to include in the first email",
        items: [
          "The topic and the decision or outcome you are working toward",
          "Organization, role, and country or region",
          "Relevant Halo version, source system, or target environment when applicable",
          "Enough non-confidential context to route the inquiry",
        ],
      },
      {
        type: "callout",
        anchor: "contact-boundary",
        label: "CONTACT BOUNDARY",
        heading: "An email starts a conversation; it does not confirm scope or availability",
        body: [
          "Sending an email does not confirm product access, a license, PoC availability, support entitlement, commercial terms, regional availability, partnership status, or a response time.",
          "Do not include credentials, license files, production data, customer records, security secrets, or confidential diagnostic material in the first email. Discuss an appropriate transfer method before sharing sensitive material.",
        ],
      },
      {
        type: "cta",
        heading: "Contact Halo Tech by email.",
        body: ["Use a descriptive subject line and include only the context needed to understand the inquiry."],
        actions: [{ label: "Email Halo Tech", href: "mailto:support@halodbtech.com?subject=Halo%20Tech%20inquiry", kind: "primary" }],
      },
    ],
    withheldModules: [],
  },
  {
    id: "P15",
    status: "active",
    name: "Plan a proof of concept",
    path: "/request-poc/",
    canonicalPath: "/request-poc/",
    seo: { title: "Plan a Halo Database PoC", description: "Coordinate a Halo Database installation package, environment-specific license, and workload-focused proof of concept with Halo Tech.", canonicalPath: "/request-poc/", robots: "noindex, follow" },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Plan a PoC" }],
    localNavigation: [
      { label: "Product access", anchor: "poc-product-access" },
      { label: "PoC process", anchor: "poc-process" },
      { label: "What to prepare", anchor: "poc-preparation" },
      { label: "Contact", anchor: "poc-contact" },
    ],
    hero: {
      eyebrow: "PLAN A PROOF OF CONCEPT",
      h1: "Plan the workload. Halo Tech coordinates product access.",
      lead: "Halo Database is commercial, licensed software. Installation packages and evaluation licenses are coordinated with Halo Tech. openHalo is a separate GPL-3.0 open-source project. A PoC begins by qualifying the workload and target environment with the company.",
      actions: [
        { label: "Email Halo Tech about a PoC", href: "mailto:support@halodbtech.com?subject=Halo%20Database%20PoC%20access", kind: "primary" },
        { label: "Open the evaluation checklist", href: "/resources/evaluation-checklist/", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "callout",
        anchor: "poc-product-access",
        label: "PRODUCT ACCESS",
        heading: "The installation package and license come from Halo Tech",
        body: ["Halo Database is commercial, licensed software. Installation packages and evaluation licenses are coordinated with Halo Tech. openHalo is a separate GPL-3.0 open-source project.", "The official installation guidance directs evaluators to Halo Tech or an authorized agent for the package and license file. The license is generated for server-environment information and may encode validity, release, and connection limits; if it does not match the environment, the database will not start."],
      },
      {
        type: "steps",
        anchor: "poc-process",
        heading: "From qualification to evidence",
        items: [
          { heading: "1. Frame the decision", body: ["Name the application, source database, business reason, owners, acceptance criteria, and the questions the PoC must resolve."] },
          { heading: "2. Share the target environment", body: ["Provide the operating system, processor architecture, server count, topology, database modes, and optional components expected in the test."] },
          { heading: "3. Confirm package and license", body: ["Halo Tech confirms the applicable release and build, then coordinates the installation package and a license prepared for the agreed PoC environment."] },
          { heading: "4. Install and verify", body: ["Install the supplied build, place the matching license, initialize the database, and verify that the intended modes and services start correctly."] },
          { heading: "5. Run the workload and record the decision", body: ["Test representative behavior, performance, continuity, recovery, integrations, and operator tasks; retain the evidence, exceptions, remediation, and next decision."] },
        ],
      },
      {
        type: "checklist",
        anchor: "poc-preparation",
        heading: "Prepare before qualification",
        items: [
          "Organization, role, country or region, and business contact",
          "Source database, version, application purpose, and criticality",
          "Required Oracle, MySQL, or PostgreSQL operating mode and database dependencies",
          "Target operating system, processor architecture, server count, and topology",
          "Representative data, workload profile, continuity, recovery, and operating requirements",
          "Acceptance criteria, decision owners, and target decision date",
        ],
      },
      {
        type: "callout",
        label: "SAFE COORDINATION",
        heading: "Exchange sensitive environment details through an agreed channel",
        body: ["Do not send credentials, production records, customer data, or detailed hardware identifiers in an initial public email. First describe the environment at a high level; Halo Tech can then agree a secure method for any server information needed to prepare the license."],
      },
      {
        type: "links",
        anchor: "poc-contact",
        heading: "Start the conversation",
        actions: [
          { label: "Email Halo Tech about a PoC", href: "mailto:support@halodbtech.com?subject=Halo%20Database%20PoC%20access", kind: "primary" },
          { label: "Review the PoC method", href: "/evaluation/", kind: "text" },
        ],
      },
      {
        type: "cta",
        heading: "Ready to qualify a Halo Database PoC?",
        body: ["Send the high-level workload, target platform, and evaluation goal. Package, license, technical scope, timing, and regional availability are confirmed during qualification."],
        actions: [
          { label: "Email Halo Tech about a PoC", href: "mailto:support@halodbtech.com?subject=Halo%20Database%20PoC%20access", kind: "primary" },
          { label: "Review commercial planning", href: "/contact-sales/?source=request-poc", kind: "secondary" },
        ],
      },
    ],
    withheldModules: [{ id: "form-shell", status: "absent", requires: ["A06", "A12"] }],
  },
  {
    id: "P17",
    status: "active",
    name: "Prepare a demo brief",
    path: "/request-demo/",
    canonicalPath: "/request-demo/",
    seo: { title: "Prepare a Halo Database Demo Brief", description: "Choose the Halo capabilities to organize for a future product introduction.", canonicalPath: "/request-demo/", robots: "noindex, follow" },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Prepare a Demo Brief" }],
    localNavigation: [],
    hero: { eyebrow: "PREPARE A DEMO BRIEF", h1: "Choose the Halo capabilities you want to explore.", lead: "Use this route to prepare a future product-introduction brief. A demo can refine technical questions, but it does not validate application compatibility, performance, recovery objectives, or production readiness.", actions: [{ label: "Explore the platform", href: "/product/", kind: "primary" }, { label: "Plan a PoC", href: "/request-poc/?source=demo", kind: "secondary" }] },
    blocks: [
      { type: "cards", heading: "Possible demo topics", items: [{ heading: "Compatibility and E5", body: ["Oracle, MySQL, and native PostgreSQL paths."] }, { heading: "Core architecture", body: ["Transactions, storage, indexing, and partitioning."] }, { heading: "Continuity", body: ["Replication, RMAN2, and Shield."] }, { heading: "Distributed data", body: ["DLB, TWR, HSM, and HDS."] }, { heading: "Operations", body: ["HWR, system visibility, resource controls, and extensions."] }] },
      { type: "comparison", heading: "What a demo can and cannot establish", columns: ["A demo can", "A demo cannot"], rows: [["Orient business and technical stakeholders", "Prove that an application moves unchanged"], ["Identify relevant architecture paths", "Establish representative performance or capacity"], ["Surface questions for evaluation", "Set an RPO, RTO, or SLA"], ["Help decide whether to prepare a PoC", "Estimate migration effort or production readiness"]] },
      { type: "callout", label: "INQUIRY STATUS", heading: "This remains an informational route", body: ["The current source set does not include an approved public scheduling endpoint, privacy notice, or consent flow. No form or scheduling action is published."] },
    ],
    withheldModules: [{ id: "form-shell", status: "absent", requires: ["A06", "A12"] }],
  },
  {
    id: "P16",
    status: "active",
    name: "Product access and commercial planning",
    path: "/contact-sales/",
    canonicalPath: "/contact-sales/",
    seo: { title: "Halo Database Product Access & Licensing", description: "Contact Halo Tech about Halo Database installation packages, licenses, PoC access, procurement, and regional availability.", canonicalPath: "/contact-sales/", robots: "noindex, follow" },
    breadcrumb: [{ label: "Home", href: "/" }, { label: "Product Access & Licensing" }],
    localNavigation: [],
    hero: {
      eyebrow: "PRODUCT ACCESS AND LICENSING",
      h1: "Discuss product access, licensing, and commercial fit.",
      lead: "Halo Database is commercial, licensed software. Installation packages and evaluation licenses are coordinated with Halo Tech. openHalo is a separate GPL-3.0 open-source project. Contact the company for procurement, deployment scope, and product availability.",
      actions: [
        { label: "Email Halo Tech about product access", href: "mailto:support@halodbtech.com?subject=Halo%20Database%20product%20access", kind: "primary" },
        { label: "Plan a PoC", href: "/request-poc/?source=sales", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "callout",
        label: "COMMERCIAL PRODUCT",
        heading: "Halo Database and openHalo have different access models",
        body: ["Halo Database is commercial, licensed software. Installation packages and evaluation licenses are coordinated with Halo Tech. openHalo is a separate GPL-3.0 open-source project.", "Halo Database packages and license files are not obtained from the openHalo repository. A PoC or deployment requires Halo Tech to confirm the applicable product build, target environment, and license scope."],
      },
      {
        type: "cards",
        heading: "Contact Halo Tech",
        items: [
          { label: "EMAIL", heading: "support@halodbtech.com", body: ["Product packages, licenses, PoC coordination, procurement, commercial questions, and regional availability."], actions: [{ label: "Email Halo Tech about product access", href: "mailto:support@halodbtech.com?subject=Halo%20Database%20product%20access", kind: "text" }] },
        ],
      },
      {
        type: "checklist",
        heading: "Prepare the product-access context",
        items: [
          "Organization, role, country or region, and business contact",
          "Whether the request is for a PoC, product introduction, procurement review, or planned deployment",
          "Source database, application, and operating modes of interest",
          "Target operating system, processor architecture, server count, and topology",
          "Expected evaluation or deployment stage, timing, and decision owners",
          "Commercial, procurement, licensing, or service-availability questions",
        ],
      },
      {
        type: "cards",
        heading: "Choose the right conversation",
        items: [
          { heading: "Defined workload", body: ["Use the PoC path when a specific application, target environment, and acceptance criteria are known."], actions: [{ label: "Plan a PoC", href: "/request-poc/?source=sales-card", kind: "text" }] },
          { heading: "Product introduction", body: ["Use the demo path to orient stakeholders and refine product questions before a workload is ready."], actions: [{ label: "Prepare a demo brief", href: "/request-demo/?source=sales-card", kind: "text" }] },
          { heading: "Open-source exploration", body: ["Use openHalo when the goal is to inspect, build, or contribute to the public MySQL-compatibility project."], actions: [{ label: "Explore openHalo", href: "/open-halo/", kind: "text" }] },
        ],
      },
      {
        type: "callout",
        label: "QUALIFICATION BOUNDARY",
        heading: "The exact package, license, support scope, and availability are confirmed for the engagement",
        body: ["An inquiry does not by itself confirm PoC acceptance, package entitlement, licensing terms, price, support level, or regional availability. Halo Tech confirms those details after reviewing the intended environment and use."],
      },
      {
        type: "cta",
        heading: "Start with the access question you have.",
        actions: [
          { label: "Email Halo Tech about product access", href: "mailto:support@halodbtech.com?subject=Halo%20Database%20product%20access", kind: "primary" },
          { label: "Plan a PoC", href: "/request-poc/?source=sales-final", kind: "secondary" },
        ],
      },
    ],
    withheldModules: [{ id: "form-shell", status: "absent", requires: ["A06", "A12"] }],
  },
  {
    id: "P26",
    status: "active",
    name: "openHalo open-source project",
    path: "/open-halo/",
    canonicalPath: "/open-halo/",
    seo: {
      title: "openHalo Open-Source Database Project | Halo Tech",
      description: "Explore openHalo, a GPL-3.0 PostgreSQL project for commonly used MySQL dialects and protocol, designed to support migrations with fewer code changes.",
      canonicalPath: "/open-halo/",
      robots: "index, follow",
    },
    breadcrumb: [
      { label: "Home", href: "/" },
      { label: "Open Source" },
      { label: "openHalo" },
    ],
    localNavigation: [
      { label: "Project background", anchor: "open-halo-background" },
      { label: "Compatibility direction", anchor: "compatibility-direction" },
      { label: "How it works", anchor: "how-open-halo-works" },
      { label: "Core capabilities", anchor: "open-halo-capabilities" },
      { label: "Teaching and community", anchor: "teaching-community" },
      { label: "Community material", anchor: "community-material" },
      { label: "Related projects", anchor: "related-projects" },
      { label: "Contribute", anchor: "contribute" },
    ],
    hero: {
      eyebrow: "GPL-3.0 OPEN SOURCE",
      h1: "openHalo: open-source MySQL compatibility for PostgreSQL.",
      lead: "openHalo is a Halo Tech-initiated GPL-3.0 project that helps PostgreSQL work with applications using commonly used MySQL dialects, semantics, and the MySQL communication protocol—so migration can require fewer code changes, subject to workload validation.",
      actions: [
        { label: "View on GitHub", href: "https://github.com/HaloTech-Co-Ltd/openHalo", kind: "primary" },
        { label: "Visit openHalo.org", href: "https://www.openhalo.org/", kind: "secondary" },
      ],
    },
    blocks: [
      {
        type: "gallery",
        heading: "A public open-source project",
        intro: ["The project source, license, build instructions, contribution guide, issue history, and discussions are publicly available."],
        layout: "single",
        fit: "contain",
        items: [
          { src: "/open-halo/openhalo-logo.png", alt: "Official openHalo project mark", width: 32, height: 29, caption: "Official openHalo project mark from the public repository." },
        ],
      },
      {
        type: "callout",
        label: "PRODUCT BOUNDARY",
        heading: "openHalo is not a Halo Database installation package",
        body: ["Halo Database is commercial, licensed software. Installation packages and evaluation licenses are coordinated with Halo Tech. openHalo is a separate GPL-3.0 open-source project."],
      },
      {
        type: "prose",
        anchor: "open-halo-background",
        heading: "Why openHalo exists",
        paragraphs: [
          { text: "PostgreSQL and MySQL have different communication protocols, dialects, semantics, catalogs, and ecosystem expectations. Applications written for MySQL can therefore require more than a data copy before they can work with PostgreSQL." },
          { text: "openHalo develops that compatibility path in public. Its goal is to let developers inspect the implementation, build it from source, test familiar application workflows, document gaps, and improve the project through reproducible contributions." },
        ],
      },
      {
        type: "cards",
        anchor: "compatibility-direction",
        heading: "Compatibility at the surfaces applications use",
        intro: ["The repository describes support for commonly used MySQL dialects, semantics, and communication protocol. That wording defines the project direction; it is not a promise of complete compatibility."],
        items: [
          { heading: "MySQL communication protocol", body: ["Expose a connection path for MySQL-facing clients and application stacks."] },
          { heading: "Common SQL and semantics", body: ["Interpret commonly used MySQL syntax and behavior on a PostgreSQL-based system."] },
          { heading: "Clients and drivers", body: ["Let teams test familiar MySQL command-line clients, connectors, drivers, frameworks, and development workflows."] },
          { heading: "Fewer migration changes", body: ["Reduce the code that may need to change for MySQL 5.7-and-later applications, while keeping workload-specific gaps visible."] },
        ],
      },
      {
        type: "gallery",
        heading: "A repository demonstration",
        intro: ["This repository image demonstrates a MySQL client creating and querying a table, followed by a PostgreSQL client reading the same row. It illustrates the intended connection model, not universal application compatibility."],
        layout: "single",
        fit: "contain",
        items: [
          { src: "/open-halo/project-overview.png", alt: "Terminal demonstration using MySQL and PostgreSQL clients with openHalo", width: 645, height: 1037, caption: "Source-build demonstration published in the openHalo repository.", href: "/open-halo/project-overview.png" },
        ],
      },
      {
        type: "prose",
        anchor: "how-open-halo-works",
        heading: "How to inspect and build the project",
        paragraphs: [
          { text: "openHalo starts from PostgreSQL and adds compatibility work where MySQL-facing applications meet the database: connection protocol, parsing, SQL semantics, and related behavior. The public repository is the canonical place to inspect what is implemented and what remains under development." },
          { text: "The Quick Tutorial is a source-build path. Its broad-listen and host-access examples are suitable only as development or test starting points; production security, network exposure, authentication, and operating policy require separate review." },
        ],
        actions: [
          { label: "Build from Source", href: "https://github.com/HaloTech-Co-Ltd/openHalo#quick-tutorial", kind: "primary" },
          { label: "View GPL-3.0 License", href: "https://github.com/HaloTech-Co-Ltd/openHalo/blob/master/LICENSE", kind: "text" },
        ],
      },
      {
        type: "cards",
        anchor: "open-halo-capabilities",
        heading: "Core project capabilities",
        items: [
          { heading: "Protocol-facing access", body: ["A MySQL communication path for compatible clients and drivers."] },
          { heading: "Dialect interpretation", body: ["Implementation work around commonly used MySQL statements, types, functions, and behavior."] },
          { heading: "PostgreSQL foundation", body: ["A PostgreSQL-based core that remains inspectable through the public source tree."] },
          { heading: "Source-first validation", body: ["Build instructions, tests, issue history, and discussions let contributors verify exact behavior instead of relying on a blanket compatibility percentage."] },
        ],
      },
      {
        type: "prose",
        anchor: "teaching-community",
        heading: "Teaching practice and community participation",
        paragraphs: [
          { text: "Halo Tech’s official project page reports that openHalo has been used as a graduate teaching-practice project at Peking University. The teaching path gives students a real database codebase through which to study systems engineering and contribute practical improvements." },
          { text: "Participation is broader than code. Reproducible tests, documentation corrections, examples, compatibility reports, design discussion, and careful issue triage all help make the project easier to evaluate and maintain." },
        ],
      },
      {
        type: "gallery",
        anchor: "community-material",
        heading: "Community material",
        intro: ["These archived captures were published on Halo Tech’s official openHalo page to show public discussion and project visibility. Statements visible inside third-party captures belong to their original authors and are not adopted here as Halo Database or openHalo performance, compatibility, or endorsement claims."],
        layout: "wall",
        fit: "cover",
        items: [
          { src: "/open-halo/community/community-03.png", alt: "Public social-media post sharing the openHalo project", width: 1264, height: 1126, caption: "Public project-sharing capture reproduced from the official openHalo page.", href: "/open-halo/community/community-03.png" },
          { src: "/open-halo/community/community-04.png", alt: "Community article discussing openHalo support in Pigsty", width: 501, height: 721, caption: "Community integration article capture reproduced from the official openHalo page.", href: "/open-halo/community/community-04.png" },
          { src: "/open-halo/community/community-09.png", alt: "PostgreSQL website news listing for the openHalo release", width: 1280, height: 731, caption: "openHalo release listing shown on the PostgreSQL community website.", href: "/open-halo/community/community-09.png" },
          { src: "/open-halo/community/community-10.png", alt: "Open-source news listing mentioning openHalo in Russian", width: 1190, height: 960, caption: "Open-source news listing capture reproduced from the official openHalo page.", href: "/open-halo/community/community-10.png" },
        ],
      },
      {
        type: "cards",
        anchor: "related-projects",
        heading: "Other open-source projects",
        intro: ["These repositories appear in Halo Tech’s published open-source project list. Review each repository’s current status, license, and fitness before use."],
        items: [
          { heading: "openHalo", body: ["MySQL compatibility work for a PostgreSQL-based database."], actions: [{ label: "Repository", href: "https://github.com/HaloTech-Co-Ltd/openHalo", kind: "text" }] },
          { heading: "bilogical", body: ["A preview logical-decoding extension intended to help prevent replication loopback on PostgreSQL versions before 16."], actions: [{ label: "Repository", href: "https://github.com/HaloTech-Co-Ltd/bilogical", kind: "text" }] },
          { heading: "MonetDB_fdw", body: ["A PostgreSQL foreign-data wrapper for accessing MonetDB data."], actions: [{ label: "Repository", href: "https://github.com/HaloTech-Co-Ltd/MonetDB_fdw", kind: "text" }] },
          { heading: "halo_migrate", body: ["Tooling for online table-structure redefinition workflows."], actions: [{ label: "Repository", href: "https://github.com/HaloLab001/halo_migrate", kind: "text" }] },
          { heading: "hmt-web", body: ["A web-interface migration-tool project for Oracle and MySQL source workflows."], actions: [{ label: "Repository", href: "https://github.com/HaloLab001/hmt-web", kind: "text" }] },
          { heading: "PG4ML", body: ["A PostgreSQL extension project for building, managing, training, and using machine-learning models."], actions: [{ label: "Repository", href: "https://gitee.com/guotiecheng/plpgsql_pg4ml", kind: "text" }] },
        ],
      },
      {
        type: "cards",
        anchor: "contribute",
        heading: "Choose a contribution path",
        items: [
          { heading: "Code", body: ["Build the source, run relevant checks, and submit focused pull requests."] },
          { heading: "Documentation", body: ["Clarify build steps, behavior, examples, or limitations that you can reproduce."] },
          { heading: "Issues", body: ["Browse the current issue record and add useful context where contribution permissions allow."] },
          { heading: "Discussion", body: ["Use GitHub Discussions for project questions and design conversation."] },
        ],
      },
      {
        type: "links",
        heading: "Project links",
        actions: [
          { label: "Contribution Guide", href: "https://github.com/HaloTech-Co-Ltd/openHalo/blob/master/CONTRIBUTING.md", kind: "primary" },
          { label: "Browse Issues", href: "https://github.com/HaloTech-Co-Ltd/openHalo/issues", kind: "secondary" },
          { label: "Join the Discussion", href: "https://github.com/HaloTech-Co-Ltd/openHalo/discussions", kind: "text" },
        ],
      },
      {
        type: "cta",
        heading: "Explore the code—or take the commercial product path.",
        body: ["Use the public repositories for openHalo. For a licensed Halo Database package and evaluation license, coordinate directly with Halo Tech."],
        actions: [
          { label: "View on GitHub", href: "https://github.com/HaloTech-Co-Ltd/openHalo", kind: "primary" },
          { label: "Email Halo Tech about product access", href: "mailto:support@halodbtech.com?subject=Halo%20Database%20product%20access", kind: "secondary" },
        ],
      },
    ],
    withheldModules: [],
  },
  {
    id: "P20",
    status: "active",
    name: "Page not found",
    path: "/404/",
    canonicalPath: null,
    seo: { title: "Page not found | Halo Database", description: null, canonicalPath: null, robots: "noindex, follow" },
    breadcrumb: [],
    localNavigation: [],
    hero: { eyebrow: null, h1: "Page not found.", lead: "The page may have moved, or the address may be incorrect. Continue with one of the destinations below.", actions: [{ label: "Go to Home", href: "/", kind: "primary" }, { label: "Explore the platform", href: "/product/", kind: "text" }, { label: "Review documentation", href: "/resources/documentation/", kind: "text" }] },
    blocks: [],
    withheldModules: [],
  },
] as const satisfies readonly ActiveSitePage[];
